### ISSUE TITLE
Strange album grouping if group/TIT1 tag set

### ISSUE THREAD

**Issue by bennybp** [strawberrymusicplayer/strawberry#1018]
**Describe the bug**
If files have a song grouping tag set (TIT1 for ID3), albums end up being duplicated for each grouping. This is a bit odd, since a song's group is usually something unrelated to the album.

I interpret the grouping tag to mean it's part of a larger work, (i.e., grouping="Symphony No. 9", title="1. Allegro"), although you might have a different interpretation.

Either way, grouping the collection by album causes albums to be duplicated, blowing up the album list.

Git bisect reports this is the commit where it was introduced: https://github.com/strawberrymusicplayer/strawberry/commit/3c8d0ebd52562937dedb453338f65ae3754dfa24

Happy to open a PR if needed. The fix looks relatively simple

**To Reproduce**
Import music with grouping tags, and group collection by album

**Expected behavior**
Album grouping should result in one entry per album in the collection list

**Screenshots:**
![image](https://user-images.githubusercontent.com/4708439/183671000-ae1cc92e-5bba-48f4-8ea4-b769e0110eb9.png)

**System Information:**
 - Operating system: Gentoo Linux
 - Strawberry Version: 1.0.7

**Additional context**
None

**Comment by jonaski** [comment]
The change was intentional since we were already using grouping to separate albums when "Year - Album" was used, and some users wanted the behavior.
But since not everyone want the behavior I suggest to create an opt-in collection tool button checkbox to separate albums with different groupings.
It would be great if you could make a
