### ISSUE TITLE
Strawberry is buffering forever

### ISSUE THREAD

**Issue by slashformotion** [strawberrymusicplayer/strawberry#1020]
**Describe the bug**
Strawberry is buffering forever, the song is never played.

**To Reproduce**
Well I suppose i missed something in the configuration so you will find a screenshot below of the buffering related settings.

**Expected behavior**
I expected buffering to stop eventually and music to be played then.

**Screenshots:**
![image](https://user-images.githubusercontent.com/45801817/184873980-ab87787f-75fa-4403-a406-deb259b5d5e4.png)

**System Information:**
 - Operating system: ArchLinux kernel 5.18.16 x86_64
 - Strawberry Version: 1.0.7

**Additional context**
here is my audio config
![image](https://user-images.githubusercontent.com/45801817/184874730-d56a1570-94c3-4391-9fe3-f422a503e333.png)

---
PS: my english is terrible, I apologize in advance for the grammar mistakes.

**Comment by jonaski** [comment]
It works here, and no-one else has reported this. So I need more details about what circumstances this happens.
What filesystem is `/tmp` and how much space is available?
Does it work if you turn off buffering by setting buffer duration to 0?
Does for example.: `gst-launch-1.0 playbin audio-sink="alsasink device=hw:0,0" uri=file:///path/filename` work?

**Comment by slashformotion** [comment]
looks like setting the buffer duration to 0 works

**Comment by bug-df** [comment]
I was also getting a lot of buffering after upgrading to 1.0.10
Reducing buffer duration reduced the problem but it still cuts out occasionally (3 or 4 times during 5-6 minute track 8.7MB mp3)
On Lubuntu 18.04 with 45% of 8GB of Ram "used" Processor load too small to register (System monitor shows strawberry using about 1.2%, nothing else using significantly more - FF 1-2%, TB <1%), pulling tracks off a SATA hard-disk (with 90GB free).
 /tmp is on the system drive SSD with 3.9GB free. 

i.e. the system looks lightly loaded..

`gst-launch-1.0 playbin audio-sink="alsasink device=hw:0,0" uri=file:///path/filename` seems to work without delays, but possibly significantly running this instruction prompted me to install gstreamer1.0-tools.  Should this have been loaded as a dependency?
(When running from CLI I got:
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
Redistribute latency...
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstAudioSinkClock
Got EOS from element "playbin0".
Execution ended after 0:06:03.548330143
Setting pipeline to PAUSED ...
Setting pipeline to READY ...
Setting pipeline to NULL ...
Freeing pipeline ...
)
Since installing gstreamer, it seems to be running with only occasional cutting out
(I originally installed in Nov 2018 I think via the lubuntu "Software store", and have updated whenever the OS Software Updater prompted me to do so. I have not knowingly removed gstreamer.)

**Comment by Turun** [comment]
I had the same issue, double clicking on a song would play, but with the setting to "repeat track" it would hang trying to play the song again.  I am running Arch with I think `pipewire` as my audio system, but I also have `pipewire-pulse` and `pipewire-jack` installed

- Buffering is set to 4000ms, low watermark 0.33, high watermark 0.99
- `gst-launch-1.0 playbin audio-sink="alsasink device=hw:0,0" uri=file:///path/filename.opus` played fine. 
- Because the song played by `gst-launch-1.0` was so loud and my `pa-applet` that is started at boot was broken, I launched a new instance of `pa-applet` (A restart may have fixed that too, but I didn't want to shut down my PC)

...and now it works! I can start a song by double clicking and it loops indefinitely. 

- After killing both instances of `pa-applet` (the ad-hoc one and the broken one) it now doesn't work again.
- I installed `gst-plugin-pipewire` and now it works again.
- Uninstalled `gst-plugin-pipewire`, it continues to work.

To the best of my knowledge these are all the changes I did for testing just now. It seems so bonkers though that I get the feeling that I must have missed something that happened on my machine. Good luck figuring that one out, lmao! 
If I remember I'll report if it continues to work after a reboot.

**Comment by jonaski** [comment]
gst-plugin-pipewire is for video only (https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/262)
There isn't a pipewire plugin for GStreamer, so you are using PulseAudio emulation, and it has many issues at least when used with all the GStreamer features we have in Strawberry.
A better option is to use PulseAudio or ALSA directly if you want a more stable experience.

**Comment by Turun** [comment]
Blaming Pipewire seems reasonable to me XD

I updated (`sudo pacman -Syu`) and everything works after a reboot. So no progress in pinpointing the reason of the bug, but more stuff for people with the same issue to try out.

**Comment by dtl131** [comment]
I'm having the same issue where Strawberry 1.0.23 gets stuck on Buffering - 0%. It only happens on Opus files. It's been happening to me for a long time, even back before I started using Pipewire, so please don't blame Pipewire. I've tried running Strawberry from the terminal in verbose mode, but I didn't see any useful output. It just outputs messages on the previous track and it doesn't look like it's even trying to advance to the next track.

**Comment by guprobr** [comment]
I'm experiencing same thing but with Tidal too. Oopus and Tidal and Qobus. I don't have time lately to debug properly.

The playlists are huge. huge. +100k
It happens to me when resuming a previous sesssion that had an asset already playing. I have to kill -9 and then, without resume/autoplay, it does not happen. I didn't experience this at normal runtime, only while opening the library with a media about to be resumed.  Program gets stuck, unresponsive.

This could be a threading issue.
