### ISSUE TITLE
(macOS) Strawberry 1.0.8 not starting, wrong rpath for libgcc_s.1.1.dylib

### ISSUE THREAD

**Issue by geroyche** [strawberrymusicplayer/strawberry#1025]
**Describe the bug**
Strawberry instantly closes on Apple Mac M1. This started with strawberry-1.0.7.17.ga647f63b-x86_64.dmg

This most likely correlates to your commits regarding CI for MacOS on August 7.

I know you don't support Apple Silicone, but Strawberry was working fine, and I will (have to) stick with
strawberry-1.0.7.6.g538c759f-x86_64.dmg
now.

Feel free to close this issue, or maybe the error message helps point you to an easy fix.

**Additional context**

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: '/usr/local/opt/gcc/lib/gcc/11/libgcc_s.1.1.dylib'
Referenced from: '/Applications/strawberry.app/Contents/Frameworks/libgcc_s.1.dylib'
Reason: tried: '/usr/local/opt/gcc/lib/gcc/11/libgcc_s.1.1.dylib' (no such file), '' (no such file), '' (no such file)
(terminated at launch; ignore backtrace)

**Comment by jonaski** [comment]
It's not related to sillicon, it's because `libgcc_s.1.1.dylib` is missing in the dmg, so 1.0.8 broken in that case.

**Comment by big610** [comment]
Intel also a problem. Knew immediately a possible problem seeing 1.0.7 48.4 MB, 1.0.8 73.8 MB.
dmg image can be seen on Intel Catalina. If it was M1 the image would be grey overplayed.
Back to 1.0.7, running perfectly.
1.0.8 strawberry cannot be opened because of a problem. Check with the developer to make sure strawberry works with this version of macOS. You may need to reinstall the application. Be sure to install any available updates for the application and macOS. Click Report to see more detailed information and send a report to Apple. 
Report: if you tell me where you want sent.

**Comment by jonaski** [comment]
The file actually there, it's just the rpath that's wrong, because of this error:
```
Log:  inspecting "/usr/local/lib/gcc/11/libgcc_s.1.dylib"
ERROR: Could not parse otool output line: "\t/usr/local/opt/gcc/lib/gcc/11/libgcc_s.1.1.dylib (compatibility version 1.0.0, current version 1.1.0, reexport)"
```
Still can't believe I missed that.

**Comment by jonaski** [comment]
To fix:
`install_name_tool -change /usr/local/opt/gcc/lib/gcc/11/libgcc_s.1.1.dylib /Applications/strawberry.app/Contents/Frameworks/libgcc_s.1.dylib /Applications/strawberry.app/Contents/Frameworks/libgcc_s.1.dylib`

**Comment by monochromec** [comment]
> To fix:
> 
> ```
> install_name_tool -change /usr/local/opt/gcc/lib/gcc/11/libgcc_s.1.1.dylib /Applications/strawberry.app/Contents/Frameworks/libgcc_s.1.dylib /Applications/strawberry.app/Contents/Frameworks/libgcc_s.1.dylib
> ```

Workaround works on M1 12.5.1.

**Comment by jonaski** [comment]
New release available now.
