### ISSUE TITLE
Strawberry 1.0.8 not in PPA

### ISSUE THREAD

**Issue by Yodo13** [strawberrymusicplayer/strawberry#1030]
Hi, I get Strawberry through the PPA, but the latest version is not available. I suppose this is related to the failures to build, as seen in the top right of https://launchpad.net/~jonaski/+archive/ubuntu/strawberry

**System Information:**
 - Operating system: Linux Mint 21 (Ubuntu Jammy)
 - Strawberry Version: 1.0.8

**Comment by jonaski** [comment]
It was because of a simple error in the debian control file, fixed (https://github.com/strawberrymusicplayer/strawberry/commit/77983445cebba9dd13bdb83729572e9f99426835). But apparently I can't push the change without bumping the version number. However I will need to make a new release anyway because of the macOS release being completely broken.

**Comment by Yodo13** [comment]
Sounds fine. Thanks for fixing and thanks for Strawberry!

**Comment by drbldrbl** [comment]
It's not coming through in 1.0.9 Ubuntu 22.04.1 either...

**Comment by jonaski** [comment]
It's not finished building yet, the Ubuntu PPA on https://buildbot.strawberrymusicplayer.org/#/console needs to go to green.

**Comment by drbldrbl** [comment]
Thank you for the timely reply; just love the player. Thanks so much for it.
