### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by juliavetter** [strawberrymusicplayer/strawberry#1046]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
A possible memory leak when using the organize files dialog. 

**To Reproduce**
When organizing files Strawberry uses more and more memory, and when the process is complete the memory usage stays high. When trying to organize my entire library (~230GB) the program used up to 30GB of memory, then I think it failed gracefully midway through. My system still had memory to spare, albeit only swapfile space. The program had to be restarted to free the memory once the process was finished. It should be noted that most of the songs (90+%) in my library were already organized, I was just doing this to update filenames after minor tag changes. 

**Expected behavior**
The program shouldn't use more than a few hundred megabytes of memory and memory usage should be basically constant when organizing files as it should be freed after files are copied. 

**Screenshots:**
The exact naming scheme and options I use for organizing:
![Screenshot_2022-09-21_00-38-32](https://user-images.githubusercontent.com/47370906/191444962-19dbf161-73c4-47e6-80b9-33909a141372.png)

Memory usage after organizing maybe a few thousand files:
![Screenshot_2022-09-21_00-43-32](https://user-images.githubusercontent.com/47370906/191445240-4d330e38-921b-4b4e-b540-de7adbf964f6.png)

**System Information:**
 - Operating system: Ubuntu 22.04.1 LTS
 - Strawberry Version: 1.0.9

**Additional context**

**Comment by jonaski** [comment]
I'm not seeing any leaks. Is this strawberry from our releases, PPA or ubuntu package? What Qt version?
Can you run strawberry under heaptrack: `heaptrack strawberry`
Or compile strawberry with leak sanitizer:

```
CFLAGS="-g -ggdb -fsanitize=address" CXXFLAGS="-g -ggdb -fsanitize=address" cmake ../strawberry \
    -G 'Unix Makefiles' \
    -DCMAKE_PREFIX_PATH="/usr/local/qt6/lib64/cmake" \
    -DCMAKE_BUILD_TYPE="Debug" \
    -DBUILD_WITH_QT6=ON \
    -DENABLE_X11_GLOBALSHORTCUTS=ON \
    -DUSE_RPATH=ON \
    -DUSE_TAGLIB=ON

cmake --build . --parallel 8
```

**Comment by kurtisvetter** [comment]
I'm using the strawberry Ubuntu package. `apt show` says the version is 1.0.9-jammy. Strawberry says it's using Qt version 6.2.4. 

I ran `heaptrack strawberry`, noting that after startup the program used about 260MB of memory. Then I used organize files on 10 albums, noting that afterwards the program used about 470MB of memory, but I would expect it to go back down to 260MB

[heaptrack stdout.txt](https://github.com/strawberrymusicplayer/strawberry/files/9806795/heaptrack.stdout.txt)
[heaptrack.strawberry.60925.zip](https://github.com/strawberrymusicplayer/strawberry/files/9806820/heaptrack.strawberry.60925.zip)  (the analysis is probably more useful than this)
[heaptrack_analysis.txt](https://github.com/strawberrymusicplayer/strawberry/files/9806837/heaptrack_analysis.txt)

I tried compiling with those flags. At startup strawberry uses ~700MB (I assume from more debugging symbols etc.). After organizing maybe 1000 songs or so that climbs up to ~2GB and doesn't go down after the organization finishes. After exiting the program, it prints the following message to the console 
```
==73023==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 136 byte(s) in 1 object(s) allocated from:
    #0 0x7f6a603981c7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x7f6a602239e9  (/lib/x86_64-linux-gnu/libQt6DBus.so.6+0x759e9)

Indirect leak of 45 byte(s) in 1 object(s) allocated from:
    #0 0x7f6a60396867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x7f6a5edb90b3 in QArrayData::allocate(QArrayData**, long long, long long, long long, QArrayData::AllocationOption) (/lib/x86_64-linux-gnu/libQt6Core.so.6+0x25e0b3)
    #2 0x8c21c91e4e26cff  (<unknown module>)
    #3 0x6030002d6c7f  (<unknown module>)

SUMMARY: AddressSanitizer: 181 byte(s) leaked in 2 allocation(s).
```
which doesn't seem related. It's possible that it is not a memory leak per se? Perhaps the memory is properly freed before closing the program but not after the organize files dialog finishes. 

This might be important and maybe I was unclear in the original post, but in these tests I was running organize files on files in my library that are already organized, i.e. they are not moved or renamed as a result. (Yeah, this is probably weird to do, but someone might do this if they have added several albums to their library but don't remember which ones are organized or not, so they just organize their entire library).

**Comment by ginsterbusch** [comment]
Oh, I happen to run into similar issues. After just a day of intense usage (eg when sorting in a few of my albums and creating a set list), Strawberry tends to hog up to 4 GB of RAM. Currently its sitting at 3365M. Its also the only program that abuses the swap space on a regular.

My workaround so far has been to disable swap, then close Strawberry entirely and reopen it (and then reenable swap OC). Stays nice for a while until one adds more albums, then the situation slowly starts to go haywire all over again.

OS: (K)Ubuntu 20.04.4 LTS
Version: 1.0.9-focal (via repository)

cu, w0lf.

**Comment by jonaski** [comment]
@ginsterbusch Can you run strawberry under heaptrack for a day and share the resulting zst file.

**Comment by ginsterbusch** [comment]
@jonaski: testing. After about 10 hours (and 8 1/2 hours of active use), its already at 2585M. Even beat Pale Moon, and that is running for weeks!
Gonna add the results of heaptrack when I'm done with the 24h test.

cu, w0lf.

cu, w0lf.

**Comment by jonaski** [comment]
If there is a leak, I'm pretty confident it's not in Strawberry directly, but probably a library. Some memory remaining higher than normal can be fragmentation, but it's hard to explain several gigabytes, and 30 GB memory use is crazy. When organizing, Strawberry does not use heap memory like that, so the allocated heap memory is done internally in Qt (QImages, etc). The highest memory usage is most of the time the QImages for album covers.
I did a few runs with leak sanitizer and heaptrack while organizing, but I don't see any leaks or abnormal memory use. But I only tested the latest Qt code (what will be Qt 6.5.0). I can do some more testing with Qt 6.2 when I get some more time.
Even if the bug is not in Strawberry, we should figure out the root cause and report the bug where appropriate, so let's just leave this issue open in any case.

**Comment by ginsterbusch** [comment]
I definitely think its kind of a caching / garbage collection issue with QImages. My heaptrack numbers were insane for it as well.

Current workaround is to disable usage of external lookup of cover images, and use "local" covers. 

Settings > Collection > Saving album covers > Save album covers in album directory

That reduces the RAM usage drastically, to about 270 - 300 MB (result after about 1 week).

cu, w0lf.

**Comment by jonaski** [comment]
There is definitely a huge difference in memory usage between Qt 5 and Qt 6. I got mostly 1500x1500 album covers and higher from albumartexchange.com. What I'm seeing is, if I group by album, the memory consumption with Qt 6 will quickly grow to 3,5 GB, but with Qt 5 it's more sane, 700 MB.
I think this has to do with signal/slots, I'm going to try to allocate the memory for the images on the heap instead and see if it solves anything.

**Comment by jonaski** [comment]
It looks better now, reduced the memory usage considerably by using shared pointers through signal slots. But using const references for the QImages in signals seem to do much the same too.
There is still some memory growth related to album cover loading. I made a test application and the same thing happens, so I suspect it's memory fragmentation, no leaks is reported for it in leak sanitizer or heaptrack, but I might open a Qt bug report about it to see what Qt have to say.
