### ISSUE TITLE
Icon is flashed between song changes in the KDE media player applet

### ISSUE THREAD

**Issue by peterhoeg** [strawberrymusicplayer/strawberry#1079]
- [X] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [X] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [X] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
When running under KDE and changing the currently playing song, the KDE tray icon media applet will flash the strawberry icon between the album artwork.

**To Reproduce**
There are 2 ways to reproduce the problem:

1. start playing a song on an album
2. open the media player tray icon
3. click the next button in the media tray popup
4. the strawberry icon is flashed before the song starts playing

And:
1. start playing a song on an album
2. open the media player tray icon
3. pin the media player tray popup
4. click the next button in strawberry
5. the strawberry icon is flashed before the song starts playing

Other media players (Elisa and Audacious) do not have this problem.
   
**Expected behavior**
No flashing of the strawberry icon.

**Screenshots:**
It's extremely brief, so the only way to show this is via a video, but it's very easy to reproduce.

**System Information:**
 - Operating system: NixOS 22.11
 - Strawberry Version: 10.0.10

**Additional context**
I reported it to KDE first as I thought this was related to a similar problem fixed in Plasma 5.26.4 and they had the following feedback: "Likely a bug in the media player because the media player doesn't update the album art in time when song changes,"

https://bugs.kde.org/show_bug.cgi?id=461496

**Comment by peterhoeg** [comment]
I have tried with both the qt5 and qt6 versions of strawberry - same result.

**Comment by jonaski** [comment]
Strawberry sends the Metadata notification twice, first once switching the song, then again when the album cover is loaded and picked. It has always done it like this. This is because it supports multiple types of album cover loading, like embedded covers and remote covers which takes a bit longer to load. Strawberry has a much more advanced cover handling than probably most other players. Can possible remove the first notification, but that means that the notification will be a bit more delayed, probably under a second for local covers, but a bit longer for remote covers.

**Comment by easyteacher** [comment]
The first notification can send an empty but valid album art to fix the bug

**Comment by jonaski** [comment]
What do you mean by empty album art?

**Comment by jonaski** [comment]
I tested this on KDE now. Strawberry is not sending `mpris:artUrl` at all before it's available, for some reason the media player applet is showing the strawberry logo instead of a "empty" album cover in that case.
For Strawberry to be creating a blank fake album art for `mpris:artUrl` seems like a workaround for something that is done by the media player applet.
Strawberry has had the same behavior for 5 years, I don't understand why this is a problem now.

**Comment by peterhoeg** [comment]
> Strawberry has had the same behavior for 5 years, I don’t understand why this is a problem now.

I’m guessing because we are in “tiny cosmetic issue”-land.

I can fully understand if you say “in the grand scheme of things, this isn’t important - just live with it, WONTFIX”.

That being said, it is an issue (albeit small) that manifests itself when using strawberry and not any of the other mentioned media players.

I just tried VLC and that *sometimes* behaves like strawberry, so I’m guessing it’s a timing issue in that case.
