### ISSUE TITLE
Strawberry not following system theme (dark mode broken)

### ISSUE THREAD

**Issue by moonraker2** [strawberrymusicplayer/strawberry#1081]
**Describe the bug**
Strawberry doesn't follow Ubuntu system theme (dark/night mode).

**To Reproduce**
Install Strawberry on Ubuntu 22 LTS

**Expected behavior**
For Strawberry to follow system theme and be shown in dark mode when Ubuntu is otherwise configured with dark theme.

**System Information:**
 - Operating system: Ubuntu 22 LTS
 - Strawberry Version: latest

**Comment by jonaski** [comment]
I suggest to get help from the Ubuntu community with this issue.
This is most definitely a configuration issue or specific to Ubuntu, Strawberry works fine here with both Qt 5 and 6 on openSUSE and KDE with the dark theme.

**Comment by guidomz** [comment]
I use Debian bookworm and I have the same issue of Strawberry not following the dark system theme. Thus, it might not only be an Ubuntu problem.

**Comment by vanukalla** [comment]
I observed the same first when upgrading to Xubuntu 22.4. LTS and recently upon switching to 24.4 LTS. I tried to set the configuration using both lxappearance and qt5 which worked for most applications but not for Strawberry (or for Nautilus). 
What actually worked for me was forcing gsettings to use dark mode:
gsettings set org.gnome.desktop.interface color-scheme prefer-dark
This is with the flatpak version since the available deb packages show unresolved dependencies for me. 
And Nautilus is in dark mode now, too.

**Comment by guidomz** [comment]
> org.gnome.desktop.interface color-scheme prefer-dark

Thanks, but it didn't work for me. (Using mate on debian bookworm.)

**Comment by lelutin** [comment]
I'm also seeing this problem on debian unstable, strawberry 1.1.1 with gnome 46 and qt5 5.15.13

gnome is set to dark theme (same gsetting as mentioned by @vanukalla 

I also tried setting qt system theme with qt5ct and it changed nothing. strawberry is the only app that persists in blasting me with a white background

@jonaski could there be a way for strawberry to detect gnome's dark theme?

**Comment by guidomz** [comment]
@lelutin, this is what worked for me (not sure about your OS setup but I hope it helps):
```
sudo apt install qt6-base-dev qt6ct
```
• **qt6ct** → Appearance → Palette = Custom → Color scheme = Darker → Apply
• **strawberry** → Tools → Settings → Appearance → Style = Fusion

**Comment by lelutin** [comment]
@guidomz thanks

however that does not appear to work in my case. the strawberry is still all white and bright colors :\

**Comment by vdualb** [comment]
Same issue on Fedora 42 and Strawberry 1.2.11 from flatpak. I don't think it's a system configuration problem, because other apps utilizing different GUI toolkits are able to follow system dark mode preference, like Zed editor with their own home-brewed toolkit, Telegram app, electron, flutter and avalonia apps.

**Comment by apolinux** [comment]
I had the same problem and I solved running with a suggest by qt6ct app:
`QT_QPA_PLATFORMTHEME=qt6ct strawberry`
