### ISSUE TITLE
A column is not visible immediately after activating it

### ISSUE THREAD

**Issue by glaubersm** [strawberrymusicplayer/strawberry#1085]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Frequently a column is completely or almost completely hidden after activating it. I need to drag the separator after the prior column to make the newly activated column visible.

**To Reproduce**
1. right-click on any column of the playlist and uncheck 'Stretch columns to fit the window'
2. right-click on any column of the playlist and activate any column

**Expected behavior**
the column activated in the last step is visible

**System Information:**
 - Operating system: Arch Linux
 - Strawberry Version: 1.0.10

**Additional context**
Strawberry built against Qt6

**Comment by jonaski** [comment]
I can reproduce the bug with Qt 6, not Qt 5.

**Comment by jonaski** [comment]
Resetting the columns to default after switching from Qt 5 to Qt 6 fixes it for me, all columns are visible after activating them. Do you still have this issue and did you try to reset the columns to default?

**Comment by glaubersm** [comment]
I can reproduce even after resetting the columns if "Stretch columns to fit window" if unchecked.

**Comment by guprobr** [comment]
strange, here compiled against Qt6, latest Ubuntu 24.04 -- I'm trying to reproduce but can't, perphaps not actually a Strawberry bug?

**Comment by jonaski** [comment]
I can reproduce it now, both with Qt 5 and 6 if stretch mode is off. It would not surprise me if this bug is in strawberry, but I have only seen this issue in the later years, so it might be a change in Qt that triggered the incorrect behaviour.
StretchHeaderView isn't doing anything fancy when stretch mode is off, but I think it might be that the column size isn't set when you add a new column, since in stretch mode it automatically resizes the columns when you add / remove any.
But I'm not happy with the stretch mode either, I think it's flaky, it would probably be better if it only resizes the right column when you resize the column to the left of it, instead of the whole thing.

**Comment by jonaski** [comment]
When a column is enabled, `StretchHeaderView::ShowSection` is called, but the sectionsize is zero, I don't remember where the section size is supposed to be set.

**Comment by guprobr** [comment]
haha I was just looking at this right now

src/dialogs/trackselectiondialog.ui:192:          <attribute name="headerMinimumSectionSize">
src/dialogs/trackselectiondialog.ui:195:          <attribute name="headerDefaultSectionSize">
src/widgets/stretchheaderview.cpp:47:  setMinimumSectionSize(kMinimumColumnWidth);
src/widgets/stretchheaderview.cpp:49:  setDefaultSectionSize(100);

**Comment by jonaski** [comment]
So setMinimumSectionSize is set, so then the column should be visible when enabled, Qt bug perhaps?

**Comment by guprobr** [comment]
is tehre some sort of need to "refresh" after making a column visible?

**Comment by jonaski** [comment]
Maybe related to #1328. I had to add `setDefaultSectionSize(100);` for it to remember the column sizes.

**Comment by guprobr** [comment]
in time, Qt here is Qt version 6.4.2

maybe thats why I cannot reproduce

**Comment by jonaski** [comment]
Yes, maybe. I'm building the Qt dev branch, so I'm on "6.8".

The initial section sizes are only set when in stretch mode here:
https://github.com/strawberrymusicplayer/strawberry/blob/master/src/playlist/playlistview.cpp#L365

If the stretch mode is off, the section size gets set here:
https://github.com/strawberrymusicplayer/strawberry/blob/master/src/widgets/stretchheaderview.cpp#L293

**Comment by jonaski** [comment]
This must be a change in Qt, if not a bug, at least a change in behavior. If the change is intentional, then we need to remember column sizes when turning on/off columns if stretch mode is off too, maybe a good idea anyway.

**Comment by guprobr** [comment]
after trying a lot, i was able to reproduce.
But i had to insert several columns, i noticed that when you turn stretch on again, the columns inserted which are invisible, become disabled again, as if we never inserted to become visible. this could be a tip too. 
I believe they are never getting inserted, perphaps because of new Qt behaviour concerning sizes? Or some sort of refresh to do after manipulating columns? I wasnt able to reproduce because I did not trigger enough columns, after more than 10 (or something) I could reproduce exactly the way its reported
