### ISSUE TITLE
Cannot restore files sent to Trash with Strawberry due to wrong original path with duplicated mount point and a symbol instead of accented character

### ISSUE THREAD

**Issue by glaubersm** [strawberrymusicplayer/strawberry#1086]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
The folder '/mnt/SEAGATE/Minhas músicas' is indexed by Strawberry on my system. 'mnt/SEAGATE' is the mount point of a ntfs partition and 'Minhas músicas' is the folder where my audio files are stored. Strawberry sends a file to Trash but I can't restore it and an error message appears due wrong original path with duplicated mount point and a symbol instead of the accented character 'ú', as we can observe in the screen below.

**To Reproduce**
1. make sure 'Enable delete files in the right-click context menu' option is checked in the 'Playlist' section of Strawberry settings
2. right-click on any song in your playlist and choose 'Delete from disk...'
3.  confirm the deletion
4. open Trash with your file manager and try to restore the deleted file

**Expected behavior**
the file can be restored with the file manager

**Screenshots:**
The first file seen in the screenshot below was deleted from disk with Strawberry. Observe the column 'Path' showing wrong original path with duplicated mount point 'mnt/SEAGATE' and a symbol instead of the accented character 'ú'. The 'test file.txt' file was located in the folder indexed by Strawberry and it was deleted with Dolphin file manager. Its path is correct and I can restore it.

![deleted by strawberry](https://user-images.githubusercontent.com/15967631/208222034-e4cbd980-6f26-4672-807c-31e369612b9f.png)

When I try to restore the file deleted with Strawberry, the following error message appears:

![cannot restore](https://user-images.githubusercontent.com/15967631/208222149-73089d01-304a-4733-96f3-f0fa5dbbecab.png)

**System Information:**
 - Operating system: Arch Linux
 - Strawberry Version: 1.0.10

**Additional context**

**Comment by jonaski** [comment]
The paths being wrong is a KDE bug, while the character encoding issue is a Qt bug.
If you look at the `trashinfo` files in the `.Trash-1000/info` directory, you can see that those created by Qt are with absolute paths, but Dolphin incorrectly handles absolute paths for `.trashinfo`. Dolphin itself does not use Qt for moving files to trash, and uses relative paths, which is why it works for files deleted by Dolphin.
According to the specifications (https://specifications.freedesktop.org/trash-spec/trashspec-1.0.html), it should be possible to use both.
You can also see by looking at the `trashinfo` files that the ones deleted using Qt is not URL encoded like they should.
I have submitted a fix to Qt for the encoding issue, and also proposed to change the paths to relative paths when possible: https://codereview.qt-project.org/c/qt/qtbase/+/450647

**Comment by glaubersm** [comment]
Thank you very much, Jonas. I see that your patch was already merged to Qt.
Should I report a bug to KDE folks? Or will your patch 'fix' the KDE bug?

**Comment by jonaski** [comment]
You can report the bug to KDE if you want, it does not handle absolute paths in .trashinfo correctly, looks like it assumes absolute paths.

**Comment by nicolasfella** [comment]
The crucial detail here is that it's a mounted disk with its own trash.

https://invent.kde.org/frameworks/kio/-/merge_requests/1106 fixes the issue
