### ISSUE TITLE
macOS Strawberry 1.0.11 Won't Open

### ISSUE THREAD

**Issue by big610** [strawberrymusicplayer/strawberry#1088]
macOS Intel Strawberry 1.0.11 Won't Open
Fails to open. Left click from Launchpad, attempts to open for a half second, then closes from Launchpad, never opening.
Back to 1.0.10. 

Unable to open, so unable to get a report.
See 1.0.8 #1025 for ideas.
https://github.com/strawberrymusicplayer/strawberry/issues/1025

Feature Request:
Windows Portable.
Then I can isolate test on Windows.
Any chance to be added to do list?

**Comment by jonaski** [comment]
What macOS release? The latest supported is Big Sur, anything older won't work.

**Comment by big610** [comment]
Tested on Catalina. Will check Monterey. Thank you.
Please list on Main Page's Web Site & GitHub, macOS Compatibility Version's System Requirements.
Any chance for future Windows Portable.

**Comment by jonaski** [comment]
What do you mean by "Windows Portable"

**Comment by big610** [comment]
Portable is a non install, does not get installed to Program Files. Instead installs as a Portable self contained in the Download un-zipped folder.
Here's the links to Clementine Portable to make it easier for you to test understand.
https://builds.clementine-player.org/win32/portable/

**Comment by jonaski** [comment]
The website was updated earlier today, now says: "macOS 11 (Big Sur) or higher". Unfortunately not possible to support older macOS versions since Qt and homebrew, etc stopped supporting them.

I won't make a portable setup or zip file, anyone can do that, it's free and open source. Also, you can simply extract the files from the setup using 7-Zip or similar without installing Strawberry using the setup. The database other files will still be in AppData, not in the current directory. But making a separate setup or zip just for that is a lot of unnecessary work that I don't want.

**Comment by big610** [comment]
Thanks for attention. I was hoping you could put out, do just one Developer done, Portable Version, to have. Then you don't have extra work for each release, have to do another Portable version, keep just one old one.
