### ISSUE TITLE
Add Discord Rich Presence support?

### ISSUE THREAD

**Issue by Akitakek** [strawberrymusicplayer/strawberry#109]
I would like to see discord-rpc support in strawberry.

**Comment by jonaski** [comment]
Could you explain it a bit, I'm not familiar with it

**Comment by AkitakeKun** [comment]
In Discord, you can show your activity (whether you're playing a game, listening to music) and some info about it (how far into the game, what music specifically).
It works by detecting which processes are running and checking if they support Rich Presence (RPC).

For instance, Spotify: 
![Spotify](https://user-images.githubusercontent.com/7873528/55827893-8ecbce80-5b0b-11e9-8fd2-80009a8292df.png)
Google Play Music:
![Google Play Music](https://user-images.githubusercontent.com/7873528/55828068-e0745900-5b0b-11e9-879b-6a58c6c425c4.png)

Various links:
https://github.com/discordapp/discord-rpc
https://discordapp.com/developers/

**Comment by roberestarkk** [comment]
I actually came here to find out whether my Discord<->Clementine Bridge would be supported by Strawberry as well (uses the Clementine Remote API).

[https://bitbucket.org/roberestarkk/discordclementineremotedotnet/src/master/](https://bitbucket.org/roberestarkk/discordclementineremotedotnet/src/master/)
Admittedly mine's pretty barebones:
![image](https://user-images.githubusercontent.com/4946179/57668622-41cba280-764b-11e9-86db-ef98e0db6004.png)
and I called it 'Music' so that it'd say 'Playing Music' next to my name.
But it does work ^^

**Comment by BobbyWibowo** [comment]
Another alternative that I've been using for quite a long while by now is: https://github.com/FichteFoll/discordrp-mpris.
It fetches data from the MPRIS2 dbus interface, which I suppose is pretty much a standard requirement for any media players, that can run on Linux, to support (so yeah, Clementine, and by extension Strawberry, already support that).
It's neat in that it's an AIO solution (mpv, VLC, and heck even web browsers too through [KDE's Plasma Browser Integration](https://community.kde.org/Plasma/Browser_Integration)).
But yeah, the "game" name will be fixed to whatever you name the Discord app to (that project names it as "Media (mpris2)").

**Comment by jonaski** [comment]
I'm closing this since I don't have time to prioritize it. Someone else is free to make a proposal for this feature in a PR.
