### ISSUE TITLE
Support chaning playerlist's font-family and font size in Windows and MacOS

### ISSUE THREAD

**Issue by kostabekre** [strawberrymusicplayer/strawberry#1097]
> @jonaski I need to increase the font size (specially at the playlist) in MacOS. Is this supported / planned at all?

Same for Windows. I can change text font and size for "Context" window but playlist's text is small and Japanese symbols are not pretty. Plus when DPI is increased, the current song is blurry.
![изображение](https://user-images.githubusercontent.com/50672363/211153966-4dfecff2-672b-42e2-80a6-81d4dc311bc4.png)

_Originally posted by @kostabekre in https://github.com/strawberrymusicplayer/strawberry/issues/303#issuecomment-1374487779_

**Comment by jonaski** [comment]
I'm aware of the comments in the issue. Strawberry follows the font settings from the OS, it does not set it's own font for the playlist or anything else with the exception the context, this is something that was added because users sometimes want this larger or different fonts for the lyrics than the rest of player. I do not have time or resources to add extra settings for fonts at this time, my TODO list is already full.
For changing font and size on Windows see: https://support.microsoft.com/en-us/windows/make-text-and-apps-bigger-c3095a80-6edd-4779-9282-623c4d721d64
I can't give much support for macOS, since I don't have mac. This is written on the website and the README on GitHub. I can only do the basic support, things like make sure it starts, runs and plays music. For adding extra settings or features explicitly for macOS needs to come as contributions from the community.

**Comment by csarven** [comment]
For anyone coming across this issue with the hopes to increase the font size in Strawberry, it is possible to do it through the Qt5 or Qt6 Configuration Tool (GUI) - although not specific to Strawberry. On Debian/Linux, `apt install qt6ct`.
