### ISSUE TITLE
'Date Created' information different in Playlist column vs 'Edit track information' dialog.

### ISSUE THREAD

**Issue by MyXelf** [strawberrymusicplayer/strawberry#1111]
Hi:

**Describe the Bug**
The reported **'Date Created'** information is different in the **'Edit track information'** dialog vs the **'Date Created'** column in the playlist (see screenshot below).

At least in Linux (ext4 FS), the reported date in the 'Edit track information' is always referring the 'Birth' date of the file. While the column correctly reports the date in the _ctime_ value stored in the database. In other OS (i.e. Windows) the result could be different cause there is no 'Birth' date at the FS level.

**To Reproduce**
- Add the 'Date created' column to a playlist and check the reported dates in the column vs the dialog.

**Expected behavior**
- The date reported in both places should be the same.

**Screenshots:**
![strawberry---different-'date-created'-reported---20230115-125045](https://user-images.githubusercontent.com/4689660/212558325-bab1cad6-0299-4fa6-9f20-fc6a28ffb9f6.png)

**System Information:**
 - Operating system: KDE Neon 22.04
 - Strawberry Version: 1.0.14-jammy

HTH!

**Comment by jonaski** [comment]
They will not always be the same, since the playlist column is using existing data from the database, while the edtior re-reads the files.
If ctime for the file is changed (ie.: the file is copied on disk), but the mtime is unchanged, that does not trigger a rescan, so the ctime is not updated, and the data in the DB will be the same. The editor re-reads the files so you'll always see the newest there.
