### ISSUE TITLE
Sidebar/Tabs/Settings no longer use system icons since 1.0.10

### ISSUE THREAD

**Issue by Cknight70** [strawberrymusicplayer/strawberry#1113]
- [ yes] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [ yes] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [ yes] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
The icons on the tab bar, and also settings do not use system icons when requested, although context menus, playback buttons still use system icons.
**To Reproduce**
I did a full system update on Arch Linux including strawberry-qt5 AUR and noticed this change. I built Strawberry with the option ``-DBUILD_WITH_QT5=ON`` 1.0.14, 13, 12, and 11 to ensure my system update was not the cause.
**Expected behavior**
Strawberry should use my native icons for the tab bar and settings icons when the "Use system theme icons" box is ticked
**Screenshots:**
1.0.10
![image](https://user-images.githubusercontent.com/28763729/212566604-6c98b420-5ef4-42eb-8952-c9e375e00e7b.png)
![image](https://user-images.githubusercontent.com/28763729/212566807-b991aff3-10b8-4c84-98b0-3534567a37c9.png)

1.0.11-1.0.14
![image](https://user-images.githubusercontent.com/28763729/212566701-eff9f6ac-be69-484b-bfeb-fac79bb043f2.png)
![image](https://user-images.githubusercontent.com/28763729/212566821-4e0b38ba-ef1a-4e22-8e9e-baf85e845c53.png)

**System Information:**
 - Operating system: Arch Linux ```linux 6.1.5.arch2-1``` and ```plasma-desktop 5.26.5-1```
 - Strawberry Version: 1.0.11-1.0.14

**Comment by jonaski** [comment]
It does if the icons are large enough >= 32x32.

**Comment by Cknight70** [comment]
The Breeze icons are SVGs and scale 32x32 though

![image](https://user-images.githubusercontent.com/28763729/212568605-1b8c76d8-c98d-4021-b3eb-c15ac80b6d94.png)

**Comment by jonaski** [comment]
It needs to be pngs

**Comment by Cknight70** [comment]
The breeze icons scaled well in 1.0.10, what work needs to be done to support them again?

**Comment by Idesmi** [comment]
I have the same issue

**Comment by jonaski** [comment]
Here is why I added the icons size to be at least 32x32 for the tabbar and the settings:
![image](https://user-images.githubusercontent.com/10343810/214151194-8b3f6bfa-30c0-4bcf-8d8e-73a399716840.png)

![image](https://user-images.githubusercontent.com/10343810/214151126-011950e2-2343-47be-a882-a4e37a4f2ef5.png)

I don't know why some of the Breeze icons only have 22x22 pngs. But the svgs are available so they could easily be produced in 32x32, 48x48 and 64x64 and that will make Strawberry pick them up.

I also think it's pretty inconsistent that some icons were black/white while others has colors. The problem is that there are no standardized icon names.
