### ISSUE TITLE
Lyrics fetching is too finicky, ignores valid matches

### ISSUE THREAD

**Issue by v-fox** [strawberrymusicplayer/strawberry#1147]
- [ X ] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [ X ] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [ X ] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
My music library is mostly various OSTs with only some entries having lyrics. But even for popular tracks lyrics are rarely fetched, even though they might have been previously present in clementine/amarok. It seems that major reason for that is strawberry not fetching a valid entry, likely due to some minor mismatch.

For example, I have a track with Artist/Album-Artist/Album/Title "Casey Edwards / Capcom / Devil May Cry 5 Special Edition VERGIL Sound Selection / Bury the Light" which does not get any lyrics. Yet there is [perfectly fine entry](https://genius.com/Casey-edwards-bury-the-light-lyrics) and genius.com is enabled, configured and set on top. I suspect that it tries to match all tags perfectly.

**To Reproduce**
Try getting lyrics, especially for not mainstream pop-music.

**Expected behavior**
Try to get everything that seems relevant.

**Screenshots:**
It's obvious.

**System Information:**
 - Operating system: openSUSE Tumbleweed
 - Strawberry Version: 1.0.15

**Additional context**
If overly strict matching is the case then I suggest doing something like this in steps (with some caching):
1) Try perfect matching.
2) Try ignoring album name with both Artist & Album-Artist.
3) Same as 2 but allow Title with additional characters at the end (like when tracks in "Metal Gear Rising: Revengeance" album have " (Platinum Mix)" suffix in Titles).
4) Same as 3 but ignore Artist entries and match Album instead while ignoring additional characters at the end (something like aforementioned MGR album may have performer names as Artist instead of releasing company's name that may be expected on lyrics sites).
5) Try only Title and grab the first thing that comes up.

Wouldn't help with language mismatch (like translated, transliterated or raw Japanese entries) but at least should help with English.

**Comment by jonaski** [comment]
Amarok and Clementine probably worked better with your specific songs years ago,
but most of those lyrics providers no longer exists. So the comparison is a bit strange.
For example, Amarok is still using Lyrics Fandom, even in the latest source code (https://invent.kde.org/multimedia/amarok/-/blob/7f966e2a46c92eeec2991feec30fb061c41c0b67/src/lyrics/LyricsManager.cpp#L34), which is defunct.
Most of the lyrics providers Clementine in the latest source code are either dead or broken and have not been fixed in years.
I went through the whole list a short while ago to see if it was possible to adapt any of them, and there were circa 3 or 4 that worked. The only one I found that was reasonable to adapt which I wasn't using already was STANDS4 (lyrics.com)

The Genius API Search is crap, seriously it's the worst of them all. You can't search by artist and song title, you have to search by a query, and apparently that matches a whole lot more than just lyrics.
If there isn't a match, you are guaranteed to get 9 results with unrelated lyrics anyway.
So I have to filter the results somehow. The results does not contain album, so I can only match by artist and song title. So I made it require either artist and song title to match. It does not require both to match.

AudD has worked great for years, there was no limit to the API, but the API key was disabled recently. I sent them a message, but they haven't responded. so I'll probably end up removing it.

Musixmatch is currently broken, receiving 401 (Unauthorized), API key is probably revoked. The API is very restrictive, allowing only a certain number of requests per day (unless you pay), it's supposed to fallback to using a URL instead in that case, but that wasn't working for the 401 error. I'll fix so it falls back to using the URL in the form (https://www.musixmatch.com/lyrics/artist/title), but that requires the artist and song title to exactly match.

STANDS4 (www.lyrics.com) works, but usually the API usage limit is reached, so instead of searching it falls back to using a fixed URL similar to Musixmatch, so obviously that requires a exact match.

The remaining 3 (Chartlyrics, OVH and Lolo) aren't very good.

**Comment by v-fox** [comment]
> So I have to filter the results somehow. The results does not contain album, so I can only match by artist and song title. So I made it require either artist and song title to match. It does not require both to match.

And yet it ignored the perfect Title match from my "Bury the Light" example.
Same happens with partial match for "Red Sun (Maniac Agenda Mix)" even though manually searching "Red Sun" puts correct song as first result.
Naturally, the program should keep fetched lyrics in its database and have purge function to avoid excessive requests.

It one thing to put something on back-burner due to difficulty but it's disingenuous to outright deny that this is an issue just because APIs are imperfect. Especially for failures in internal matching where you have all the control.

**Comment by jonaski** [comment]
It probably wasn't working because the lyrics search was using album artist instead of artist. I see I changed the search from artist to album artist in 2019, but I don't remember exactly why, but I think it was because if an album by an artist has guest artists, the songs are usually written by the album artist not the guest artists, like the Bob Dylan The 30th Anniversary Concert Celebration.
I changed that yesterday back to artist, if you can build by source it should probably work now.

**Comment by s38b35M5** [comment]
Why is this closed? Is there another open issue I'm not seeing?
Lyrics search is still missing easy matches on almost half my music, even mainstream.

**Comment by jonaski** [comment]
@s38b35M5 What lyrics providers do you have enabled in the settings? Do you have examples that do not give match? Artistand  song titles?

**Comment by s38b35M5** [comment]
> @s38b35M5 What lyrics providers do you have enabled in the settings? Do you have examples that do not give match? What artist and song titles?

I enable all but Genius, but I used an app a few months ago that added lyrics for my collection to the lyrics tag, so I don't have an easy time finding any to test. I think part of the difficulty relates to songs that include  "Feat." in the artist tag, or anything other than the mainstream top-billed artist. I'll see if I can trip it up like it was when I first migrated my library from Google Play Music / YT Music Takeout, and post my results.
