### ISSUE TITLE
Editing track information of Ogg Opus files "scrambles" the track

### ISSUE THREAD

**Issue by Velkee** [strawberrymusicplayer/strawberry#1158]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Manually editing the metadata of Ogg Opus files causes it to "scratch", moving parts of the song to places it doesn't belong seemingly randomly and leaving behind a loud scratching sound. The tracks this has happened to sound normal when I've played them before editing the metadata.

**To Reproduce**
1. Right click a track stored in the Ogg Opus format and select  "Edit track information..."
2. Set an artist name, title, and cover
3. Attempt to play track

**Expected behavior**
The track should play as normal, as it did before editing the metadata.

**System Information:**
 - Operating system: Arch Linux, linux-zen kernel version 6.2.2
 - Strawberry Version: 1.0.15

**Additional context**
I'm unsure if the issue happens with other file formats, but the issue has affected both my home PC and my laptop.

**Comment by jonaski** [comment]
I can reproduce this with both Vorbis and Opus when saving both artist, title and embedded cover at the same time. So far can't reproduce it with FLAC.
I don't know if this bug is Strawberry's code or in TagLib, but it's not good.
One thing we do is that we save tags and embedded cover separately, so the processes runs concurrency which is bad idea in the first place, but I thought filesystems had protection against two processes writing to the same file. But I'll start with dealing with that and see if it fixed it.

**Comment by jonaski** [comment]
I've now implemented a method for saving tags and cover in the same function, I can no longer reproduce any corruption with Ogg Vorbis and Opus.
The changes are quite large so it requires some more testing before a new release, but hopefully I should be able to put out a new release in a few days.
This is definitely the most severe bug we've ever had.

**Comment by jonaski** [comment]
New release 1.0.16 available now.
