### ISSUE TITLE
Album art is missing in notifications when you set "Show a native desktop notification" as "Notitication type"

### ISSUE THREAD

**Issue by glaubersm** [strawberrymusicplayer/strawberry#119]
I use strawberry-full-git on Arch Linux running KDE Plasma 5.15.4, installed from AUR.

Open strawberry settings, click "Notifications" section in the left side.
Set "Show a native desktop notification" as "Notitication type", make sure that
"Include album art in the notification" option is checked, click "Ok" button.
Play some track.
Result: album art is missing in notification when you pause the track and change the repeat/shuftle mode. The notification shows strawberry icon instead of the album art.

**Comment by jonaski** [comment]
I'm working on some improvements to the OSD notifications.

**Comment by jonaski** [comment]
Closing this due to lack of time. No notifications are currently showing cover when stopping.

**Comment by jonaski** [comment]
I made pausing and stopping show artist / title (summary text) and album covers now. I think it looks better now.
I also fixed so that "Stopped" isn't showing twice when there is an error starting playback.
But I think it's better to leave the Strawberry icon for the notifications when changing settings.

**Comment by glaubersm** [comment]
Thank you Jonas. :)
