### ISSUE TITLE
Invalid manifest URI

### ISSUE THREAD

**Issue by mkamensky** [strawberrymusicplayer/strawberry#1211]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Strawberry no longer plays songs from Tidal. When trying to play, a message similar to the following appears in a pop-up window:

```
Invalid manifest URI

../gstreamer/subprojects/gst-plugins-good/ext/adaptivedemux2/gstadaptivedemux.c(959):
handle_incoming_manifest (): /GstPlayBin3:pipeline-2-pipeline/
GstURIDecodeBin3:uridecodebin3/GstURISourceBin:urisourcebin1/
GstDashDemux2:dashdemux2-3: Manifest URI needs to use either http:// or https://
```

Local songs play as usual

**To Reproduce**
Try playing any tidal song.

**Expected behavior**
The song plays

**System Information:**
 - Operating system: arch linux x86_64
 - Strawberry Version: 1.0.17
 - Gstreamer Version: 1.22.3

**Comment by jonaski** [comment]
Still works here using OAuth and "streamurl" for Stream URL method.

**Comment by mkamensky** [comment]
> Still works here using OAuth and "streamurl" for Stream URL method.

Ok, a bit strange. It turns out that not all tracks stopped playing, only some of them. My original stream url method was `playbackinfopostpaywall`. Changing it to either of the other two the same tracks remain unplayable, but with an error of  `Asset is not ready for playback (401)(4005)` (I have no idea what this option does, couldn't find its docs anywhere)

**Comment by mkamensky** [comment]
I tried to copy a url for one of the tracks that don't play, it looks like `tidal:10843700`

**Comment by jonaski** [comment]
"tidal:10843700" is not the actual URL, it's a fake URL used by strawberry internally where 10843700 is the tidal track number.
When you play the song, the actual URL is requested from Tidal based on the track number, so the error you get here is when the stream URL is requested.
In my experience, "Asset is not ready for playback", is just a general error when the song is not available, I think this can be based on your subscription, region, the quality setting or the tidal client ID.
Sometimes albums / tracks are listed twice or more, then you can try the other listing and see if it works.
Since I don't have any documentation from tidal it's hard to know exactly.

**Comment by mkamensky** [comment]
Thanks. I had been using the same playlist for a while, and it started 
happening all of a sudden a few weeks ago. I gather there is no way to 
figure out what is going on?

In any case, as far as Strawberry is concerned, perhaps it would help to 
give a clearer error message here, it was very hard to understand what's 
going on.

Thanks!

* Jonas Kvinge ***@***.***> [06/06/23 21:55]:

**Comment by jonaski** [comment]
Then it could be that you just need to search the album or track and re-add it to the playlist, Tidal can have removed the song, or created a new track ID for it.
Strawberry is not generating this error message, it comes from Tidal, and without official documentation from Tidal its not possible to know what the different API error codes are.

**Comment by rwolfson** [comment]
I hit this recently as well, after an Arch system update. I also use the `playbackinfopostpaywall` stream method as that's what seemed to work reliably for me historically. Changing to other streaming modes had some tracks work, but most break with the `Asset is not ready for playback` error seen above when using the other modes; I suspect this is why I've been using this particular stream method.

The Flatpak distribution of Strawberry works fine for me with my same historical settings, so I don't believe it's due to an upstream Tidal API change, but instead a local issue. It might be worth digging deeper as you may see more folks running into this as time goes on and Strawberry dependencies get updated in other distributions, although Flatpak works as a workaround for me for now. I can confirm I see the issue with a build from the current `master` branch, but I haven't been able to spend any time debugging further.

My non-Flatpak package versions are same as the initial report:
```
$ pacman -Q | grep -E "strawberry|gstreamer"
gstreamer 1.22.3-2
strawberry 1.0.17-2
```

**Comment by mkamensky** [comment]
> I hit this recently as well, after an Arch system update. I also use the `playbackinfopostpaywall` stream method as that's what seemed to work reliably for me historically. Changing to other streaming modes had some tracks work, but most break with the `Asset is not ready for playback` error seen above when using the other modes; I suspect this is why I've been using this particular stream method.
> 
> The Flatpak distribution of Strawberry works fine for me with my same historical settings, so I don't believe it's due to an upstream Tidal API change, but instead a local issue. It might be worth digging deeper as you may see more folks running into this as time goes on and Strawberry dependencies get updated in other distributions, although Flatpak works as a workaround for me for now. I can confirm I see the issue with a build from the current `master` branch, but I haven't been able to spend any time debugging further.
> 
> My non-Flatpak package versions are same as the initial report:
> 
> ```
> $ pacman -Q | grep -E "strawberry|gstreamer"
> gstreamer 1.22.3-2
> strawberry 1.0.17-2
> ```

Great, thanks for the help. I just verified that everything works fine with Strawberry 1.0.14-2, so indeed it is a change in Strawberry.

**Comment by jonaski** [comment]
> > The Flatpak distribution of Strawberry works fine for me with my same historical settings, so I don't believe it's due to an upstream Tidal API change, but instead a local issue. It might be worth digging deeper as you may see more folks running into this as time goes on and Strawberry dependencies get updated in other distributions, although Flatpak works as a workaround for me for now. I can confirm I see the issue with a build from the current `master` branch, but I haven't been able to spend any time debugging further.

Flatpak is storing the settings in a different location, did you actually use the same settings file with the same Tidal session ID?

**Comment by jonaski** [comment]
> Great, thanks for the help. I just verified that everything works fine with Strawberry 1.0.14-2, so indeed it is a change in Strawberry.

Believe what you want, but there are no relevant changes to the source code between those releases.

**Comment by rwolfson** [comment]
I had not tried 1.0.14 recently until seeing the comment above, but I can confirm this also does not have the issue for me locally (via local build and same system packages otherwise). I did a `git bisect` with local builds to locate the breaking commit, and commit d406a1c34131d6c9431034b41f77e0547b05eb07 looks like a probable cause; this was first included in release 1.0.15. This commit also has a keyword overlap with the reported error (`playbin3`) and references GStreamer 1.22.0. I also can confirm that rebuilding the `master` branch with that one change reverted fixes the issue.

Looking at my Pacman log,  I believe this broke around when a system update upgraded gstreamer (1.22.1->1.22.3), so I suspect the Strawberry behavior itself was fine until my gstreamer updated; my Strawberry was on 1.0.17 for months. This would lead me to believe that this combination (Strawberry 1.0.15+, gstreamer 1.22.3, and Tidal using `playbackinfopostpaywall` method) triggers the issue. I had a lot of other packages update at the same time, however, Gstreamer seems like the likely culprit given that git commit.

Let me know if there's additional data points that would help; I imagine some possibilities could either be a bug in GStreamer, or something that Strawberry/Tidal is sending to GStreamer doesn't play nicely with `playbin3` on the latest GStreamer version(s).  If nothing else, a possible workaround could be presenting a Strawberry user option to use `playbin` instead of `playbin3`.

Regarding your Flatpak question, confirming that the issue follows the build with the same config file (copying non-Flatpak config file `~/.config/strawberry/strawberry.conf` to Flatpak config location `~/.var/app/org.strawberrymusicplayer.strawberry/config/strawberry/strawberry.conf`).

**Comment by jonaski** [comment]
The breaking change might be this, forcing http or https in adaptivedemux2:
https://gitlab.freedesktop.org/gstreamer/gstreamer/-/commit/df3b2e2d41067baf8d305fff5cbe0d3d7b32a939
For certain stream url requests, Tidal replies replies with a dash manifest, and strawberry creates a URL that looks something like `data:://(application/dash+xml;base64,manifest_here)`

I've tried all stream URL methods and quality settings and I can't get Tidal to reply with that specific stream URL reply, maybe it's specific to the client ID.

**Comment by jonaski** [comment]
I extracted the access token from my android phone and placed it in strawberry.conf, then get the dash xml streams, so  I can confirm that's the issue.
I modified gstadaptivedemux to allow data: for the URL, and it works again.

**Comment by jonaski** [comment]
This is merged in gstreamer now. I've opened an issue in Arch here: https://bugs.archlinux.org/task/78773 and asked if they can include the patch.
@rwolfson @mkamensky Thanks for the detailed bug report and investigation.
