### ISSUE TITLE
Network mounted media library database lost when connection is dropped

### ISSUE THREAD

**Issue by lopsided** [strawberrymusicplayer/strawberry#1228]
- [X] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [X] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [X] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
I have my music library stored on a network file storage mounted with samba. This all works fine until I use Strawberry when I'm out of the house. Then it tells me my library is empty and to add some files. This is understandable, but when I later remount my library Strawberry appears to rebuild the entire database again which a) takes ages and b) messes up my playlists (the tabs are still there but the entries are now random selections from my library). I thought "Mark disappeared songs unavailable" might fix it but this appears to make no difference on the behaviour.

**To Reproduce**
Mount a library across samba. Add it as a media folder in Strawberry. Make some playlists. Unmount the folder/disconnect from the network. Wait for Strawberry to realise, all media should disappear (may take some time). Remount the folder/reconnect to the network. Strawberry slowly rebuilds database and playlists are now incorrect.

**Expected behavior**
If the library root is not currently accessible, don't treat the files as being removed? 

**Screenshots:**
n/a

**System Information:**
 - Operating system: Fedora 38 (Linux)
 - Strawberry Version: 1.0.16

**Additional context**
My current workaround is to make sure I only use Strawberry when the drive is mounted and accessible. But inevitably this approach still leads to periodic breakages. Apart from this, I'm a big Strawberry fan. Thanks!

**Comment by jonaski** [comment]
The "Mark" disappeared songs unavailable" needs to be on, otherwise songs are deleted from the database when they are missing on disk. But when this option is on, it should mark the songs unavailable.
Testing this here, it works as expected. The songs are only marked as unavailable and reappear with the same database row id when the found again, and correctly linked to the playlist.

Can query this to check yourself with a simple query:
`select rowid, url, unavailable from songs where album = 'album name';`

When songs that were marked unavailable are found again on disk, they will be re-scanned to see if the metadata is changed too. That could perhaps be avoided to speed things up by checking the mtime for the files, but right now that's not done.

**Comment by cproensa** [comment]
An unsolicited tip here:
Mounting a samba coillection, moreso, in a dynamic enviroment like you describe where your client disconnects regularly or change locations, is a risk of unreliable behaviour, and stress for Strawberry to track and rebuld the collection.
This is the ideal use case for a subsonic music server, which is well supported by Strawberry. That way the collection is always indexed at the server, and the client only needs to sync the index and metadata. Probably more secure too, than opening samba acess outside your home network. Also better performance over slow network, vpns,... and compatibility with a variety of mobile apps, web frontends, etc
