### ISSUE TITLE
Add libsoup option to cmake

### ISSUE THREAD

**Issue by oniGino** [strawberrymusicplayer/strawberry#1256]
Looks like you depend on libsoup sometimes? but only when using gstreamer, and its not documented in any CmakeList

Please add a build option for us package maintainers :)

**Comment by jonaski** [comment]
Strawberry does not build against or link to libsoup so why should there be build option for it?

**Comment by oniGino** [comment]
```
#  if defined(Q_OS_MACOS)
  libsoup_library_path = app_path + "/../Frameworks/libsoup-3.0.0.dylib";
#  endif
  if (!libsoup_library_path.isEmpty()) {
    if (QFile::exists(libsoup_library_path)) {
      Utilities::SetEnv("LIBSOUP3_LIBRARY_PATH", libsoup_library_path);
      qLog(Debug) << "libsoup path does not exist:" << libsoup_library_path;
```
 
its conditional, but it exists

**Comment by jonaski** [comment]
You didn't answer my question, and I have no idea what you are asking for here since Strawberry does not build against libsoup , link or dynamically loads it, pasting some code that sets an environment variable isn't helping.
There is an issue template here that you are supposed to use, if you had actually used it I would have known that you were talking about macOS, but I still don't know what you are asking for here.
If you are building on macOS yourself you need to patch gstsouploader.c to actually use this environment variable.
