### ISSUE TITLE
Albums missing if file path longer than 260 characters (Windows)

### ISSUE THREAD

**Issue by dbolton** [strawberrymusicplayer/strawberry#1277]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Albums missing from Strawberry when file path includes too many characters.

**To Reproduce**
What I have:
- C:\Users\User1\Music\Include in audio player\CDs (FLAC)\European Brandenburg Ensemble & Trevor Pinnock - Bach Six Concertos for the Margrave of Brandenburg\01 - European Brandenburg Ensemble & Trevor Pinnock - Brandenburg Concerto No. 1 in F Major - I. [Allegro].flac
- C:\Users\User1\Music\Include in audio player\Freegal\Joshua Bell - Double Concerto in A Minor, Op. 102 for Violin, Cello and Orchestra\JoshuaBell_DoubleConcertoInAMinorOp102ForViolinCelloAndOrchestraIIIVivaceNonTroppo_DoubleConcertoInAMinorOp102ForViolinCelloAndOrchestraIIIVivaceNonTroppo_1.mp3

Show up in Strawberry when file paths shortened to: 
- C:\Users\User1\Music\Include in audio player\European Brandenburg Ensemble - Bach Six Concertos for the Margrave of Brandenburg\01 - European Brandenburg Ensemble & Trevor Pinnock - Brandenburg Concerto No. 1 in F Major - I. [Allegro].flac
- C:\Users\User1\Music\Include in audio player\Joshua Bell - Double Concerto in A Minor, Op. 102 for\JoshuaBell_DoubleConcertoInAMinorOp102ForViolinCelloAndOrchestraIIIVivaceNonTroppo_DoubleConcertoInAMinorOp102ForViolinCelloAndOrchestraIIIVivaceNonTroppo_1.mp3

**Expected behavior**
All albums in the scanned folders should appear in the Strawberry collection regardless of file length. For comparison, these albums appear in other audio players like Media Player (bundled with Windows), Exaile, foobar2000.

**System Information:**
 - Operating system: Windows 10 
 - Strawberry Version: 1.0.18-71-g560712db

**Comment by jonaski** [comment]
I can confirm this, but the issue is in TagLib.

`TagLib: Could not open file C:/Data/Test_Music/LongPath/long_path_long_path_long_path_long_path_long_path_long_path_long_path_long_path_long_path_long_path_long_path_long_path_long_path_long_path_long_path_long_path_long_path_long_path_long_path_long_path_long_path_long_path/After_Paradise/02_-_Snowy_White_-_After_Paradise_-_Midnight_Blues.flac`

**Comment by jonaski** [comment]
This is because TagLib uses ``MAX_PATH`` limitations:  https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry
We have to wait for the next major TagLib release which should remove such restrictions. Not much I can do for now.

**Comment by jonaski** [comment]
Still an issue in TagLib 2.0, 
when debugging it I've found it is caused by CreateFileW used by TagLib, but according to according to https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry the limitation should be removed as of Windows 10, version 1607 if  ``Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem\LongPathsEnabled`` is set to 1. But I can still reproduce it, but prefixing the path with "\\?\" works.

**Comment by jonaski** [comment]
Opened a PR to fix this in TagLib: https://github.com/taglib/taglib/pull/1216
