### ISSUE TITLE
(macOS) macdeployqt does not deploy libraries with .so extensions

### ISSUE THREAD

**Issue by llucps** [strawberrymusicplayer/strawberry#1278]
Hi,

I've successfully compiled Strawberry 1.0.20 following this article https://wiki.strawberrymusicplayer.org/wiki/GStreamer_plugins, but when I tried to play a file I got this error:

`GStreamer could not create the element playbin with name pipeline-4-pipeline.`

I carefully checked that all the plugins are installed, and it seems to be the case.

```
gst-inspect-1.0 playbin
Factory Details:
  Rank                     none (0)
  Long-name                Player Bin 2
  Klass                    Generic/Bin/Player
  Description              Autoplug and play media from an uri
  Author                   Wim Taymans <wim.taymans@gmail.com>

Plugin Details:
  Name                     playback
  Description              various playback elements
  Filename                 /opt/local/lib/gstreamer-1.0/libgstplayback.so
  Version                  1.16.2
  License                  LGPL
  Source module            gst-plugins-base
  Source release date      2019-12-03
  Binary package           GStreamer Base Plug-ins source release
  Origin URL               Unknown package origin

GObject
 +----GInitiallyUnowned
       +----GstObject
             +----GstElement
                   +----GstBin
                         +----GstPipeline
                               +----GstPlayBin

Implemented Interfaces:
  GstChildProxy
  GstStreamVolume
  GstVideoOverlay
  GstNavigation
  GstColorBalance

Pad Templates:
  none
```
This does NOT happen on Strawberry 1.0.18 which I also compiled myself following the same article.

Any idea where to look at?

Thanks.

**Comment by jonaski** [comment]
What OS is this? mac? The link is only a gstreamer plugin overview.

**Comment by llucps** [comment]
Sorry I forgot to mention that. Yes Mac OS Ventura 13.5.1, and yes it's the wrong link.. I meant this one https://wiki.strawberrymusicplayer.org/wiki/Compile_macOS_using_macports

The compiling works fine, and Strawberry runs fine except when trying to play a song, I get a dialog with the error:

`GStreamer could not create the element playbin with name pipeline-1-pipeline.`

**Comment by jonaski** [comment]
It's because I switched from a modified macdeployqt to a script for copying gstreamer plugins, macports uses an older version of gstreamer which uses .so extension for plugins instead of .dylib. Looks like I was checking both extensions before (https://github.com/strawberrymusicplayer/strawberry/commit/878148ac32a9afc09f03f87d33a958022268fb4f#diff-fdce6e62828ca53e33290fd08f227059df34fed60878476fc2c9d140587807c3L1371).
However, it looks like macdeployqt only checks .dylib, not .so libraries, so the rpaths does not get adjusted after deployed. This was probably the main reason I was using a modified macdeployqt in the first place.

**Comment by llucps** [comment]
Thank you!
