### ISSUE TITLE
Cannot build on macOS Monterey or newer

### ISSUE THREAD

**Issue by davidbitterlich** [strawberrymusicplayer/strawberry#1321]
- [v] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [v] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [v] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
When I try to compile strawberry on macOS, just like described on the wiki page: https://wiki.strawberrymusicplayer.org/wiki/Compile_macOS_using_homebrew
I will get the problem, that protobuf does not find its dependent header file attributes.h from abseil package. I've applied the following workaround in the CMakeLists.txt files under ext/libstrawberry-tagreader/CMakeLists.txt, ext/strawberry-tagreader/CMakeLists.txt and src/CMakeLists.txt:
I added '${ABSL_INCLUDE_DIRS}' to the target_include_directories list and manually specified this variable in the cmake step to /opt/homebrew/Cellar/abseil/20230802.1/include
I also needed to specify PROTOBUF_INCLUDE_DIRS as it was also not detected by cmake: /opt/homebrew/Cellar/protobuf/25.1/include

However, I don't know why abseil was not detected by protobuf and why protobuf was not detected by cmake correctly. I followed the guide so far step by step.

**To Reproduce**
1. setup a clean new macOS machine (virtual or physical does not matter)
2. follow the guide (https://wiki.strawberrymusicplayer.org/wiki/Compile_macOS_using_homebrew) until the make step
3. run make

**Expected behavior**
The compilation should run fine without any issues

**Screenshots:**
-

**System Information:**
 - Operating system: macOS Monterey 12.6.3 aarch64 (virtual machine)
 - Strawberry Version: current master branch (1.0.21)

**Additional context**
The documentation in how to build strawberry on macOS could be improved, there are some issues in the documentation regarding the variables on aarch64 - in general it should be mentioned that /usr/local is only for x86_64 and on aarch64 /opt/homebrew is used instead, so each path starting with /usr/local is wrong for aarch64 and it would be nice if the documentation could be updated so that there are separate instructions for each architecture, just like it was already started with...

**Comment by jonaski** [comment]
Its the cmake files provided by protobuf that does not set PROTOBUF_INCLUDE_DIRS, so it needs to be manually provided to cmake, you can simply append the abseil includes to PROTOBUF_INCLUDE_DIRS and it should work.
I've added a notice on top of https://wiki.strawberrymusicplayer.org/wiki/Compile_macOS_using_homebrew, that it
s currently not maintained / updated.  If you want to update it I can give you access, but otherwise it's not maintained.
Homebrew is changing all the time so the guide needs continuous updating, since I build all dependencies from source now I no longer use homebrew to build the official strawberry releases, homebrew was just too flawed to be using it for official strawberry releases.
There is almost always one or more patches that needs to be applied to Qt or gstreamer to fix upstream issues too.

**Comment by davidbitterlich** [comment]
Ok I understand your concerns, but is there any better documentation which describes how to successfully compile strawberry without any problems on macOS? From what I see, MacPorts is also not supported anymore and it sounds like you do a lot of manual steps, including compiling and patching Qt from source...
