### ISSUE TITLE
thanks for strawberry - happy 2024 - stops playback when  encountere like DRM protected wmas

### ISSUE THREAD

**Issue by Edgepath** [strawberrymusicplayer/strawberry#1347]
Hello,

thanks for strawberry fork of clementine :D 

managed to install it like this: https://dwaves.de/2023/12/09/gnu-linux-music-imho-currently-best-music-player-for-gnu-linux-and-music-creation-tools-please-donate-so-that-the-hidden-gems-of-the-internet-stay-online/

imho it's one of the best Open Source music players :+1: 

got it configured: auto play on startup

**Describe the bug**

Strawberry stops playing with error: "The stream is encrypted and decryption is not supported."

../gst/asfdemux/gstasfdemux.c(4582): gst_asf_demux_process_object (): /GstPlayBin3:pipeline-1-pipeline/GstURIDecodeBin3:uridecodebin3/GstURISourceBin:urisourcebin0/GstParseBin:parsebin0/GstASFDemux:asfdemux1

*.wma <- VLC reports: "Could not demux ASF stream: DRM protected streams are not supported."

so this is some form of DRM protected content X-D

which is fine for me if Strawberry simply skips those titles and keeps playing :)

**To Reproduce**

play some DRM protected wma. if necessary can provide the file X-D

**Expected behavior**

maybe log some error but not display error and keep playing :)

**System Information:**
 - Operating system: Debian 12 
 - Strawberry Version: Version 1.0.22

thanks!

**Comment by UltimateSolar** [comment]
thanks that was FAST :D

**Comment by UltimateSolar** [comment]
Hello,

how are you? (damn cold here)

got a "similar problem" "Resource not found"

../plugins/elements/gstfilesrc.c(553): gst_file_src_start (): /GstPlayBin3:pipeline-5-pipeline/GstURIDecodeBin3:uridecodebin3/GstURISourceBin:urisourcebin12/GstFileSrc:filesrc12: No such file "/home/user/Music/Dream Theater/dream theater/Dream Theater - Fatal Trage.mp3"

<- the file was deleted because too much tragedy is no good, strawberry halts playback. why? just go to next title :D

just keep em' play'n bro :D
