### ISSUE TITLE
Implement Rich Presence

### ISSUE THREAD

**Issue by dakralex** [strawberrymusicplayer/strawberry#1356]
Hello Strawberry community!

First of all, I wanted to thank you for this player. I've been using Clementine for about a decade and migrated to Strawberry seamlessly some months ago - finally.

I would like to make a contribution to the project and wanted to ask if it was in the interest of the application. I would like to implement Discord's Rich Presence API, so that other people can see what you're listening to. I think it's pretty cool.

The feature would be opt-in of course, so it can be disabled in the build process and in the options. The API is documented [here](https://discord.com/developers/docs/game-sdk/activities) and [here](https://discord.com/developers/docs/rich-presence/how-to), which is focused on in-game presence, but I hope that I'm able to find a way to have a similar display as the one when someone is listening to Spotify. I would also be available to maintain that addition in the feature, in case the API changes, there are some questions or it needs to be changed some way.

What do you think?

**Comment by liif-starstorm** [comment]
As a user I can only say that I'd love to see this; the current workarounds for getting Discord to show what Strawberry is playing aren't exactly amazing. Would be awesome to see it have a clean Discord Rich Presence!

**Comment by jonaski** [comment]
My answer here: https://github.com/strawberrymusicplayer/strawberry/issues/109#issuecomment-647483316

**Comment by dakralex** [comment]
> My answer here: [#109 (comment)](https://github.com/strawberrymusicplayer/strawberry/issues/109#issuecomment-647483316)

All right, I will look into it at the start of February. I'm new to the project, should I make a proposal as a PR and then implement it or the other way around? Is there some communication channel where I can ask others on feedback other than in the PR?

**Comment by jonaski** [comment]
> > My answer here: [#109 (comment)](https://github.com/strawberrymusicplayer/strawberry/issues/109#issuecomment-647483316)
> 
> @jonaski All right, I will look into it at the start of February. I'm new to the project, should I make a proposal as a PR and then implement it or the other way around? Is there some communication channel where I can ask others on feedback other than in the PR?

Wouldn't you need to implement it for opening a PR?

There is https://forum.strawberrymusicplayer.org/
Artifacts are available for PR's so it's possible for users to test on different distros and Windows without building.

**Comment by jonaski** [comment]
Closing this as I haven't hard anything in over 2 months. A PR is still welcome.

**Comment by fruityloops1** [comment]
I would like to PR this but it's pretty difficult since all of the open source libraries that support RPC are now outdated, and discord offers 3 "official" options:

- "Social SDK", which is a closed source C++ library bundled as a dynamic library, walled off behind a developer application process (which mostly assumes that the person applying for it is a company)
- "Game SDK", which is the same as the Social SDK, but deprecated, and not walled off behind an application process
- "Embedded SDK", which is only available for JavaScript

The only of the above that would really work is the Game SDK, but I severely doubt you'd want a closed source library that only works on certain architectures bundled with this player. Really disappointing how discord provides barely any options to use their features
