### ISSUE TITLE
Strawberry flatpak compiled without iPod support?

### ISSUE THREAD

**Issue by seficharis** [strawberrymusicplayer/strawberry#1451]
Hi Guys

I just installed strawberry from flathub and it tells me the app is compiled without support for iPod devices.
Anyone else has this issue? 
I would compile it myself but i cannot get some dependencies on ubuntu 24.04

I hope updated versions would fix this.

**Comment by seficharis** [comment]
OK I managed to compile it from source. 
Thanks for providing the list of libraries used. This project is so well maintained.
Now it recognizes devices, but it cannot copy any music to it. It somehow messes with iPods database and the music that was already there is unaccessable. The device must go through reset in itunes.
I have 3 ipods, nano 3 gen, 5gen, classic 6 gen. It is same across all. Strangely the music is there in Strawberry, just the device cannot see any music after unplugging.
Is that why this was removed from the flatpak?

**Comment by jonaski** [comment]
You need to ask the Flatpak packagers.
Unfortunately, some newer iPod models are not compatible with the libgpod, I think Apple switched to some sort of encrypted database to prevent 3rdparty software from using them, that's probably why your iPod shows no songs, because libgpod writes it in a wrong database format.

**Comment by seficharis** [comment]
Thank you for the reply. Too bad libgpod was abandoned. It looks like there is no alternative to get iPods to sync on linux.
