### ISSUE TITLE
"Organizing Files" infinitely when copying music to an ipod mini

### ISSUE THREAD

**Issue by RolesG** [strawberrymusicplayer/strawberry#1472]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
"Organizing Files" stuck at 0% attempting to copy files to an old ipod

**To Reproduce**
Steps to reproduce the behavior.
Attempted to copy files to my ipod mini, got 'Organizing Files' indefinitely.

**Expected behavior**
Files copy to ipod

**Screenshots:**
![Screenshot_20240628_020229](https://github.com/strawberrymusicplayer/strawberry/assets/95465444/029878d0-8b0e-45d0-95dc-53838d166ed2)

**System Information:**
 - Operating system: Fedora 40
 - Strawberry Version: 1.0.23 (dnf)

**Additional context**
I was able to transfer files to this ipod before, I have no idea what changed since then.

**Comment by jonaski** [comment]
This isn't something I'd be able to debug, since I can't reproduce the issue here.
Most likely one of the calls to copy tracks (itdb_cp_track_to_ipod) hangs, so it's stuck. This could be that the DB on the iPod is corrupt, or that the iPod is not properly handled by the libgpod library.
You could try to delete the iPod and reconnect it in strawberry first, right click on the device and select forget.
if that doesn't work, you can try to use iTunes to reset the iPod.
