### ISSUE TITLE
Analyzer is not working for all audio formats

### ISSUE THREAD

**Issue by kevinmcmurtrie** [strawberrymusicplayer/strawberry#155]
Using default settings on Ubuntu 19.04 with gstreamer.  All analyzers show high-intensity noise on AAC tracks.  FLAC and MP3 work.

**Comment by alekksander** [comment]
what are this AAC file properties? i noticed something similar with high resolution audio (24/96 if i recall)

**Comment by jonaski** [comment]
I'm aware of it, it's don't work with anything than 44.1/16 because the analyzer does not handle that, need to find a way to resample the pipeline that is sent to the analyzer without affecting what is played. Currently I did not find a way to work that out.

**Comment by alekksander** [comment]
a bit off topic, bur regarding analyzer — is it intended that its menu shows both at right and left click?

**Comment by jonaski** [comment]
AAC is affected even if it's 44.1/16 for some reason.

**Comment by jonaski** [comment]
@alekksander No, I did not notice that.

**Comment by jonaski** [comment]
On my McIntosh DAC playing 192/24 files (the dac display shows 192/24)

access: RW_INTERLEAVED
format: S24_3LE
subformat: STD
channels: 2
rate: 192000 (192000/1)
period_size: 1920
buffer_size: 38400

This is what is output if I force 16bit for the analyzer (Display on the DAC shows; 192/16):

access: RW_INTERLEAVED
format: S16_LE
subformat: STD
channels: 2
rate: 192000 (192000/1)
period_size: 1920
buffer_size: 38400

So I rather leave it like it is.

**Comment by alekksander** [comment]
I guess this brings us to the analyzer itself. It seems rather symbolic than informative in current state (clementine heritage...?). In my understanding a „bit perfect” music player should adapt to frequency currently played with detailed info about its (low and top) range. Are there plans to improve the analyzer to be more detailed, more precise? Still its probably not something vital for reliable precise playback, but rather a feature extending possibilities.

**Comment by jonaski** [comment]
If we can fix so they work for other bit depths too without resampling the bit depth in the pipeline the way it is it in Clementine I think we should keep them, but we could also add a more technical correct analyzer like you suggest.
But I don't understand the analyzer code or know how to write a new one, so unless someone else does it it's not going to happen any time soon.
The existing block and boom analyzers are from amarok 1.x with some improvements by a few clementine contributors, that and parts of engine code, the equalizer and the volume slider (maybe a few small widgets too) are the only things that are from amarok.
Very few people have worked on them in Clementine and I doubt many understand how they work . Most of the Clementine contributors have left anyway.

**Comment by kozga** [comment]
The analyzer also works incorrectly with ogg vorbis (even 44.1/16).

**Comment by m4x3t** [comment]
For me the analyzer only shows noise for every file type when replay gain is enabled.

**Comment by jonaski** [comment]
@m4x3t 
Yeah it does.
Xine might work with the analyzer with different bits, if someone can test. it's broken on my system and produces loud noise so I cant' test with Xine now.
If it works with xine and different samplerates / bit depths maybe could look at some of the code for the xine engine how it's done there:
https://github.com/jonaski/strawberry/blob/master/src/engine/xineengine.cpp#L905

**Comment by m4x3t** [comment]
I can confirm that with Xine the analyzer works for 44.1/16 AAC files.

**Comment by RomanHargrave** [comment]
I will add that I am on Gstreamer and that the analyzer appears to be noise for me regardless of format. This happens with my very unconventional JACK setup at home, and my very conventional, stock Debian/KDE/Pulse setup at work.

**Comment by jonaski** [comment]
I tried various ways of fixing the splitting of the pipeline that is supposed send unmodified stream to the speaker and 16 bit to the analyzer. I've had little success. The problem is that it's auto- negotiated to 16 bit even when forcing the other caps to S32LE. It works fine with some DAC's but not others.
I decided just to get rid of the whole splitting (tee and the probe stuff) and try to convert the audio buffer instead.
So far I've had some progress, I've managed to convert S32LE to S16LE for the analyzer. So S32LE now works which means AAC/MP4 works if it's not re-sampled to F32LE (if you set a device in the settings).
I've been trying to convert S24LE too, but so far no luck.
I've decided to disable the analyzer for the other formats that currently doesn't work.
S24LE and F32LE isn't working and remains to be fixed.
If you enable replay gain, the format will always be F32LE, so that means no analyzer.

**Comment by mashiro-tan** [comment]
Almost managed to get the fully working analyzer, but then looked at the Clementine sources and found that this problem was solved at least 4 years ago (same way). Is there a problem with Clementine's variant? Two buffers with two conversions not quite the good idea, but its at least something and better than manually written convertors. And that implementation is working, what's most important.

At least i've got a practice with the gstreamer, huh.

**Comment by jonaski** [comment]
The splitting with a tee doesn't work and will always resample the bit depth. The analyzer works but you get the resampling. None of the solutions in Clementine has worked. The problem is that gstreamer negotiates to the lowest one (at least with FLAC). That's why I moved away from it completely. I think the problem needs to be adressed in GStreamer first, but I've set up a small test program if you are interested: https://github.com/jonaski/gstpipelinetest
Here is the answer I received from the gstreamer mailinglist:

> I've given another look, and notice that flacdec does not expose S24LE
> as an output format, only the 32bit aligned variant (same bits though)
> is available. Consider changing your filter into format=S24_32LE. This
> will yield the same quality, but will use slightly more bandwidth.
> 
> Someone would have to look into the element (flacdec) code, so see if
> the packed S24LE can be supported. Another thing that could be improved
> in flacdec is the format order:
> 
>   format: { (string)S8, (string)S16LE, (string)S24_32LE, (string)S32LE }
> 
> I haven't checked in the code, but if upstream element uses
> gst_caps_fixate() without any logic, the end result would prefer 8bit,
> followed by 16bit, over 24 and 32bit variants. I think we should flip
> these caps order, just in case. That being said, many upstream elements
> are smarter then this.
> 
> regards,
> Nicolas

**Comment by mashiro-tan** [comment]
Just checked, really... I've been sceptic about gstreamer ability to transfer a stream without any loss (judging how the pipeline is built), but didn't expect that one element can affect the entire bin. And i didn't checked it's behaviour with the FLAC (only OGG/MP3) so i thinked that all is good.
Well then, i'll try to search another solution, thanks.

**Comment by jonaski** [comment]
Finally managed to fix analyzer for S24LE and F32LE formats. Please test.

**Comment by jonaski** [comment]
I was very close a year ago to fix it, I almost did the same code the last time.
