### ISSUE TITLE
Double click starred playlist vs double click smart playlist has different result

### ISSUE THREAD

**Issue by scubanarc** [strawberrymusicplayer/strawberry#1567]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
When you double-click a 'Starred' playlist, it opens in a new tab. When you double-click a 'Smart Playlist, ' it will append to the end of the existing tab. This is confusing and not consistent.

**To Reproduce**
Double-click a 'Starred' playlist, then double-click a 'Smart Playlist,' and Strawberry will append the 'Smart Playlist' to the end of your 'Starred' playlist. You have just modified your 'Starred' playlist, possibly on accident.

**Expected behavior**
In both cases, double-clicking should result in a new tab opening with the playlist.

**Screenshots:**
Not needed.

**System Information:**
 - Operating system: Mint 22
 - Strawberry Version: 1.1.3

**Comment by jonaski** [comment]
This is intentional, since smart playlists is generating songs that you add to a specific playlist, you sometimes want to add more from a different smart playlist generator, you can't do that if the action was opening a new playlist each time. A option could be added to add to a new playlist, but since this project has only 1 developer, it's currently not possible to fix all bugs, I have to prioritize, and this seems something that easily can be worked around.
