### ISSUE TITLE
New songs not being added (Subsonic)

### ISSUE THREAD

**Issue by llucps** [strawberrymusicplayer/strawberry#1598]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
New songs are not being processed after clicking the Refreshing catalog button from Subsonic Tab.

**To Reproduce**
After refreshing the catalog from Subsonic, the progress bar goes all the way through to 100% and I get this error:

`Unable to execute SQL query: Parameter count mismatch<br />Failed query: UPDATE subsonic_songs_fts SET ftstitle = Rehumanize Yourself, ftsalbum = Ghost in the Machine, ftsartist = The Police, ftsalbumartist = Ghost in the Machineartist, ftscomposer = , ftsperformer = , ftsgrouping = , ftsgenre = Rock, ftscomment = WHERE ROWID = 1`

**System Information:**
 - Operating system: Debian 12 Bookworm
 - Strawberry Version: 1.0.14 (from the official debian repos)

**Additional context**
This problem does not happen on the latest 1.1.3 build from your website, it works fine. The problem is I?m still using QT5 and the 1.1.3 build uses QT6 which although totally functional, the theme does not look as good as using QT5.

**Comment by jonaski** [comment]
1.0.14 is too old, too much have changed since that version, so if the issue is not present in a newer version, that's not a bug I'm going to fix.

But this can happen if there is an issue with the database file (corruption), or you used a newer version of strawberry which means the database has been upgraded to a newer schema incompatible with the older version of strawberry.

I suggest running a database integrity check:
https://wiki.strawberrymusicplayer.org/wiki/Database_integrity_check

To check which version the database is, use:
`sqlite3 ~/.local/share/strawberry/strawberry/strawberry.db "select * from schema_version"`
For version 1.0.14, the DB version should be 15, if it's higher than it's no longer compatible and you need to start with a new DB file.

The style should work independent of whether Strawberry is Qt 5 or 6, so that sounds like a configuration issue, or Debian bug.

**Comment by llucps** [comment]
Understood, thank you
