### ISSUE TITLE
Build fails on MacOS with Qt related error

### ISSUE THREAD

**Issue by logkirk** [strawberrymusicplayer/strawberry#1613]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Build from source fails on MacOS 15.1.1 (24B91). I followed the [instructions listed here](https://wiki.strawberrymusicplayer.org/wiki/Build_macOS). I combined these steps into a shell script for repeatability. Here's exactly what I ran:

```
#!/usr/bin/env bash

# https://wiki.strawberrymusicplayer.org/wiki/Build_macOS

cd ~/Downloads
rm -rf strawberry

# Download and install dependencies
curl -f -O -L https://github.com/strawberrymusicplayer/strawberry-macos-dependencies/releases/latest/download/strawberry-macos-$(uname -m)-release.tar.xz
sudo tar -C / -xf strawberry-macos-$(uname -m)-release.tar.xz
rm strawberry-macos-$(uname -m)-release.tar.xz

# Checkout code
git clone --recursive https://github.com/strawberrymusicplayer/strawberry
cd strawberry
mkdir build
cd build

# Configure build
PKG_CONFIG_PATH=/opt/strawberry_macos_$(uname -m)_release/lib/pkgconfig LDFLAGS="-L/opt/strawberry_macos_$(uname -m)_release/lib -Wl,-rpath,/opt/strawberry_macos_$(uname -m)_release/lib" /opt/strawberry_macos_$(uname -m)_release/bin/cmake --log-level="DEBUG" -S .. -B . -DCMAKE_BUILD_TYPE="Release" -DBUILD_WITH_QT6=ON -DUSE_BUNDLE=ON -DCMAKE_PREFIX_PATH="/opt/strawberry_macos_$(uname -m)_release/lib/cmake" -DPKG_CONFIG_EXECUTABLE="/opt/strawberry_macos_$(uname -m)_release/bin/pkg-config" -DICU_ROOT="/opt/strawberry_macos_$(uname -m)_release" -DFFTW3_DIR="/opt/strawberry_macos_$(uname -m)_release" -DENABLE_DBUS=OFF -DGETTEXT_MSGMERGE_EXECUTABLE="/opt/strawberry_macos_$(uname -m)_release/bin/msgmerge" -DGETTEXT_MSGFMT_EXECUTABLE="/opt/strawberry_macos_$(uname -m)_release/bin/msgfmt" -DGETTEXT_XGETTEXT_EXECUTABLE="/opt/strawberry_macos_$(uname -m)_release/bin/xgettext"

# Build
make -j 4
make install

# Set environment variables
export GIO_EXTRA_MODULES="/opt/strawberry_macos_$(uname -m)_release/lib/gio/modules"
export GST_PLUGIN_SCANNER="/opt/strawberry_macos_$(uname -m)_release/libexec/gstreamer-1.0/gst-plugin-scanner"
export GST_PLUGIN_PATH="/opt/strawberry_macos_$(uname -m)_release/lib/gstreamer-1.0"
export LIBSOUP_LIBRARY_PATH="/opt/strawberry_macos_$(uname -m)_release/lib/libsoup-3.0.0.dylib"

# Deploy
make deploy

# Deploy check
make deploycheck

# Create DMG
make dmg

cd -
```

Here is the excerpted error from the build log:

```
"strawberry.app/Contents/Frameworks/QtVirtualKeyboard.framework/Versions/A/QtVirtualKeyboard" does not exist for "strawberry.app/Contents/PlugIns/platforminputcontexts/libqtvirtualkeyboardplugin.dylib"
"strawberry.app/Contents/Frameworks/QtQuick.framework/Versions/A/QtQuick" does not exist for "strawberry.app/Contents/PlugIns/platforminputcontexts/libqtvirtualkeyboardplugin.dylib"
"strawberry.app/Contents/Frameworks/QtQmlModels.framework/Versions/A/QtQmlModels" does not exist for "strawberry.app/Contents/PlugIns/platforminputcontexts/libqtvirtualkeyboardplugin.dylib"
"strawberry.app/Contents/Frameworks/QtQml.framework/Versions/A/QtQml" does not exist for "strawberry.app/Contents/PlugIns/platforminputcontexts/libqtvirtualkeyboardplugin.dylib"
"strawberry.app/Contents/Frameworks/QtPdf.framework/Versions/A/QtPdf" does not exist for "strawberry.app/Contents/PlugIns/imageformats/libqpdf.dylib"
make[3]: *** [CMakeFiles/deploycheck] Error 1
make[2]: *** [CMakeFiles/deploycheck.dir/all] Error 2
make[1]: *** [CMakeFiles/deploycheck.dir/rule] Error 2
make: *** [deploycheck] Error 2
```

Additionally, the app fails to open with the following error:

```
01:40:35.796 INFO  main:181                         Strawberry 1.2.2-1-g2548b464 Qt "6.8.0"
01:40:35.796 INFO  main:182                         "macOS Sequoia (15.1) 15.1 - (darwin 24.1.0) [arm64]"
01:40:35.797 DEBUG unknown                          Could not load the Qt platform plugin "cocoa" in "" even though it was found.
01:40:35.797 ERROR unknown                          This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
01:40:35.797 ERROR unknown
01:40:35.797 ERROR unknown                          Available platform plugins are: cocoa.
01:40:35.797 ERROR unknown
```

**To Reproduce**
Download and run the script, or execute the steps manually.

**Expected behavior**
The build finishes successfully and the application runs.

**Screenshots:**
N/A

**System Information:**
 - Operating system: MacOS 15.1.1 (24B91)
 - Strawberry Version: master branch, commit hash 2548b46

**Additional context**
N/A

**Comment by jonaski** [comment]
Strawberry does not use Qt Xml, Quick and Pdf, those modules are not built and part of the dependencies. Also, the dependencies doesn't have the `libqtvirtualkeyboardplugin.dylib` plugin file as it's not used either, so where did that file come from? Do you have another Qt installation?

It is important that the correct macdeployqt utility is used, as it will resolve the Qt plugins dir, if if you use a macdeployqt utility from a different Qt installation, it will pick up plugins that belong to a different Qt installation than the one you compiled with.
Check with: `grep MACDEPLOYQT_EXECUTABLE CMakeCache.txt`

To make sure the correct macdeployqt utility is used pass `-DMACDEPLOYQT_EXECUTABLE=/opt/strawberry_macos_$(uname -m)_release/bin/macdeployqt`

I've added this to the build instructions.

The second error is because it doesn't find the cocoa platform plugin, so you need to check that's correctly installed and the rpaths for it are correct.

In any cause, this is pretty basic macOS/CMake/Qt programming issues, so I suggest to use the Qt forum for Qt programming support as I have limited time to give programming support.

**Comment by logkirk** [comment]
Yes, I have another Qt installation required for other projects, and the build succeeded after the `DMACDEPLOYQT_EXECUTABLE` is passed; no other changes were needed.

> In any case, this is pretty basic macOS/CMake/Qt programming issues, so I suggest to use the Qt forum for Qt programming support as I have limited time to give programming support.

I appreciate your help, but I don't agree that the Qt forums are the appropriate place for this discussion since this ended up with an edit to the build instructions. Regardless of limited resources, I don't think this sort of hostility contributes to a better project in the long run.

**Comment by AllKind** [comment]
Hostility?
He helped you to solve your problem.
He even updated documentation for this corner case to help other users in the future -> better project in the long run.
Just because he suggested to discuss the matter of parallel QT installations at QT forums you feel offended?
Personally I think he's absolutely right. If you have parallel installs, which is not standard in any way, but a deliberate modification of the system, then you should know of the consequences it has. But obviously you did not even try to use your brain.
There was nothing unfriendly, or even hostile.
Reality check dude!!!
