### ISSUE TITLE
Convert diacritic letters when searching

### ISSUE THREAD

**Issue by alekksander** [strawberrymusicplayer/strawberry#203]
Would it be possible if Strawberry interpret characters as „Ł” as „L” and vice versa? there are many foreign characters not available for most users making it impossible to search library for some artists. For example such characters are present in Polish, Dutch, Spanish, German, Hungarian, Icelandic and probably many more latin languages . I stumbled across this issue when was trying to find polish „Vołosi”. Without Strawberry seeing „ł” as „l” it's impossible to search for those. More examples are:

Ä → A
Á → A
Ñ → N
Ó → O

**Comment by NucleaPeon** [comment]
Perhaps it could be a toggleable option, because if people have international keyboards, they may want to search for those specific characters.

**Comment by jonaski** [comment]
I need something like that for the organiser when stripping non-ascii characters. Maybe boost has something.
I don't want it as default for the search, but maybe it could be an option.

**Comment by ronjakoi** [comment]
The Apache Lucene search engine backend has a plugin which does Unicode to ASCII folding. It is basically implemented as a giant ad hoc [`switch` statement in Java](http://svn.apache.org/repos/asf/lucene/java/tags/lucene_solr_4_5_1/lucene/analysis/common/src/java/org/apache/lucene/analysis/miscellaneous/ASCIIFoldingFilter.java) (see method `foldToASCII()`).

**Comment by jonaski** [comment]
If someone wants to do this. We can use iconv, I made the function here: https://github.com/jonaski/strawberry/blob/master/src/core/utilities.cpp#L792

**Comment by KingDuckZ** [comment]
I think in general it would be nice to be able to search into anything. For example I have many songs in Japanese but I didn't setup Japanese input. I don't know how easily this could be done but it would be really good if I type for example Mizuki and results like 水木 are shown.

**Comment by jonaski** [comment]
I'm closing this since this is only a minor detail, and I don't have time to prioritize it. Anyone else is free to make a proposal for a change in a PR.

**Comment by jonaski** [comment]
I changed my mind. It makes sense since it was possible to search for diacritic letters before I changed from FTS3 to FTS5.
So I changed this now, the change takes affect only with new DB's, but you can convert the existing FTS tables to remove_diacritics 1.

Backup strawberry.db in case this goes wrong.

Go on Tools / Console:

Type the following in the bottom command line, after each command press the Run button and replace the text in the command to enter the next command:

`drop table songs_fts;`

`CREATE VIRTUAL TABLE songs_fts USING fts5(ftstitle, ftsalbum, ftsartist, ftsalbumartist, ftscomposer, ftsperformer, ftsgrouping, ftsgenre, ftscomment, tokenize = "unicode61 remove_diacritics 1");`

`INSERT INTO songs_fts (ROWID, ftstitle, ftsalbum, ftsartist, ftsalbumartist, ftscomposer, ftsperformer, ftsgrouping, ftsgenre, ftscomment) SELECT ROWID, title, album, artist, albumartist, composer, performer, grouping, genre, comment FROM songs;`

Screenshot:

![image](https://user-images.githubusercontent.com/10343810/88925002-455d4080-d274-11ea-9cde-c1e5db4af627.png)

**Comment by alekksander** [comment]
seems to be working here. thanks a lot!
