### ISSUE TITLE
Feaure request: Fullscreen visualization

### ISSUE THREAD

**Issue by ryanmusante** [strawberrymusicplayer/strawberry#230]
Is it a future possibility for visualization alike to projectM?
https://wiki.archlinux.org/index.php/ProjectM

**Comment by jonaski** [comment]
I don't like projectm much, is there an alternative?

**Comment by ryanmusante** [comment]
What about using the original spectrum analyzer fullscreen plugin from clementine, something simple and neat.

**Comment by desputinski** [comment]
Hm, why not Projectm? It has a wide variety of different visualizations. The only thing I dislike about it, is that is confusing and too many visualizations...

**Comment by ryanmusante** [comment]
What about ripping only one feature from projectm and integrating?

**Comment by RomanHargrave** [comment]
> I don't like projectm much, is there an alternative?

There's [VSXu](https://www.vsxu.com/); however, this seems out of scope to me (then again, I use JACK - so I can just run a visualizer and plug strawberry in to it). Picking a single visualizer from ProjectM like Ryan suggests also seems a little strange - though if one were to go the route of embedding something like ProjectM or VSXu, I think ProjectM would probably be the most straightforward choice because of libprojectM which can accept PCM data and spit out a texture or draw to a GL context. I believe VSXu may be a little more involved, not to mention it's closer to something like Processing than ProjectM.

**Comment by jonaski** [comment]
I can't prioritize this now, we need to prioritize a new analyzer.

**Comment by KingDuckZ** [comment]
I would also like to vote for adding a visualizer

**Comment by eebssk1** [comment]
Is there any plan to add it? Clementine already uses projectM,I just switched to strawberry and I'm missing the feature.

**Comment by tom709** [comment]
It seems that other projects are able to implement Milkdrop in a Music player; if not with stubborn Linux frameworks, but in a web browser:
git clone https://github.com/captbaritone/webamp.git
open webamp/examples/minimal/index.html in browser
drag mp3 to playlist and press play
done
