### ISSUE TITLE
Bring back "Add stream"

### ISSUE THREAD

**Issue by llucps** [strawberrymusicplayer/strawberry#244]
I know that adding podcast support has been requested in the past and I understand you don't want to go that route.. but would it be possible at least to bring back the "Add Stream functionality that Clementine has?

I don't need the podcast functionality (although I would like to :D), that I handle myself using a script which downloads all the RSS and insert them into m3u file. But at least it would be handy to be able to open a m3u (hosted on my own server from internet, not locally) in a playlist by just adding an stream and specifying the URL.

Thanks,

**Comment by jonaski** [comment]
The add stream depends on the internet support in Clementine, which I didn't include to make it easier to maintain. The streams in clementine is just called "your radio stream" in the internet tab. It's a lot of code, and if we add it back I want to review everything and improve it at the same time, not just add it back like it is. Possible just add back streams in it's own widget in the tabbar. We could make it add directly to the playlist, but then we need to add support for identifying the streams first.
In any case I want to add stream discovery to the pipeline first so it automatically detects sample rate, bit depth and bit rate. When I do that I also need a subscription with both Tidal and Qobuz to make sure it doesn't break anything.
Things like Tidal and Qobuz needs to be in it's own view anyway, not like Clementine, because if we ever get official partner agreement with them, it's a requirement that they are kept separate, and not mixed with a bunch of others. I also think it's a better approach that way. I also want to keep those existing model/views for feature streaming servers and services we might add.
So the question is if we bring back streams and podcasts support, if that also should be like Qobuz and Tidal is, or if it should be mixed like in Clementine.

**Comment by llucps** [comment]
To be honest.. what I really miss is the Podcast support and ideally with Gpodder synchronization as Clementine has.. although it's actually really broken.. but that's another story.

I mean having Gpodder support would be an nice to have.. but I honestly think that the Podcast support as Clementine and VLC should be enough. If having the podcast search functionality is too complicated which would also add more complexity, we might start by just having the possibility to add a podcast, and add episodes to a playlist and play.. that's it, obviously all under one separate tab called Podcast I wouldn't add them mixed like in Clementine.

Does it make sense?

**Comment by rodneyrod** [comment]
I'd be in support of bringing in this feature as an optional plugin if that makes the development and maintenance easier.

**Comment by nazar-pc** [comment]
Yeah, the only internet-related feature I'm really missing is adding podcasts, I had quite a few in Clementine.

**Comment by jonaski** [comment]
Added back "Add stream" now as part of https://github.com/strawberrymusicplayer/strawberry/commit/a2c0e4d4b1c801ea29090e3eb36faefb5b7c0374
