### ISSUE TITLE
Delete from disk

### ISSUE THREAD

**Issue by komodo666** [strawberrymusicplayer/strawberry#284]
Hi, i don't know if it's a feature or a bug.

But i'm missing "Delete from disk" in the right click menu on files in playlist or in collection.

It's working in Clementine and i was using it frequently.

Could you please add this feature ?

Thanks

Martin

**Comment by jonaski** [comment]
I removed it because I didn't like the way it was implemented. It was too easy to accidental delete files. Also, when the menu is in the collection or the playlist, you don't really know what you are removing on disk when you select it from the menu. In my opinion it makes more sense to browse the folder and delete it directly from disk.
I was thinking of bringing it back, but I'd like to have a setting where the user has to explicitly enable it in the settings first, and a better confirmation dialog.

**Comment by komodo666** [comment]
Ok, i understand.
But delete files from browser is annoying, because i need to find path to file first and then delete the file.
So if will be possible to add the option to enable this in the configuration, i am ok with this.

Thanks

**Comment by Obigre** [comment]
> But delete files from browser is annoying, because i need to find path to file first and then delete the file.

Right-click on the file you want to delete > Show in file Browser... > You are in the file directory :)

**Comment by komodo666** [comment]
> > But delete files from browser is annoying, because i need to find path to file first and then delete the file.
> 
> Right-click on the file you want to delete > Show in file browser... > You are in the file directory :)

Thanks for the tip :-) But the solution from jonaski, to enable this feature in the config will be better for me :-)

**Comment by glassfox** [comment]
+1
For me this is showstopper to move from clemantine to strawberry.
As proposal, you able to make this future configurable and disabled by default in Preferences.

**Comment by hoangphucITJP** [comment]
I'd love to have this feature implemented

**Comment by mashiro-tan** [comment]
I'll double @glassfox proposal, that's really disturbing. Moreover, "tick it and open a browser" will be really troublesome if i want to, e.g., remove all 128kbps mp3 files from the collection.

**Comment by jonaski** [comment]
Qt 5.15 will have `QFile::moveToTrash`, see https://wiki.qt.io/New_Features_in_Qt_5.15

**Comment by divisionbyzeroerror** [comment]
So, would allowing a mass delete feature (all selected files in a playlist) that moves them to the Trash be possible if there was a way to easily undo that last operation? Perhaps a type of "toast" popup message that allows a user to undo the action?

**Comment by jonaski** [comment]
I've added the option back. It's possible to enable it both for collection and playlist with individual setting in the respective settings.
But instead of deleting from disk it's moving the trash, so it will show the options if you got Qt 5.15 or higher.
I think that's better since it's safer and the user have the ability to easily restore the files from trash if a mistake is made.
There is a delete confirmation dialog showing the affected files in a listbox too.
The "Delete from disk" in the file browser is always enabled independent of Qt version since it already was there before (it is also much more clear there what files you delete), but will now move files to trash if you got Qt 5.15 or higher, otherwise delete permanently like before. I also changed it to use the new delete confirmation dialog with listed files.
Rolling release distros already have 5.15, and the other ones will have it not to long. Qt 6 will already be out in November. For those that do not have the option yet, there is always the "Show in file browser" and delete from there like pointed out by @Obigre

**Comment by mbnoimi** [comment]
> those that do not have the option yet, there is always the "Show in file browser" and delete from there

"Show in file browser" is useless in this case; I've the recent release (Version 0.8.4) but it still built by Qt version 5.12.8, so I really miss "Delete from disk" (I've migrated from Clementine since 3 days ago)

**Comment by SolarDesalination** [comment]
Hi, would it be possible to reenable the delete option? I'm using the latest version and it's not there :(

**Comment by mbnoimi** [comment]
+100
