### ISSUE TITLE
Suggestions? Mailinglist or forum?

### ISSUE THREAD

**Issue by jonaski** [strawberrymusicplayer/strawberry#290]
I want to create a mailing list or forum for discussions and questions. Any suggestions what we should use?

**Comment by NucleaPeon** [comment]
I found this list while looking around briefly: https://en.wikipedia.org/wiki/List_of_mailing_list_software

The linux kernel uses patchwork in addition to a mailing list (https://lore.kernel.org/patchwork/project/lkml/list/), but I don't know if you want to go in that direction yet. 

I have no dog in this fight, but using something built in python would likely be easier to setup and maintain, though scalability could be an issue later on due to the GIL. I'm also more familiar with python as I work with it on a daily basis.

GNU Mailman ticks the right boxes for me on paper.

**Comment by alekksander** [comment]
i have two suggestions. reddit is probably a fine and easy to maintain place to talk, and google forums are one of the worst forum engines i used

**Comment by v-fox** [comment]
I'm not a fan of either but I really against generic social network-style sites like reddit and mailing lists with their need to register and dump entire things into your client. Something that has threaded messaging and selective notifications but is actually software focused is fine. GitLab maybe ? But that's too development-focused for generic talks.

**Comment by gavinhoward** [comment]
I would prefer a mailing list, but a forum is fine as well.

**Comment by fitojb** [comment]
What about a Discourse instance? It is configurable to behave as a mailing list if so desired by each user.

**Comment by jonaski** [comment]
Forum is available here: https://forum.strawberrymusicplayer.org/
It's NodeBB, the same thing Qt forums uses, very similar to Discourse.
Please test it and see if it works.
It might go a bit up and down in the start in case I need to fix something.
