### ISSUE TITLE
DSD support on Windows

### ISSUE THREAD

**Issue by mluizescu** [strawberrymusicplayer/strawberry#338]
I just installed the latest available version for Windows and it seems that it does not support DSD playback. When I try to load a .dsf file, i get the following error: "File H:/2L-125_stereo-2822k-1b_04.dsf is not recognized as a valid audio file.". Is there any way to make this work?

OS: Windows 10, 1909
Strawberry Version: 0.6.7-47-g31aa42c

**Comment by jonaski** [comment]
Try this one: https://builds.strawberrymusicplayer.org/windows/StrawberrySetup-0.6.8.15.gc4be310-x64.exe

**Comment by mluizescu** [comment]
Thank you for your response. The new version is able to load the files, but it lacks WASAPI support. With DirectSound i get an error when I try to play a DSD file: DirectSoundCreate: The parameter is incorrect.

**Comment by jonaski** [comment]
We can add back WASAPI support when the plugin becomes more stable in GStreamer.
There is no plans to add ASIO support. I know to little about audio on Windows.

**Comment by RomanHargrave** [comment]
@mluizescu Strawberry is built on top of GStreamer, though I believe it is theoretically possible to implement non-GStreamer backends. In order to get straightforward ASIO support, a GStreamer ASIO plugin would need to exist - and from what I can tell, there is no such plugin. 

Also, from what I've read about ASIO there are very few people that would be interested in actually writing software for it. I hear it's not exactly a pleasant API to work with. It seems to be one of those things that sticks around because it came on to the scene at an opportune time and gained momentum.

**Comment by jonaski** [comment]
I just compiled the gst-plugins-bad with the latest changes to the wasapi code, still crashes. This means that it probably will not be fixed in the upcoming gstreamer 1.18 release either.
It usually crashes when stopping and starting playback when you set the output to WASAPI or automatic, if you set the output to directsound everything is fine. It looks like it works better when fading is enabled, that's probably because it doesn't immediately cleanup the pipeline.
Probably need to do a backtrace on it in Windows and report it to GStreamer.

**Comment by mluizescu** [comment]
Thank you for trying! Hope gstreamer gets this fixed, although supporting native DSD doesn't seem to be of much interest for them.

**Comment by jonaski** [comment]
I reopened the original issue for WASAPI. GStreamer isn't capable of playing native DSD yet, see issue https://github.com/strawberrymusicplayer/strawberry/issues/152
