### ISSUE TITLE
Strawberry has glitches while using it on mac

### ISSUE THREAD

**Issue by Master-baker** [strawberrymusicplayer/strawberry#342]
Hi, 
While working with Strawberry 0.6.8 on mac os 10.15.2 (imac 21.5" 4k) the GUI has a lot of glitches, i don't if this has happened with previous version of Strawberry as this is my first time using Strawberry on mac os. For example image 1, i closed a playlist and the placement of the
other playlists did not display correctly until I either create a new playlist or minimize and maximize Strawberry. Image 2, I added a few songs to a playlist and the from the top the playlist does not display correctly, even when scrolling the playlist it causes these glitches. This happens randomly as i work with Strawberry. I also tried running Strawberry in "low resolution" and the same thing happens. Things that remedy the situation is if I change to another playlist and back or minimize and maximize Strawberry until it happens again.

Image 1.
https://imgur.com/ChzI1Qu
Image 2.
https://imgur.com/NgIIClg

Strawberry 0.6.8
Mac OS 10.15.2
iMac 21.5 Retina 4k

**Comment by jonaski** [comment]
It doesn't occur here, macOS 10.14.6 running in VirtualBox.

**Comment by Master-baker** [comment]
> It doesn't occur here, macOS 10.14.6 running in VirtualBox.

At what resolution are you running the mac os in Virtualbox? Strawberry is the only application that is giving me these problems on my mac. I do not know how else to test to determine if it is REALLY a Strawberry issue or the issue is somewhere else. To me it seems as Strawberry struggles to refresh/display the information fast enough and that is why i get the glitches.

**Comment by Master-baker** [comment]
Also are the icons on the left supposed to sit in the middle of the application? All screenshots that i have seen of Strawberry the icons on the left sit at the top. 

https://imgur.com/MjoER5O

**Comment by jonaski** [comment]
It's using 1680 x  1050. It's probably a macOS specific problem, maybe it only occurs with 4K screens. I've never seen this on Linux or Windows, but I've never had 4K screen to test on, but there are so many Linux users by now that if it had been a general problem it would most likely been reported by now.
I think the performance with strawberry on macOS is awful, it runs horrible slow, so it might be related to that. I don't know if that's a general Qt on macOS problem or something wrong in strawberry.
This needs to be debugged with a profiler on macOS by someone with more programming experience on macOS than me. It not likely that it will be fixed unless a macOS developer gets involved.

**Comment by jonaski** [comment]
The icons in the middle on the tab bar isnt normal, they are supposed to be on the top, although I've seen that problem on Fedora too, I don't know what causing it.

**Comment by Master-baker** [comment]
I don't have any programming skills, Only thing I can do is assist you where i can on debugging to try and resolve the issue.

**Comment by jonaski** [comment]
I've removed the macOS bullds, we don't provide releases for macOS. If someone wants to fix this we can re-enable it, I dont have time to fix macOS issues and there isn't any macOS developers involved here.

**Comment by NucleaPeon** [comment]
My coworkers have experienced some odd graphical glitches (such as svgs on a webpage missing some lines), but only on mac retina displays. Other macs or computers don't see the issues they do.

**Comment by llucps** [comment]
Hi,

Yes I was just going to say that. There are small glitches specially on retina displays but nothing really major that I can't live with. And regarding performance I don't see that is that terrible.. actually the starting boot after updating to macOS Catalina has been much better it only takes 3 icon bounces where before it could take 10 or more. What's not that good is the scrolling also specially on retina display, but as @NucleaPeon said on other non-retina displays it works much better.

I'm a bit surprised on frankly a bit disappointed that you've decided to remove the macOS builds, as it was said on the README macOS wasn't supported and experimental, but it's a bit of a bummer for me since I've been using and updating those macOS builds, I really like Strawberry, and from now on I've no other option that just compile it myself in order to keep using Strawbeery which I will.

Would you reconsider the bring back macOS builds? You don't have to support them at all, but let Travis to build them since they work pretty good for the most part.

Thanks for your work anyway.

**Comment by jonaski** [comment]
I decided to provide the macOS builds because there was a lot of request for macOS releases from a lot of users, I've ended up fixing a lot bugs that were specific to macOS only, even though I dont even have a mac, I installed macOS in a virtualbox which just works really slow. In over 2 years this project have been on GitHub there have been only 1 macOS contributor involved and he doesn't have time to maintain it.
The Travis-CI builds worked, but it was a headache because it stopped all the time and I had to manually re-trigger the builds. I've moved to GitHub actions now which works much better, I kept the Travis-CI there just so that it would build for macOS too until now. Generating the dmg didn't work inside of actions, and I didn't figure out why, and I don't have time to do all the stuff necessary to have it upload the dmgs.
At this point I have to limit my time more, so it's better to just keep supporting Linux and Windows since it works really well there. As long as the installeres are there users expect things to work, and I think if we are going to provide something it has to have some quality to it, and I can't guarantee it for macOS.
If just 1 developer wants to contribute and help with macOS specific issues, I'm willing to re-enable it, but as long as it's just me, it's too much work for now.
Maybe it's possible to announce it somewhere that contributors are needed.

**Comment by llucps** [comment]
Hi there,

I totally understand your point, it's just a shame fro my own interest that it won't be available anymore. I really liked it and it's basically the only desktop viable client to use with Airsonic, besides Clementine obviously.

Thanks for your efforts anyway I really appreciated.

**Comment by llucps** [comment]
One last favor I would like to ask you.

These last few days I've been using my own compiled version of Strawberry and I don't know why it eats 40% of my CPU whereas using your builds that didn't happen.

Would it be possible to donwload the latest macOS build, so at least I can continue using it?

Thanks.

**Comment by jonaski** [comment]
Unfortunately I deleted them all

**Comment by jonaski** [comment]
I'll try to set up a forum or mailinglist this weekend and we can announce that we need an macOS maintainer and maybe some volunteers

**Comment by llucps** [comment]
I followed the steps listed on travis.yml which you deleted on this [commit](https://github.com/jonaski/strawberry/commit/853224148f76f1e9ea1ba4857c2d26d04e7019ad#diff-354f30a63fb0907d4ad57269548329e3)

And I have no idea why Strawberry can take up top 30% of CPU when playing a song from an Airsonic connection.. it's bizarre because it worked relatively well with your builds up to 7-8% of CPU.

These are the steps I follow to compile it:

> brew install glib pkgconfig libffi protobuf protobuf-c qt gettext gnutls fftw sqlite chromaprint;
> brew install gstreamer gst-plugins-base gst-plugins-good gst-plugins-bad gst-plugins-ugly gst-libav;
> brew install libcdio libmtp libimobiledevice libplist;
> export Qt5_DIR=/usr/local/opt/qt5/lib/cmake
> export Qt5LinguistTools_DIR=/usr/local/opt/qt5/lib/cmake/Qt5LinguistTools
> export PATH="/usr/local/opt/gettext/bin:$PATH"
> export PKG_CONFIG_PATH=/usr/local/opt/libffi/lib/pkgconfig/:$PKG_CONFIG_PATH
> mkdir build
> cd build
> cmake .. -DUSE_BUNDLE=OFF

These are the results after cmake .. -DSUE_BUNDLE=OFF

```
-- Strawberry Version:
-- Display:  0.6.8-15-gc4be310
-- Package:  0.6.8.15.gc4be310
-- RPM:      0.6.8-2.15.gc4be310
-- PAC:      0.6.8.r15.gc4be310-1
-- Could NOT find ALSA (missing: ALSA_LIBRARY ALSA_INCLUDE_DIR)
-- Checking for module 'dbus-1'
--   No package 'dbus-1' found
-- Checking for module 'libxine'
--   No package 'libxine' found
-- Checking for module 'libvlc'
--   No package 'libvlc' found
-- Checking for module 'phonon4qt5'
--   No package 'phonon4qt5' found
-- Checking for module 'libpulse'
--   No package 'libpulse' found
-- Checking for module 'libgpod-1.0>=0.7.92'
--   No package 'libgpod-1.0' found
-- Checking for module 'libimobiledevice-1.0'
--   Package 'openssl', required by 'libimobiledevice-1.0', not found
-- Using builtin taglib library
-- Checking for module 'singleapplication'
--   No package 'singleapplication' found
-- Checking for module 'libsingleapplication'
--   No package 'libsingleapplication' found
-- Checking for module 'singlecoreapplication'
--   No package 'singlecoreapplication' found
-- Checking for module 'libsinglecoreapplication'
--   No package 'libsinglecoreapplication' found
-- Using builtin SingleApplication and SingleCoreApplication libraries
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)

Building strawberry version: 0.6.8-15-gc4be310

The following components will be built:
   Chromaprint (Tag fetching from Musicbrainz)
   Devices: Audio CD support
   Devices: MTP support
   Engine: GStreamer backend
   Global shortcuts
   Moodbar
   Qobuz support
   Subsonic support
   Tidal support
   Translations

The following components WILL NOT be built:
   ALSA integration (missing alsa)
   D-Bus support (missing D-Bus)
   Devices: GIO device backend (missing Unix or Windows)
   Devices: UDisks2 backend (missing D-Bus support)
   Devices: iPhone, iPod Touch, iPad and Apple TV support (missing libimobiledevice, libgpod)
   Devices: iPod classic support (missing libgpod)
   Engine: Phonon backend (UNSTABLE) (disabled in CMake config)
   Engine: VLC backend (missing libvlc)
   Engine: Xine backend (missing libxine)
   Pulse audio integration (missing libpulse)
   Sparkle integration (missing Sparkle)

-- Configuring done
-- Generating done 
```
As you can see some libraries are missing, but Subsonic support is present.. nevertheless it gets compiled, although I don't know if the poor performance can come from this, but I really doubt it.

Could it be you have changed something in code in your last commits that could affect the performance that much?

Thanks, any help would be appreciated.

**Comment by llucps** [comment]
It seems it could be due poor performance of QT5 on macOS..

https://forum.qt.io/topic/59578/rendering-performance-problems-on-imac-with-retina-5k

**Comment by llucps** [comment]
Hi @jonaski ,

I complied Strawberry again with the latest QT available (5.14.1) on Homebrew and I find out than the poor performance on MacOS goes away if I hide Strawberry. So when the main windows is active and playing a song (it doesn't matter whether playing the song locally or from a Airsonic server) it takes 30% of CPU whereas with Strawberry hidden it takes 4-5%.

I've been thinking that all the problem comes with QT on macOS, and like I said I'm pretty sure this poor performance didn't happen with your builds... so what I wanna do is trying to compile with Strawberry with different QT versions.

Do you remember or know what versions were you using to compile the macOS builds from https://builds.strawbs.org/macos/?

Thanks!

**Comment by jonaski** [comment]
I was using the version from brew at the time, had to be 5.13 or 5.14. I don't think it's related to the Qt version though.

**Comment by llucps** [comment]
Yes, It's got nothing to do with the QT version. I compiled and tried with QT 5.11, 5.12 and 5.15 beta and still bad performance when the window is active at the front.

Oh well it was worth the try, it's just drives me crazy why suddenly of this bad performance when it wasn't that bad before. Could it be MacOS Catalina? I updated the OS way back in October and I don't recall any change.

Just worth to mention that the performance in Clementine is as bad as Strawberry.

Thanks anyway.

**Comment by llucps** [comment]
I think the poor performance could be coming because of Gstreamer.. I found this on Clementine Github issue's https://github.com/clementine-player/Clementine/issues/6030#issuecomment-395385074

Could it be because the Gstreamer version used to compile Strawberry? I see on https://gstreamer.freedesktop.org/data/pkg/osx/ that there was an update on December 5th 2019 and the last Clementine build that worked perfectly was clementine-1.3.1-963-gfb51e7733.dmg which dates from December 16th 2019.

So after spending a few hours, I managed to install Gstreamer 1.16.0, 1.15.2 and even 1.14.4 through Hombrew and the compile Strawberry with each version and still nothing.. the performance is still pretty bad.

I don't know where else to look, apparently is not QT5 or Gstreamer, so what else could it be?

Another think I wanted to try was using VLC as a backend but I don't know how to do it..

Any ideas?

Thanks!

**Comment by NucleaPeon** [comment]
Do you know what qt version the good clementine 1.3.1-... version was built against? If I recall correctly, macOS / OS X apps use static qt libs per/app bundle so if you can find which qt  version it is, you can try compiling it from source and then compiling your clementine/strawberry version with it.

**Comment by jonaski** [comment]
I tried to enable the macOS builds in Travis CI again but it fails:
Looks like something is requiring a newer version of XCode which isn't available on macOS 10.13.

```
swiftlint: A full installation of Xcode.app 10.2 is required to compile
this software. Installing just the Command Line Tools is not sufficient.
Xcode 10.2 cannot be installed on macOS 10.13.
You must upgrade your version of macOS.
Error: swiftlint: An unsatisfied requirement failed this build.
Removing: /usr/local/Cellar/unbound/1.9.6... (57 files, 4.8MB)
Removing: /usr/local/Cellar/webp/1.0.3... (39 files, 2.1MB)
```

**Comment by llucps** [comment]
Would it help you if I download Xcode 10.1 and Command Line Tools (macOS 10.13) ?

Just in case I started to download them for you, I can send you links once they are downloaded.

Ok?

**Comment by jonaski** [comment]
I'm not sure I understand what you mean, xcode is already installed I suppose.
But I fixed it now by removing the brew upgrade step.
You can try the one on https://builds.strawberrymusicplayer.org/macos/ now.

**Comment by jonaski** [comment]
I used GCC to compile in Travis-CI (at least for the last year or so), while the default in macOS is Clang.
Except for that, there is much going on that the only way to really figure out if anything is causing the sluggishness is to use a profiler.
My macOS Vm isn't working anymore so I can't really fix anything, and it's too much hassle for me to set it all up again.

**Comment by jonaski** [comment]
I added some highDPI options that might fix the glitches in the GUI.

**Comment by NucleaPeon** [comment]
@jonaski For reference going forward, I have El Capitan and Snow Leopard on hardware available if you need/want testing on those platforms.

**Comment by llucps** [comment]
YES!!! it works great! It only takes 3% of CPU when playing and with the window active and scrolls fast as well.. Also yes you're right some of the glitches are gone!.

So, we can assume the sluggishness is because of using Clang instead of GCC? If so, I don't mind to compile the builds myself, in case you don't that trouble. But do you know how to compile it with GCC?

Thanks you! I really appreciated.

**Comment by jonaski** [comment]
Install gcc with `brew install gcc`
Remove everything in build and run cmake with:
`CC=gcc CXX=g++ cmake ..`
Or you can try:
`cmake .. -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DCMAKE_CC_COMPILER=/usr/bin/gcc`
But you probably need to change /usr/bin to wherever brew installs gcc.

**Comment by jonaski** [comment]
@NucleaPeon Thanks, but I probably won't have time for the additional work that macOS requires so it should be done by someone else, but at least now it works pretty good according to @llucps 
Looks like the Travis-CI macos builder still has some delay with starting up / timeouts, but I can keep the Travis-CI macos builds active in the macos branch instead of master and just occasionally merge it with master so we can still have the builds active for macOS.

**Comment by llucps** [comment]
I already had gcc installed with hombrew, but I reinstalled it again  just in case, then I checked the location where brew installs gcc and the location is 
```
/usr/local/Cellar/gcc/9.3.0/bin/g++-9
/usr/local/Cellar/gcc/9.3.0/bin/gcc-9
```
with a symlink to
```
/usr/local/bin/g++-9
/usr/local/bin/gcc-9

```
Then I run

`cmake .. -DCMAKE_CC_COMPILER=/usr/local/bin/gcc-9 -DCMAKE_CC_COMPILER=/usr/local/bin/g++-9`

And I get this.. It says g++-9 is broken? but it seems unlikely after reinstalling it.. Just wonder what gcc compiler you use in Travis CI.. I also checked /usr/bin/gcc and /usr/bin/g++ and those are the Apple compilers.. if I use those as -DCMAKE_CC_COMPILER and -DCMAKE_CC_COMPILER then it works and compiles just fine.. but the performance is better than before is nowhere near as good as your builds.

```
-- The CXX compiler identification is unknown
-- Check for working CXX compiler: /usr/local/bin/g++-9
-- Check for working CXX compiler: /usr/local/bin/g++-9 -- broken
CMake Error at /usr/local/Cellar/cmake/3.16.5/share/cmake/Modules/CMakeTestCXXCompiler.cmake:53 (message):
The C++ compiler

/usr/local/bin/g++-9

is not able to compile a simple test program.

It fails with the following output:

Change Dir: /Users/xxxx/projects/strawberry/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_bf9bd/fast && /Library/Developer/CommandLineTools/usr/bin/make -f CMakeFiles/cmTC_bf9bd.dir/build.make CMakeFiles/cmTC_bf9bd.dir/build
Building CXX object CMakeFiles/cmTC_bf9bd.dir/testCXXCompiler.cxx.o
/usr/local/bin/g++-9 -o CMakeFiles/cmTC_bf9bd.dir/testCXXCompiler.cxx.o -c /Users/xxxx/projects/strawberry/build/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
FATAL:/usr/local/Cellar/cctools/855/bin/../libexec/as/x86_64/as: I don't understand 'm' flag!
make[1]: *** [CMakeFiles/cmTC_bf9bd.dir/testCXXCompiler.cxx.o] Error 1
make: *** [cmTC_bf9bd/fast] Error 2

CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
CMakeLists.txt:17 (project)

-- Configuring incomplete, errors occurred!
See also "/Users/xxxx/projects/strawberry/build/CMakeFiles/CMakeOutput.log".
See also "/Users/xxxx/projects/strawberry/build/CMakeFiles/CMakeError.log".
```

Any idea? If not, it's fine I don't want to bother you anymore.. you already helped me a lot.

Thanks
