### ISSUE TITLE
Cache Album Art

### ISSUE THREAD

**Issue by gavinhoward** [strawberrymusicplayer/strawberry#358]
**Is your feature request related to a problem? Please describe.**
One thing that Clementine had that Strawberry does not is caching of album art. This causes Strawberry to reload album art frequently, which does not look great.

**Describe the solution you'd like**
Strawberry caches the album art like Clementine does or some other way.

**Describe alternatives you've considered**
We just figure out how to reduce the amount of reloading.

**Additional context**
I opened this issue to get @jonaski's opinion on whether this would be worth implementing, and if so, how he would like it done.

**Comment by jonaski** [comment]
We use QPixmapCache https://doc.qt.io/qt-5/qpixmapcache.html, but maybe the cache limit is too low?
Clementine uses QNetworkDiskCache too. But there were issues with the album covers being stuck which annoyed me, you manually had to delete the cache file because the cache was not automatically deleted when albums were removed and readded. I've since fixed that, but there still should be a setting to manually clear the cache in case it gets stuck.
You can add the disk cache if you want, but make it an option in the collection setting and the ability to clear the cache from the settings.

**Comment by gavinhoward** [comment]
I think I could do some testing to figure out if increasing the cache size takes care of the problem. (I think it might because my collection is big, with album art for all of my 800+ albums.) If it does, I may just add an option in the `Collection` settings to allow the user to set the cache size.

If it does not work, then I can do the following:

1. Add an option for the user to choose between `QPixmapCache` and `QNetworkDiskCache`.
2. Add an option for the cache size.
3. Add a button in the settings to clear the cache.

If you approve, you can let me know and close this issue. I will then get to work.

**Comment by jonaski** [comment]
I think an optional setting to use disk cache for pixmap cache is a good idea, and QPixmapCache needs to be there anyway.
You can just copy the QNetworkDiskCache parts from Clementine and add settings in collection settings. Just make sure you add the parts that deletes the cache when an album is removed in SongsDeleted() function.
