### ISSUE TITLE
Lyrics not appearing

### ISSUE THREAD

**Issue by kjcole** [strawberrymusicplayer/strawberry#383]
**Unexpected behavior**
Lyrics and artist information (and album covers) not appearing, when streaming [Radio Paradise](http://stream-tx3.radioparadise.com/aac-320).

**Expected behavior**
When streaming [Radio Paradise](http://stream-tx3.radioparadise.com/aac-320), using Clementine, I get both lyrics and artist information.

**System Information:**
 - Operating system: Arch Linux (up to date)
 - Strawberry Version: 0.6.8-1

**Additional context**
This is a brand new install of Strawberry. I had not heard of it before today. I haven't screwed with the configuration beyond setting a directory tree for finding my local music files.

**Comment by jonaski** [comment]
I've fixed the lyrics so it works when metadata is changing. Will push it as a very large commit that also includes better album cover handling for local files outside of the collection and much more.
The stream you point to sends "artist - title" as title in the stream, i've fixed it so it splits it to the relevant artist and title.
Album cover searching is more difficult unless the stream sends "album" tag as part of the stream metadata.
Do you have other streams you can share that you use that I can test with? Maybe they send album as part of the metadata. I don't remember exactly but I think Clementine uses the song title + artist when searching for album covers if album is not present, however it will return to many incorrect results, so I don't want that. However I enabled it how just to test if it works, and it works if I replace album with title.
Very good music on Radio Paradise by the way, I might actually use it.

**Comment by jonaski** [comment]
![image](https://user-images.githubusercontent.com/10343810/79686505-2bf23480-8241-11ea-956c-2e51e4b3102b.png)

**Comment by jonaski** [comment]
On second thought I think Deezer can search for artist songs and return covers, I'll look into it.

**Comment by kjcole** [comment]
> I've fixed the lyrics so it works when metadata is changing. Will push it as a very large commit that also includes better album cover handling for local files outside of the collection and much more.
> The stream you point to sends "artist - title" as title in the stream, i've fixed it so it splits it to the relevant artist and title.
> Album cover searching is more difficult unless the stream sends "album" tag as part of the stream metadata.

Thanks!

> Do you have other streams you can share that you use that I can test with? 
> ...
> Very good music on Radio Paradise by the way, I might actually use it.

Not really any other streams use: As you say, very good music on RP, and so I've never really wanted much else.  (BTW, I'm "ubuntourist" on RP's comments board.)

**Comment by jonaski** [comment]
Fixed as part of https://github.com/strawberrymusicplayer/strawberry/commit/a2c0e4d4b1c801ea29090e3eb36faefb5b7c0374

**Comment by jonaski** [comment]
I've fixed the scrobbler now also to handle streams (basically songs retrieved through the engine metadata has no duration and there was no mechanism in place to handle that until now). Stream songs without a duration will be scrobbled when you either stop playback or switch song.

I also did some changes to the album cover searcher so it will sort the images by the first calculated score and try the 3 best first. (instead of sorting by provider like it did before). In most cases it gets a good match from Deezer which will be sufficient score so it won't try to download more covers in that case, so the searcher will be faster.

It's getting pretty accurate results for both lyrics and albums covers now. Deezer probably works best with songs without an album name. But both providers from Tidal, Deezer and Qobuz can handle songs without an album title now.

I also found that Radio Paradise also has FLAC streams, but they don't have metadata, too bad.
https://radioparadise.com/listen/stream-links
