### ISSUE TITLE
Selecting all songs in my collection and right clicking freezes strawberry

### ISSUE THREAD

**Issue by NucleaPeon** [strawberrymusicplayer/strawberry#392]
**Describe the bug**
Strawberry freezes when using the context menu on thousands of selected items in the collections sidebar

**To Reproduce**
1. Click into the collections sidebar
2. Ctrl+A to select all
3. Right click
4. One cpu core at 100%
5. ????
6. Freeze (tested about a minute of waiting before closing)

**Expected behavior**
The context menu to pop up. It seems to be doing a lot of processing which I think is unneeded. 
In my mind, if multiple items are selected, strawberry should understand that we are selecting multiples and have a right click menu specific for multiple item selection appear immediately, so we can click out of it and cancel the operation easily. If we select an item, *then* we should go full bore with the processing of thousands of artists/albums/songs. Perhaps a box to show loading and a cancel button that can be clicked because otherwise I have to close out strawberry forcefully.

**Screenshots:**
![Screenshot_20200324_142249](https://user-images.githubusercontent.com/1475151/77478469-43bdd080-6ddb-11ea-9e49-be39f67d939a.png)

**System Information:**
 - Operating system: Gentoo amd64, linux [hostname] 4.14.173 #1 SMP PREEMPT Fri Mar 13 13:47:54 PDT 2020 x86_64 Intel(R) Core(TM) i7-2860QM CPU @ 2.50GHz GenuineIntel GNU/Linux
 - Strawberry Version: Version 0.6.8-72-g89d96a3e AND Version 0.6.8-88-gafa8486d

**Comment by jonaski** [comment]
There isn't an easy fix for this with the current model implementation as far as I can think of.
The reason it takes long is that the model uses lazy loading. Meaning it only loads the first node from SQL when the model is reset (on startup and on search) in the grouping (default the artist).
So when your right clicking it loads all the songs that aren't already loaded from SQL. It only loads the songs on right click to determine whether to show the "edit track" option (if a cue track is selected it won't show it), but it is still necessary to do that, and it's impossible to know before loading the rest of the songs how many songs are selected, since the grouping can be by genre for example it will only see a few nodes initially. Even if we move the song loading to when ie. "add to playlist" is selected it will still hang there if too many songs are selected, so that's just moving the problem, not fixing it.
The model could be changed to move away from lazy loading and use the backend for everything, but it would take much longer for the songs to load on startup, we will have to see how that affects a really huge collection. It's also a lot of work, and I don't know if there are other side-effects.
I think it's very rare that someone would add the entire collection to the playlist . In 10 years Clementine have existed I haven't seen any complaint or bug reports on this ever, so I'm a bit resistant to change it.

**Comment by NucleaPeon** [comment]
Hmmmmm, then would it be possible for a right-click to do lazy loading in 'blocks' and if the user clicks outside (which would normally cause the right-click menu to disappear), it would cancel additional loading of blocks? The cursor could be set to a busy cursor to indicate that loading is occurring at that time.

**Comment by jonaski** [comment]
The loading needs to be done in a different thread to solve it, so it needs to be moved to the backend or use a current thread, otherwise it won't work showing a loading indicator or respond to clicks, because the song loading blocks everything until it's finished.
The initial loading/search is done in concurrent threads, but that's one SQL query per reset, that's why it doesn't hang there, and why it works.
But the problem with the lazy loading is that when asking for all the songs under the first node it does it in one SQL query per node, that's the way it's implemented, so that won't work to do in concurrent threads as for as I can see.
I think it has to use the backend, then it can show a loading indicator and doesn't block, and can also be cancelled. But like I said, it's a bit work, basically have to rewrite half of the model.

**Comment by NucleaPeon** [comment]
This is probably the lowest priority of issues you're dealing with right now. In fact, we can ignore it for now. If I'm the only one who's mentioned it for many years of clementine/strawberry development, it's not important enough. I can always try my hand at it if it bothers me enough, so I'll close the ticket. Thanks for the information and context.

**Comment by jonaski** [comment]
I did some testing removing all the lazy loading stuff and changing to loading all songs in the model at startup.
There are both advantages and disadvantages with that approach, it will take longer for the program to start, at least until it is usable, since the model gets loaded with all the songs, this will freeze the program for a while, and that loading needs to be done in the main thread since it's GUI specific. It will also take longer to switch between group by's.
The advantages are that it fixes the problem you have here.
But it also fixes many other problems. There is a problem where the entire model needs to be reset if a song disappears from disk (a song that hasn't been fully loaded in the model so it can't know what nodes to remove), this is probably the most important reason I want to try make it work.
It also fixes problems with thumbnails in the collection getting stuck if you change a cover for a song that hasn't been fully loaded in the collection, since it can't know what to remove in that case.
