### ISSUE TITLE
sndio support

### ISSUE THREAD

**Issue by Menelkir** [strawberrymusicplayer/strawberry#431]
sndio is a small audio and midi framework part of OpenBSD and port to many other systems (such as FreeBSD, Linux, etc).
http://www.sndio.org/

sndio is simple and well documented, and for people that doesn't want to mess up with pulseaudio it's a must.

**Comment by jonaski** [comment]
I actually looked into this 2 years ago because I tried to get strawberry packaged in openbsd. I think I didn't find out how to get the devices listed. There already is a gstreamer plugin.
My email to the openbsd mailing list is here: http://openbsd-archive.7691.n7.nabble.com/NEW-audio-strawberry-td343375.html
I never got a reply, I never bothered looking more into the sndio stuff, but maybe my e-mail was blocked because of my DMARC policy (if the mailinglist does not handle that).
If you are interested I probably still have the openbsd port files here somewhere.
I used to be a user of both freebsd and openbsd 15 years ago. I only use Linux now.

**Comment by Menelkir** [comment]
Yes, it could be useful. Maybe someone in freebsd community can help as well.

**Comment by jonaski** [comment]
I added the openbsd port files here: https://files.jkvinge.net/packages/strawberry/strawberry-openbsd-port.tar.xz
Updated to version 0.6.11
I ran into a problem with it complaining about using gettext, but adding gettext-tools to the LIB_DEPENDS didn't help so I disabled translations.
Clang crashed when compiling the icons resource. It might work on an up-to-date system though.I only have 1 openbsd installation in a VM and it is 2 years old.

**Comment by Menelkir** [comment]
I'm still trying to see if I can manage sndio to work with freebsd build, I'll send a proper diff if I'm able to do that. Otherwise, strawberry works pretty well on freebsd, I'm maintaining the port (I'll update to 0.6.12 in the next days). 
I think this can be closed to get out of your way. Thanks.
