### ISSUE TITLE
(macOS) Weird artifact on selected tab after focusing out of strawberry then back in

### ISSUE THREAD

**Issue by tybug** [strawberrymusicplayer/strawberry#454]
**Describe the bug**
If you click off strawberry to another application, then reselect strawberry, the selected tab at the top will have a strange white space that isn't there normally. It goes away when you hover over it.

**To Reproduce**
* have strawberry focused
* click on any other application
* click back to strawberry

**Expected behavior**
* the artifact should be gone

**Video:**
(I tab in and out here because it's easier, but the steps above reproduce as well)
https://streamable.com/4pkcs8

**System Information:**
- Operating system: mac 10.14.4
- Strawberry Version: 0.6.11

**Comment by jonaski** [comment]
This problem does not occur on Linux or Windows. Looks to be specific to macOS. Maybe @MartinDelille can look into it.
The fancy tabwidget doesn't work correctly on macOS, the icons should not be stretched or centered like that.

**Comment by jonaski** [comment]
What resolution do your screen have?

**Comment by tybug** [comment]
2017 macbook pro 13-inch, so 2560 x 1600.

I checked on another computer (2019 macbook pro 16 inch, so 3072 x 1920) and it still occurs.

**Comment by llucps** [comment]
Yes those artifacts are present on QT for Mac OS but I really didn't bother since are very specific to macOS and I can live with it.

@tybug keep in mind the @jonaski doesn't have a Mac so it's a bit difficult to him to test these macOS specific problems.

**Comment by jonaski** [comment]
Both the "plain sidebar" and the "tabs on top" modes are broken on macOS, they should have text too.

**Comment by llucps** [comment]
Yes, here are some screenshots after your latest commit from yesterday.

![Screenshot 2020-07-13 at 08 34 13](https://user-images.githubusercontent.com/25823659/87278177-1f9a1280-c4e4-11ea-8499-703a7d56bce8.jpg)
![Screenshot 2020-07-13 at 08 34 20](https://user-images.githubusercontent.com/25823659/87278179-2032a900-c4e4-11ea-9adb-84e20e7c0596.jpg)
![Screenshot 2020-07-13 at 08 34 2
![Screenshot 2020-07-13 at 08 35 06](https://user-images.githubusercontent.com/25823659/87278204-2aed3e00-c4e4-11ea-93aa-9b4333ff844f.jpg)
9](https://user-images.githubusercontent.com/25823659/87278180-20cb3f80-c4e4-11ea-8b1d-d7ac6bc463aa.jpg)
![Screenshot 2020-07-13 at 08 34 43](https://user-images.githubusercontent.com/25823659/87278200-2a54a780-c4e4-11ea-914f-e75b07cc55d6.jpg)

**Comment by jonaski** [comment]
Commit https://github.com/strawberrymusicplayer/strawberry/commit/b29387d4098454f9c6ba10edb21be888c4973233 should fix the "plain" and "tabs on top" modes. Check if the artifact is gone too.

**Comment by llucps** [comment]
Yes It's much better, there are some quirks but nothing major though. The only major problem is there is no minimum size  for the tabbar.. so you can end up with something like this:

This the minimum size:

![Screenshot 2020-07-13 at 19 11 27](https://user-images.githubusercontent.com/25823659/87332948-b4305f00-c53c-11ea-909a-24a3fc29700a.jpg)

A little bigger:
![Screenshot 2020-07-13 at 19 05 55](https://user-images.githubusercontent.com/25823659/87332996-c27e7b00-c53c-11ea-9dc8-e67da1ed5f62.jpg)

An before, the minimum was like this:

![Screenshot 2020-07-13 at 19 09 05](https://user-images.githubusercontent.com/25823659/87333041-d4f8b480-c53c-11ea-9a04-d6e47f775578.jpg)

Also whatever you did it also fixed the playlist tab bar where sometimes because of the play icon being too big the tab would look truncated :)

Like this:
![Screenshot 2020-07-13 at 19 09 23](https://user-images.githubusercontent.com/25823659/87332792-6d426980-c53c-11ea-8821-20e4cdbec401.jpg)

Thanks!
