### ISSUE TITLE
Sync to the system volume control

### ISSUE THREAD

**Issue by zlzleking** [strawberrymusicplayer/strawberry#473]
**Is your feature request related to a problem? Please describe.**
I use usb dac with no hardware volume control flag. so when i want to change volume, i need to use software volume control. but when i use strawberry with alsa output, (if turn off volume control option when volume is always maximum) i can't control volume with system volume control widget.

**Describe the solution you'd like**
Make option player's software volume control sync to pulseaudio volume.

**Comment by jonaski** [comment]
This doesn't make much sense. You want to disable the SW volume to use another SW volume?

**Comment by J-J-Chiarella** [comment]
First, thank you for reviving this project.

I think this may be related to a problem I had with Clementine.

Ignore any references to ALSA above. I do not know what the user is talking about or if we have same issue but there is a language issue.

Almost all programs all go like this:

(1) software player volume slider with slider -> (2) pulseaudio master mix with volume slider -> (3) Digital-Audio-Converter chip and along to the speakers

If you open up pavucontrol, then you will see that there is a volume slider for the hardware output (master volume) and also a volume slider for every audio stream originating from a program like VLC or Spotify or Firefox or Clementine/Strawberry.

If you have the VLC window and the pavucontrol windows displayed on your desktop, then you will notice the following. The volume slider within the VLC window and the volume slider for the VLC audio stream in the pavucontrol window move in synchronis. If you manually move the volume slider in VLC's window to 42%, then the volume slider for the VLC audio stream in the pavucontrol window will also move to 42%. If you manually move the volume slider for the VLC audio stream in pavucontrol's window to 60%, then the volume slider inside VLC's window will also move to 60%. They are shared. This is the first step. The second step is when all streams get mixed and go to pulseaudio master. (Assuming flat volume voodoo is left disabled as per the norm and new default.)

Every program of which I know does this.

Clementine, however, does not do this. When you move the volume slider in Clementine's window. the volume slider for Clementine does not move. And vice versa.

The result is that audio played through Clementine/Strawberry goes through two volune sliders abd gets distorted two times before reaching the main master mix for pulseaudio.

(1) audio from Clementine/Strawberry gets software volume control applied to it -> (2) a second software volume control for the Pulseaudio stream from Clementine/Strawberry gets applied to the music -> (3) music gets mixed and/or re-sampled with all other audio streams simultaneously in use if applicable -> (4) final mix goes to DAC with volume control signal from Pulseaudio master volume control -> (5) goes out of DAC and to speakers

The norm for all other programs is this: (1) audio from VLC gets only onesoftware volume control applied to it by moving the GUI slider within VLC or moving the GUI slider for VLC's stream within the pavucontrol window -> (2) music gets mixed and/or re-sampled with all other audio streams simultaneously in use if applicable -> (3) final mix goes to DAC with volume control signal from Pulseaudio master volume control -> (5) goes out of DAC and to speakers

Clementine/Strawberry is not fully integrated with Pulseaudio. As a result, the music goes through two software volume controls that are cascaded, before reaching the master mix and master volume control. Every other program has the music go through only one software volume control before reaching the master mix and master volume control.

(The journey from the Pulseaudio master mix to the DAC chip happens thanks to ALSA, but that is handled completely by lower-level technology unassociated with Clementine/Strawberry.)

Again, thank you for reviving this project.

**Comment by RomanHargrave** [comment]
@J-J-Chiarella If I had to guess, this has to do with how GStreamer (the software that actually does the playing and resampling) handles volume adjustment. It would be possible to "integrate" strawberry with pulseaudio, but it would require bypassing gstreamer in some critical parts. I am, of course, saying this without actually investigating whether or not gstreamer supports this functionality internally. 

If you are concerned about the number of DSP/Resampling stages that your audio passes through, I would posit that there are two ways to truly be certain of your audio's path:

1. Use exclusive output, with GStreamer (strawberry) decoding and feeding audio directly to also. As long as your output device supports the sample size and rate of the source audio, no software resampling (nor hardware, though you'll have to take your DAC manufacturer's word for that) will happen.
2. Use JACK to handle output sharing instead of Pulseaudio (if you need PA support, run PA as a JACK client) and have GStreamer connect to JACK. In this configuration, software resampling will occur but you will have a greater degree of control than with Pulseaudio. Additionally, there will only be two stages of pre-amp volume control - Strawberry/GStreamer and then ALSA.

While it is possible to achieve high quality playback with Pulseaudio, there are far more variables involved (as well as the fact that Pulseaudio may or may not resample your audio regardless of source and sink format - and you won't know). I have used both of the two methods described above, and - on a day-to-day basis - use the second method. 

If you absolutely require bit-perfect playback, you should choose method 1 (direct, exclusive output) and leave Strawberry and ALSA volumes at 100%.

**Comment by J-J-Chiarella** [comment]
@RomanHargrave  I do see what are you saying. Of course, (1) would be the best. At that point, however, I would be more concerned with having a good DAC that allows for generous inter-sample overs (to prevent clipping) and good speakers with flat frequency response.

My only point is that to my experience, no other PulseAudio-integrated player (*even other GStreamer players*) does this. The audio is not going to be perfect, but why add another hoop of digital processing? (Obviously, you don't want to do that.) Anyone who usually controls volumes through a pavucontrol window of various sliders (e.g., someone playing a simple game with sound effects while chosen music player runs simultaneously) must remember to not ever adjust the volume in the Strawberry player window. If not, you will get one slider at 80% and the other at 30% and then you need bump both back up to 100% manually for maximum volume without distortion. I just wanted to make clear that Clementine/Strawberry is the black sheep here. Not Parole, not Kodi, not Firefox, not VLC, not Audacious -- just Clementine/Strawberry. I won't comment on the cluster-fruitcake that is KDE audio and Phonon. Most KDE media players have fallen by the wayside in any case (amarok, kaffeine, etc)

As for suggestion (2), of course JACK is better for latency and directness, but having PulseAudio is really convenient; it works-out-of-the-box for most people and handles multiple streams gracefully.

My point is not about getting perfection. It's about removing bad configurations and unnecessary complications that just degrade the sound. It's fairly simple to fix PulseAudio (just fix config file and lobby the people in charge of the project releases to switch the defaults as done with flat volumes).* I don't know if the same is the case for Strawberry. I thought it could have been a GStreamer thing, but as I said, pretty basic GStreamer video and music players all "get it right."

* To explain what I mean about PulseAudio: PulseAudio defaults to resampling everything to 44.1 kHz, even though 99.99% of all sound cards have been 48 kHz for decades and most digital masters and new content are at some multiples of 48 kHz. This means that content often goes from 48 kHz and gets resampled needlessly to 44.1 kHz and then gets resampled by the sound card back to 48 kHz. (99% of consumer sound cards that claim to handle 44.1 kHz direct as input just resample it in the driver firmware.) The default resampling format speex-float-1 is abysmal. Speex-float-5 is transparent, but computationally expensive for small devices; I give PulseAudio a pass there. But I find it frustrating that a simple setting for resampling makes the sound worse for no good reason. YouTube audio, even if submitted as 44.1 kHz gets resampled to 48 kHz Opus anyway, making the default resampling at 44.1 kHz all the more senseless. The setting over flat volumes is finally going to be settled. Most distros except Debian -- i.e., Fedora, Arch, Ubuntu, etc. -- disabled flat volumes with a patch at every distro release. Now the upstream PulseAudio will switch to that in version 14.0. I could write a book on amateur misunderstandings and odd (to me) lack of priorities in AV in open source. GIMP is decades behind in not supporting CMYK. Only in the past 7 years have video editors got pixel aspect ratios right and color spaces right (after Rec.601 and non-HDTV ceased to be of much relevance). Kodi and VLC still do not have working gapless playback. But, hey, your video player now supports doing a file sync with your remote toaster or chain load videogame emulators in a jukebox. Why this was better than being able to play a symphony or Dark Side of the Moon (properly saved as FLAC or high bitrate Vorbis or Opus) is beyond my understanding.

**Comment by jonaski** [comment]
What you are probably asking for is for Strawberry to adjust the PulseAudio volume directly and synchronize it with the volume control in Strawberry, which is possible to implement. I probably won't implement that, but this is a community project so anyone is free to make a proposal for it.
I don't know where you get all this information from. But your claim or assumption that a program doesn't have a software volume built in because when you adjust the volume control in the program it adjusts the PulseAudio (or ALSA) volume control is very wrong.
We use the gstreamer volume element to control the software volume when the volume control is enabled in the settings, see https://gstreamer.freedesktop.org/documentation/volume/index.html?gi-language=c
This is pretty standard for most music players on Linux. Other gstreamer based music players like Guayadeque and Pragha does the exact same thing looking at the source code, and most other I have tested too. It's not unique for Clementine and Strawberry like you claim.
What is unique with Strawberry is that you can disable the software volume, and unlike Clementine you can play music without resampling, Clementine will always limit to 16 bit.
Most of the programs you referer to are media players or other programs, not music players. For some reason you even mention Firefox.
But it's pretty funny that you even mention VLC in this context. libvlc has a software volume, it's not even optional.
If you got PulseAudio enabled it will adjust the volume there instead of the software volume in VLC, but there is still a software volume in VLC. Testing here without PulseAudio I can adjust the software volume in VLC, without a volume control in ALSA.
Audacious is a low-level music player, it has it's own engine. But I had quick look at the source code, and it looks like it uses D-Bus to control the system volume.
It probably isn't difficult to implement controlling the system volume either through a event handler or dbus. But it's just an esthetical thing, and will only work if there is a software volume in ALSA or PulseAudio. You can adjust the system volume fine directly through a software mixer if you have a software volume control.
I don't use PulseAudio, and my DAC's don't have software volumes, I use fixed inputs on the DACs, so the only place to adjust volume is on the analog amplifier, or by enabling the software volume in Strawberry.

I suggest to use our forum instead for these discussions.

**Comment by RomanHargrave** [comment]
> If you listen to jazz music like me, you pick up a lot of the issues, especially with complex stereo recordings of a band with a drummer hitting the cymbals a lot. After enough distortion, it crosses a line and gives me a headache.

Oh boy, tell me about it. Bandcamp serves track previews as 320k MP3 and the sizzling is unreal. Makes shopping not-so-fun. I usually end up previewing the album on TIDAL. They would save some bandwidth by using Opus, but I think they keep MP3 around to deter folks from ripping.

**Comment by J-J-Chiarella** [comment]
> But your claim or assumption that a program doesn't have a software volume built in because when you adjust the volume control in the program it adjusts the PulseAudio (or ALSA) volume control is very wrong.

I meant that the software volume doesn't act as an additional "hoop." It sounds as if you are saying that the synchronizing of volume sliders means that if someone sets the volume to 60% in the software window, then the volume on the PulseAudio stream moves to 60% and each is an independent volume control and that the resulting volume is 36%. If that is indeed how it works, then I stand corrected, and I am sorry.

> Other gstreamer based music players like Guayadeque and Pragha does the exact same thing looking at the source code, and most other I have tested too. It's not unique for Clementine and Strawberry like you claim.

I have not encountered Pragha, but if as you may be implying, GStreamer music players operate differently from GSreamer audio-video players, then I am simply wrong. I don't mean to impugn any of the choices you made with Strawberry. Clementine let various Pulseaudio bugs sit unaddressed for several years.

> What is unique with Strawberry is that you can disable the software volume, and unlike Clementine you can play music without resampling

I did not know that Strawberry behaved differently on this count. I was operating under the assumption that Clementine's behavior carried over and this was what the bug poster was referring to, but I couldn't be sure what he was describing exactly. In any case, having GUI volume sliders in both the respective media-playing programs and in the virtual mixer for Pulseaudio is good and affords choice to the user. The only problem is when the values do not synchronize and each control independently changes the volume.

> Clementine will always limit to 16 bit.

Lowering the bit depth has negligible effect, and there is nothing that bad about Clementine's behavior here.. At a bit depth at or above 16 bits, even a crude cut off the smaller bits without dithering will not cause audible distortion at all. Properly captured audio with good normalization (not compression normalization) will come in just fine 14 bits. You only need higher bit depth at recording and editing, and remixing, and re-editing. Final mixes above 16 bits are just snake oil. To hear the benefit of those extended bits, you would need to be able to distinguish the sound of a hummingbird's wings flapping next to a jackhammer. Truncation of the bits of audio samples can introduce artifacts and could obscure the music entirely at low levels if no dither is used. Truncation, however, is not the same as resampling. Resampling is when you recreate the underlying sine waves approximately and interpolate the values at the new, different time values (e.g., every 1/44100th of a second to every 1/48000th of a second). In any case, each round of digital volume adjustment can introduce errors by compounded rounding.

> For some reason you even mention Firefox.

Because it uses PulseAudio and plays media. When you play media in the browser there is a GUI volume control that is synchronized with the PulseAudio stream for Firefox's audio. The volumes did not synchronize a few years back. They synchronize now just fine.

> I suggest to use our forum instead for these discussions.

Okay then

**Comment by jonaski** [comment]
I had a second look at this, and @RomanHargrave is correct. libvlc implements synchronization to PA volume control, but gstreamer does not.  This is something that needs to be implemented in gstreamer, not in strawberry. It is not possible to do through d-bus.

**Comment by J-J-Chiarella** [comment]
I don't know how I missed this follow-up. I am sorry about filing the bug again separately. Because this bug was closed, I didn't see it in the list or in a basic search and had forgotten I filed this bug with Strawberry, thinking I had only filed with Clementine back in the day.

I would have mentioned that this isn't (or isn't any longer) the case:

>  libvlc implements synchronization to PA volume control, but gstreamer does not. 

Rhythmbox and totem seem to be fine with this. Maybe that wasn't the case in 2020, but these programs behave as expected. Those being Gnome programs hide functionality and are generally annoying with design guidelines and dialog boxes, but they at least have the volume working as expected, hence why I prefer to use Strawberry.
