### ISSUE TITLE
No support for high-dpi screens on Linux

### ISSUE THREAD

**Issue by starkgate** [strawberrymusicplayer/strawberry#481]
**Describe the bug**
I'm using Linux Mint 20, x64, Xfce with a 4K screen. Strawberry (0.6.13) doesn't seem to acknowledge the system-wide scaling settings I set in the system settings, and I don't see any option in Strawberry's settings to change the font size or scale everything up.

The options in Mint:
![Screenshot_2020-07-15_15-14-16](https://user-images.githubusercontent.com/12874678/87549311-f4fbb580-c6ad-11ea-82d3-32655153ed90.png)
![Screenshot_2020-07-15_15-14-27](https://user-images.githubusercontent.com/12874678/87549317-f5944c00-c6ad-11ea-8988-5925986566ab.png)

How Strawberry looks, in comparison to Thunar:
![Screenshot_2020-07-15_15-10-07](https://user-images.githubusercontent.com/12874678/87548948-7e5eb800-c6ad-11ea-96ac-4fec62b60a86.png)

**Comment by jonaski** [comment]
We already support it through Qt, it is specifically here https://github.com/strawberrymusicplayer/strawberry/blob/master/src/main.cpp#L122
Information here: https://doc.qt.io/qt-5/highdpi.html
Since you use a GTK based desktop you need to use qt5ct to configure font sizes, theme, etc. That's common for all Qt programs on Linux.
For scaling configuration with Qt 5 see: https://wiki.archlinux.org/index.php/HiDPI#Qt_5

**Comment by starkgate** [comment]
Thank you. It doesn't look like I can set a system-wide scaling parameter from qt5ct though.
Running `QT_SCALE_FACTOR=2 strawberry` does work though.
