### ISSUE TITLE
Feature request: Disable all track editing

### ISSUE THREAD

**Issue by BezPowell** [strawberrymusicplayer/strawberry#488]
I wonder whether it would be possible to have a configuration option in Strawberry to disable all track editing and ensure that any operations on files are strictly read-only?

I only use strawberry as a player and do any tag editing via beets or music brainz picard, having such an option would act as a sort of safety net to ensure I don't accidentally screw any tags up. I don't know how entangled any editing functionality is and thus how much work it might be to implement such a feature, but feel it could be useful for others who use the player in a similar fashion.

**Comment by jonaski** [comment]
There is an option in the playlist settings, "enable song metadata inline edition with click", it's disabled by default. Other than that there isn't any editing of tags, or modification of files unless you open the tag editor and press SAVE. If you don't trust players do leave your files untouched I suggest to change the permissions on your files to be read only (that's what I do actually, I keep all my music files owned by root and read only to users unless I want to change them, which I rarely do).

Please use the forum for questions, feature requests or discussion around this. It's general better suited for help and discussion because it's easier to get other users to help answer questions instead of just those who participate in development. As for feature requests, someone can pick it up there if they decide to participate in development, otherwise it results in having hundreds of open issues on GitHub that we don't have the capacity to do anyway.
