### ISSUE TITLE
Contractions ("don't", "can't", etc.) not working in Collection Search

### ISSUE THREAD

**Issue by garuffalo** [strawberrymusicplayer/strawberry#492]
For general technical questions and help with technical issues please use the forum on https://forum.strawberrymusicplayer.org/

**Describe the bug**
Words that are contractions, like "don't", "can't", etc., fail to get any results when searching Collection.

**To Reproduce**
Type a song title, such as "Can't Buy Me Love", by The Beatles in the Collection search field and no results appear. "Buy Me Love", however, will produce results.

**Expected behavior**
A song title, typed verbatim, should yield search results.
Contractions in Clementine, on which Strawberry is based, work perfectly in the Library search field.

**Screenshots:**

**System Information:**
 - Operating system:  Linux Mint 19.3 Cinnamon
 - Strawberry Version: 0.6.13-64-gb6b9b903-bionic

-Hardware
Dell Latitude D630; 2.4Ghz; 8GB RAM
Graphics - Intel Mobile GM965/GL960 Integrated Graphics (driver: i915)

**Additional context**
Tried searching leaving out the apostrophe, but that didn't help.
Searching with words that are contractions does work when searching a playlist.

**Comment by jonaski** [comment]
Try with this fix https://github.com/strawberrymusicplayer/strawberry/commit/dd6e254e4f65a841657c61a023ca5702f5de072a

**Comment by garuffalo** [comment]
Well, the fix seems to work fine for apostrophes. However, it does not seem to work for # ("hash" or "pound sign") as I tried searching for #1 Record, an album by Big Star, and got no results. I tested this in Playlist Search and was successful.

It should be noted, however, that, this same search also failed when I tried it in Clementine Library Search.

Not a deal-breaker, because symbols other than apostrophes are pretty rare in music names, but I thought I'd mention it. Thank you for fixing the apostrophe issue. And thank you for developing Strawberry as an alternative to Clementine. I prefer it in many ways.

**Comment by jonaski** [comment]
I see that some characters like colon, comma and hashtag, etc are ignored. We don't do that in our code so that's probably done by the SQlite itself, there are no SQL errors either for that. The `'` problem was different though, it actually produced a SQL error when sent because it wasn't properly quoted in the query we sent. We use SQlite FTS5 for searching, it is documented here: https://www.sqlite.org/fts5.html, however I don't see anything related to that.

The playlist search is not based on SQL but uses a filter through the model where the data is while the collection is SQL queries directly to the DB.
