### ISSUE TITLE
Fix buildbot PPA builder to only update stable repository on releases (python)

### ISSUE THREAD

**Issue by jonaski** [strawberrymusicplayer/strawberry#494]
The stable PPA is still updated even when INCLUDE_GIT_REVISION is set to OFF.
If someone knows Python and can look into it, the function is MakePPABuilder in https://github.com/strawberrymusicplayer/strawberry-buildbot/blob/master/config/master/strawberry/builders.py
My Python knowledge isn't great.

**Comment by jonaski** [comment]
@NucleaPeon

**Comment by NucleaPeon** [comment]
I set up buildbot on my machine, went through the steps to add a master and builder, but ran into some issues fetching the repo from github. I can try again tonight.

**Comment by jonaski** [comment]
You don't need to install buildbot on your machine, just install docker and docker-compose then follow the instructions in the README: https://github.com/strawberrymusicplayer/strawberry-buildbot
You can remove all distros except one ubuntu in the config so you don't need to build all the workers: https://github.com/strawberrymusicplayer/strawberry-buildbot/blob/master/config/config.json before you run ./update_config.py

**Comment by NucleaPeon** [comment]
A couple things I'm finding:
* Running ./update_config.py the first time on a fresh checkout will fail because config/secret directory isn't created. (Fixed in my fork of strawberry-buildbot)
* I feel that update_config.py should be able to create itself if it doesn't exist. It currently fails if it is missing (deleted)
* When running `docker-compose build` step, even with every distro but ubuntu removed, it will still fetch, say, openSUSE content.(Maybe this is still intended, I haven't looked thoroughly in the code). I updated the config, ran the command and left the it running and my vm disk filled up completely.
I'll track down why it's building all OS's even though I only chose one in config.json.

How much work do you want me to put into this? I see a lot of things I could improve and extra things I could do, such as making strawberry-buildbot its own pip package, etc. I don't mind at all.

**Comment by jonaski** [comment]
opensuse is used by volumes and master, you could change those to the ubuntu distro you need to test on to save space.
It would be great if you could do more work on it, it probably needs it. Only I have worked on it, and my Python skills are very limited.

**Comment by NucleaPeon** [comment]
I'm still working on this issue, I can't get to the point where I can actually test things.

I was able to `docker-compose build` just an ubuntu worker by adding the worker name after the command.
Running `docker-compose up` was confusing because it started bringing in opensuse and other distro downloads, but the downloads were only 30-40Mb large so I left it finish. (I wasn't able to add just the ubuntu worker name to the command and have it run successfully).
Then when running the `docker-compose run` command, I get errors because `/config/secret/github-auth.json` doesn't exist.

It feels like the entire system is tightly coupled and not all assumptions are stated. Does a buildbot config require an `auth` entry to build an ubuntu version? It could be possible to skip the entire auth process if not, I'll keep digging.

**Comment by NucleaPeon** [comment]
I'm also new to docker, which hasn't helped my case.
The buildbot command for checking `INCLUDE_GIT_REVISION` *seems* like it's okay, so I have to wonder if the error is coming from another place. 
I'm looking at `dist/scripts/maketarball.sh.in` and it has the line

    gitrev="@INCLUDE_GIT_REVISION@"
    ...
    if ! [ "$gitrev" = "ON" ]; then

In particular, I'm assuming that @INCLUDE_GIT_REVISION@ is somehow substituted, but I grepped both strawberry-buildbot and strawberry repos for 'gitrev' and it's not pulling up anything outside of `dist/scripts/maketarball.sh.in`.

Would this be the issue? Or is it put in place by something outside those two repos?

**Comment by jonaski** [comment]
The github auth token is for authentication to buildbot through github. You can change auth section in https://github.com/strawberrymusicplayer/strawberry-buildbot/blob/master/config/master/master.cfg.py
I think the only thing you need to do is to replace the auth line that points to util.GitHubAuth with `'auth': util.UserPasswordAuth({"username": "doh!"}),`
Then add a line to roleMatchers like: `RolesFromUsername(roles=["admins"], usernames=["username"]),`
See: http://docs.buildbot.net/current/manual/configuration/www.html

cmake/Version.cmake isn't modified by CMake. The maketarball.sh.in file is processed by CMake and INCLUDE_GIT_REVISION is replaced with the what's set in cmake/Version.cmake in the output file maketarball.sh.
It greps Version.cmake where INCLUDE_GIT_REVISION is set directly so I'm not sure why I think the maketarball script has anything to do with it
I think it has something to do with the setting the variable from the property, util.Interpolate or something.

However I spotted something right now actually, in MakeSourceBuilder it's setting  `git_args["method"] = "fresh"` too.

**Comment by jonaski** [comment]
docker-compose up will still need the master and volumes even if you build only 1 worker.
To make everything use the ubuntu distro, you need to replace the FROM in volumes/Dockerfile and master/Dockerfile. But it's probably easier to just use opensuse, because otherwise you need to fix the commands for installing packages in those dockerfiles, and make sure entrypoint points to the python 3 executable.

**Comment by jonaski** [comment]
If I write:
```
if include_git_revision == ['anything']:
  return f
```
Then it always returns from the function, and never continues independent of what include_git_revision is set to.

if I write the same line with not, then it always continues.

If I simply echo the value set by util.Interpolate, it looks fine:
```
  f.addStep(
    shell.ShellCommand(
      name="echo",
      workdir="source",
      command=["echo", ppa_type, include_git_revision],
      haltOnFailure=True
    )
  )
```

**Comment by jonaski** [comment]
The variable set from util.Interpolate isn't working with the if statement. I'm using a similar if statement in MakeRPMBuilder and that one is working fine.

**Comment by jonaski** [comment]
I've sent an email to the buildbot mailinglist

**Comment by jonaski** [comment]
No answer from the list. Doesn't look like there is much participation or activity on the mailinglist at all, I've been on it for a month.

**Comment by NucleaPeon** [comment]
That's disappointing... Have you thought about filing a ticket on their bugtracker?

I set up a computer as a server for all the dockers and I've built all the images and am doing some logging work around the interpolation.

 I had to add a dummy git repo auth json file to get to that point. Buildbot doesn't seem to let me build, but it might not be a requirement for what I'm doing.

<img width="1378" alt="Screenshot_20200816_222514" src="https://user-images.githubusercontent.com/1475151/90360193-dde31700-e00f-11ea-8a11-1430e348f935.png">

**Comment by jonaski** [comment]
You need to login. And leave all the fields empty.

**Comment by NucleaPeon** [comment]
Went to what I assumed the login button was, at the top right, there was only a "Log in with Github" button. Clicked it and it errored out with a 404 on this url:

https://github.com/login/oauth/authorize?client_id=guest&redirect_uri=https%3A%2F%2Fbuildbot.strawberrymusicplayer.org%2Fauth%2Flogin&response_type=code&scope=user%3Aemail+read%3Aorg&state=redirect%3D%252F

Maybe because I set up placeholder auth credentials?

**Comment by jonaski** [comment]
If you run buildbot locally, I'm not sure OAuth works or not since it needs to redirect to a local IP, that's why I suggested to use username  / password instead using util.UserPasswordAuth(). Did you create an OAth app on your account?

**Comment by NucleaPeon** [comment]
I haven't done anything with OAuth. Are you saying I have to remove the "auth" line in the json file to force buildbot to use a username and password, else it looks in the config json and attempts oauth? I didn't explicitly set anything to use oauth.

I have a thought. 
Maybe the problem is with the command in a list instead of a string. When I try running

    sh -c grep 'some thing' some/path

I get 

    Usage: grep [OPTION]... PATTERNS [FILE]...
    Try 'grep --help' for more information.

When using a list for arguments, it's more portable, but I'm not sure it's capturing things in the right order. I could be wrong, but maybe with something like

    command="""sh -c "grep 'set.*(.*INCLUDE_GIT_REVISION \(.*\).*)' cmake/Version.cmake" """,

If everything else is working but this one thing, that's more the culprit as I'm not seeing any obvious python issues with that block of code.

**Comment by jonaski** [comment]
I don't think you are reading my posts here.
I explained how to use username password authentication here: https://github.com/strawberrymusicplayer/strawberry/issues/494#issuecomment-672983780
You replied that you get "Log in with Github", but you said nothing about following explanation or not.  It's really hard for me to tell  what you have done here. Whether you want to use GitHub login or username/password login.
If you still get "Log in with Github", the configuration is either still set to use GitHub OAuth, or you have not restarted buildbot with docker-compose stop / start.

If you intend to use GitHub Authentication / OAuth, in that case you need to register a OAuth app on your account and put those secrets in config/secret/github-auth.json like this:
```
{
  "clientid": "...", 
  "clientsecret": ".."
}
```

I also explained here https://github.com/strawberrymusicplayer/strawberry/issues/494#issuecomment-674088437 that I have debugged the variable and the if statement and include_git_revision is correctly set to ON or OFF depending on the commit.

This is the command I tested with the last time:

```
  f.addStep(
    steps.SetPropertyFromCommand(
      name="get INCLUDE_GIT_REVISION",
      workdir="source",
      command=["sh", "-c", "sed -n 's/^set(INCLUDE_GIT_REVISION
\\(.*\\))/\\1/p' cmake/Version.cmake"],
      property="git_revision_prop",
      haltOnFailure=True
    )
  )

include_git_revision=util.Interpolate("%(prop:git_revision_prop)s")

```

If I print the include_git_revision variable then it is correctly set to ON or OFF depending on the commit which shows that it is reading the file.
You can change the GitBaseUrl to your own strawberry fork and test commit to it, and you'll see that.

`if include_git_revision == ['anything']:`
is true independent of what include_git_revision is set to, and I literally match it to "anything" and it still returns from the function instead of continuing. The exact opposite is happening if I use a not statement.

Anyway, I thought it was very easy to spot what was wrong with my code. Maybe it isn't after all. I will just comment out the stable ppa builder and uncomment and restart buildbot. So if you want you can just look into the other improvements.

**Comment by NucleaPeon** [comment]
OK, I'll explain all the steps I've gone through.

1. On a newly installed debian machine, I checked out your strawberry-buildbot repo.
2. Ran `./update_config.py` to create the credentials
3. `config.json`: 
```
{
  "linux": {
    "opensuse": ["lp151", "lp152", "tumbleweed"],
    "fedora": ["31", "32", "33"],
    "centos": ["8"],
    "mageia": ["7"],
    "ubuntu": ["bionic", "focal", "groovy"],
    "debian": ["buster", "bullseye"]
  },
 "special_workers": [
    "appimage", "mingw"
  ]
}
```
4. `docker-compose build --no-cache --pull` (I use the docker group so I don't need to run as sudo), took 3 hours to complete
5. `docker-compose up -d`
6. `docker-compose run --entrypoint cat master /persistent-data/master/twistd.log`
     Basically I followed https://github.com/strawberrymusicplayer/strawberry-buildbot
7. Navigate to server:8010 and see this:

<img width="1434" alt="Screenshot_20200826_205013" src="https://user-images.githubusercontent.com/1475151/91382032-a3326900-e7dd-11ea-9002-221c3e3e096e.png">

In buildbot, the only option I have to log in is to use github, which I don't want to use.

Yes, I didn't follow the steps in the comment you mentioned. There wasn't much context and I was confused why you were asking me to set my username to `doh!`. I had to read the buildbot docs to make sense of it. I guess that's expected but it would have been nice to have documentation that allows me to ramp up quickly. For instance, you could have a branch in your strawberry-buildbot, master for login and another for github oauth login (or vice versa). Or in your readme docs you could explain in more detail how to do a local login. 
I don't have a lot of time to spare with full time work and family; I was hoping this would be a quicker issue than it is turning out to be.  I'll continue tomorrow. Thanks for your patience and your help.

> if include_git_revision == ['anything']:

Do you mean `if include_git_revision in ['anything']:`?

**Comment by jonaski** [comment]
"doh!" is the password, it's taken from the example in the buildbot documentation.
Anyway. I've created a test branch in the buildbot repo, use it instead. See:
https://github.com/strawberrymusicplayer/strawberry-buildbot/compare/test
I have successfully ran it here and tested so I know it actually works. As you can see the required changes are minimal. I updated to config to use only one worker.
Explanation on the changes:
1. Sets buildbot URL to http://localhost:8010/
2. Set a local username and password using util.UserPasswordAuth
3. Switches master and volumes to use ubuntu groovy.
4. Only groovy enabled in the config.json.
5. Commented out every line related to source, appimage, MXE and windows builders.

All you need to do:
1. Do docker-compose down (very important because the volumes and master are changed now).
2. You might also want to run all the clean commands as I have written in the README: https://github.com/strawberrymusicplayer/strawberry-buildbot to delete all the containers and start fresh.
3. Do: `sudo docker-compose build` and `sudo docker-compose up` (should be done in under 30 min with only 1 container image).
4. It should be accessible on http://localhost:8010/ with plain username password login, username: admin and password: doh!
5. On the buildbot page there should be only 3 builders with the same ubuntu groovy worker.
6. When you build ppa it will give you an error because the private key file is not accessible, but you can just comment out most of the code in the MakePPABuilder function. Or you can create your own PPA repo with your own key.

**Comment by NucleaPeon** [comment]
I followed your instructions but encountered another issue. I tried it doing a clean, then removing all images, containers and volumes. Still got the same result.

Because I host buildbot on another machine, I have to change the buildbot host config entry to 192.168........:8010. Other than that, I log in just fine but any attempt to build gets me an error mentioning the role. I find this odd, seeing as there's already a config entry that seems to assign the user the `admins` role.

<img width="1290" alt="Screenshot_20200828_092718" src="https://user-images.githubusercontent.com/1475151/91627743-73ff3180-e96e-11ea-9799-7c3d7ae964ed.png">

I looked around via search engine, buildbot docs and stackoverflow, but neither was particularly helpful with the error message. 
I read the tutorial https://docs.buildbot.net/current/tutorial/tour.html?highlight=roles and modified the allowRules list as follows:

    allowRules=[
        #util.AnyControlEndpointMatcher(role="admins", defaultDeny=True),
        util.AnyEndpointMatcher(role="admins"),
    ],

then brought docker `down` (restarted service too), did a `build` and `up` and logged back in. That enabled me to at least run the build, but now I get another error which you mentioned in step 7:

    gpg: directory '/home/buildbot/.gnupg' created
    gpg: keybox '/home/buildbot/.gnupg/pubring.kbx' created
    gpg: can't open '/config/secret/jonas-gpg-private-key': No such file or directory
    gpg: Total number processed: 0
    program finished with exit code 2
    elapsedTime=0.255263

This is good. I'm at the point where I can start really digging into what's going on. Thank you.
 
> "doh!" is the password, it's taken from the example in the buildbot documentation.

Makes sense after reading the documentation; I'm used to json/dict keys being descriptive or ids, not used as a value as well. Having the username as "username" didn't help either. A tuple would have made more sense to me, but as it turns out, buildbot supports a list of tuples for credentials. It's a non-issue so I won't mention it further, was just unfamiliar with it.

**Comment by NucleaPeon** [comment]
I think I kind of understand the problem. 

**You set up the property and Interpolated value here:**

    f.addStep(
        steps.SetPropertyFromCommand(
          name="get INCLUDE_GIT_REVISION",
          workdir="source",
          command=["sh", "-c", "grep 'set.*(.*INCLUDE_GIT_REVISION \(.*\).*)' cmake/Version.cmake"],
          property="include_git_revision",
          haltOnFailure=True
        )
    )
    include_git_revision=util.Interpolate("%(prop:include_git_revision)s")

**Once you set** `include_git_revision` **, you check it immediately to see if it is set.**

    if ppa_type in ['stable'] and not include_git_revision in ['set(INCLUDE_GIT_REVISION OFF)']:

Therein lies the problem. The BuildFactory process in buildbot is just configuring for when the build is run so any attempts to do logic outside of the build steps will fail. Simply put, `include_git_revision` hasn't been run at this point

https://stackoverflow.com/questions/50765296/how-to-convert-buildbot-property-to-string-value

I tried implementing the solution, but the created ExampleBuildStep classes aren't tied into the build, unless I assume, they are added into the build factory and run, but at that point they aren't usable for the check anyway.

What your if statement is actually doing is this:

    if ppa_type in ['stable'] and not Property/Interpolated/BuildObject in [str]:

I wrote a snippet to check:
`python3`

    >>> from buildbot.plugins import steps, util
    >>> a = util.Property("include_git_revision")
    >>> a
    Property(include_git_revision)
    >>> not a in ['set(INCLUDE_GIT_REVISION OFF)']
    False

It's probably returning False because the buildbot objects don't have `__str__()` functions to allow string representations nor comparisons.

Buildbot is based on `twisted`, a python asychronous-capable web server, similar to `tornado`, a python web server that I use for work. It's basically stringing a bunch of callable classes together and running them at build time so your logic to check for the `include_git_revision` line in `Versions.cmake` file needs to be put elsewhere. You might think of subclassing a BuildStep similar to ExampleBuildStep and in the `run()` function, do the check and stop the build there.

I may be able to get around to it eventually, but getting to this point has been exhausting.

**Comment by jonaski** [comment]
Not worth spending for time on, I have just created a shell script and let the buildstep call that instead of dput directly, see https://github.com/strawberrymusicplayer/strawberry-buildbot/commit/568d617365074374b2d9c7686a58a9d7bc8c96a5
You can look into other improvements if you want, it's appreciated.
