### ISSUE TITLE
Search issue

### ISSUE THREAD

**Issue by DOFfactory** [strawberrymusicplayer/strawberry#496]
For general technical questions and help with technical issues please use the forum on https://forum.strawberrymusicplayer.org/

**Describe the bug**
When I search for an artist in the Subsonic tab, I have to type the exact name of the artist, e.g. `Jónsi`, instead of the ASCII format `Jonsi`, which does not yield any result and remains empy

**To Reproduce**
See above

**Expected behavior**
Typing `Jonsi` should list also `Jónsi` as the result

**Screenshots:**

**System Information:**
 - Operating system: Windows 10
 - Strawberry Version: 0.6.13

**Comment by jonaski** [comment]
Close Strawberry and go to C:\Users\%username%\AppData\Local\Strawberry\Strawberry and backup strawberry.db in case this goes wrong.

Go on Tools / Console:

Type the following in the bottom command line, after each command press the enter button and replace the text in the command to enter the next command:

`drop table songs_fts;`

`CREATE VIRTUAL TABLE songs_fts USING fts5(ftstitle, ftsalbum, ftsartist, ftsalbumartist, ftscomposer, ftsperformer, ftsgrouping, ftsgenre, ftscomment, tokenize = "unicode61 remove_diacritics 1");`

`INSERT INTO songs_fts (ROWID, ftstitle, ftsalbum, ftsartist, ftsalbumartist, ftscomposer, ftsperformer, ftsgrouping, ftsgenre, ftscomment) SELECT ROWID, title, album, artist, albumartist, composer, performer, grouping, genre, comment FROM songs;`

Screenshot:

![image](https://user-images.githubusercontent.com/10343810/88925002-455d4080-d274-11ea-9cde-c1e5db4af627.png)

**Comment by DOFfactory** [comment]
Just run the commands, and it did not help:

![image](https://user-images.githubusercontent.com/10846169/88925555-f663db00-d274-11ea-94e3-1a0412cfffb3.png)

I would also kindly ask you not to close this issue before confirming that the bug has been resolved. Thanks.

**Comment by jonaski** [comment]
For Subsonic you need to use subsonic_songs_fts instead of songs_fts. And subsonic_songs instead of songs.
Corrected commands:

`drop table subsonic_songs_fts;`

`CREATE VIRTUAL TABLE subsonic_songs_fts USING fts5(ftstitle, ftsalbum, ftsartist, ftsalbumartist, ftscomposer, ftsperformer, ftsgrouping, ftsgenre, ftscomment, tokenize = "unicode61 remove_diacritics 1");`

`INSERT INTO subsonic_songs_fts (ROWID, ftstitle, ftsalbum, ftsartist, ftsalbumartist, ftscomposer, ftsperformer, ftsgrouping, ftsgenre, ftscomment) SELECT ROWID, title, album, artist, albumartist, composer, performer, grouping, genre, comment FROM subsonic_songs;`

**Comment by DOFfactory** [comment]
Thanks, it works now. Will this be implemented in future versions, or will I need to run this whenever my database is recreated/updated?

**Comment by jonaski** [comment]
You only need to rerun it if you start with a new strawberry.db, if you refresh songs, then it's fine.
I might consider to change it permanently or make an option for it in the settings.

**Comment by DOFfactory** [comment]
Cool, thanks!
