### ISSUE TITLE
"Rescan songs" feature does not work with non indexed files

### ISSUE THREAD

**Issue by glaubersm** [strawberrymusicplayer/strawberry#503]
**Describe the bug**
Sometimes files located in a folder non indexed by Strawberry are present in my playlist, I use an external software (mainly Ex Falso) to edit their tags, then I use "Rescan songs" from context menu to update the edited tags of the files present in my playlist and nothing happens.
I'm not sure if this behavior is intentional or a bug, but would be nice if Strawberry could also update tags in this use case.
Also I noticed that the entry of the context menu is "Rescan song**s**(s)" instead of "Rescan song(s)".

**To Reproduce**
add to your playlist files located in a non indexed folder and do NOT close Strawberry
edit any tag (I edited album name) of the added files with an external software (I used Ex Falso)
go back to Strawberry, select the edited files, right-click, choose "Rescan songs(s)"

**Expected behavior**
tag(s) edited with the external software should be updated

**System Information:**
 - Operating system: Arch Linux
 - Strawberry Version: 0.6.13

**Additional context**
If I follow the same steps with indexed files, the edited tags are updated as expected

**Comment by jonaski** [comment]
Rescan songs will only work for collection songs since those are using a file system watcher while songs added from outside of the collection won't. The rescan option is there because if there is minor edit to a file in external tag editor sometimes the filesystem watcher won't pick that up.
I have fixed the context menu to only show rescan songs if any of the selected songs are part of the collection.

**Comment by jonaski** [comment]
Nevermind. We actually have a function in the playlist to reload songs so we can use that.
