### ISSUE TITLE
False positive error when TIDAL track is unavailable

### ISSUE THREAD

**Issue by tehw0lf** [strawberrymusicplayer/strawberry#505]
When trying to play a song from an album that was removed from TIDAL, the 'host requires authentication' error is thrown. This is a false error, because other available songs work flawlessly.

![example](https://user-images.githubusercontent.com/15650679/89716600-9379ee80-d9ae-11ea-9a14-1379ef941027.jpg)

I did confirm that the song is indeed unavailable by trying to play it in the TIDAL web client, where it was marked as unavailable.

The expected behavior IMO would be that it skips the unavailable song, maybe remove it from the playlist.

Currently it will stop playback completely.

If the TIDAL API actually sends 'requires authentication', then this not a strawberry problem and can be safely closed - I hope we find a workaround though!

I'm running on latest Arch Linux, with strawberry-git.

Great work on the project by the way, it is exactly the player I was looking for!

**Comment by jonaski** [comment]
You can use the option for "Continue to the next item in the playlist if a song is unavailable" in the playlist settings.
I fixed so that songs that aren't marked as "allowStreaming" or "streamReady" won't be included from the API.

**Comment by tehw0lf** [comment]
I'm aware of that and enabled this setting, hence why I opened this issue.

Could it be related to having shuffle all enabled? The TIDAL web client also stops playing upon reaching one of those songs, so I had hoped the error might be catchable.

**Comment by jonaski** [comment]
No, it was treating the error as fatal so it was stopping anyway, fixed now.

**Comment by tehw0lf** [comment]
Great! Thank you very much!

**Comment by jonaski** [comment]
I'm not really sure what we should do with the songs that are not marked as "stream ready" by the API, I changed it to ignore them yesterday, but sometimes it good to know that some songs are instead of showing incomplete albums. It's weird that some songs on an album can't be streamed while others can, it does not make sense at all.
I was listening to a great album by the Billy Talbot Band called "On The Road To Spearfish" from Tidal for a long time because I didn't have it on CD, but the title track "On The Road To Spearfish" could not be streamed from Tidal, I ended up finally buying the album because it was so great, then there was an extra track that I had never heard, it was so weird.

**Comment by tehw0lf** [comment]
Yeah that is a good question. In most cases where I experienced the problem, the whole album is not available. But there are also cases like the screenshot from the first post where it's just single songs.

I think marking them in another color might work, aka visually indicating that they have been / should be there but aren't. (I don't know if the songs actually return though or if TIDAL just 'republishes' the album anew when something changes. What's annoying is that even though you don't modify your playlist, it can stop 'randomly' just because a song is no longer available - which I consider bad design in their own player. It's consistently happening on both web and app player, so having a solution to this in strawberry makes it even more attractive to use.
