### ISSUE TITLE
Coverart is not transferred to iPod with Qt>5.10

### ISSUE THREAD

**Issue by jenskuespert** [strawberrymusicplayer/strawberry#519]
When coyping to an iPod with Qt in a version larger than 5.10 the image is screwed up. Instead of the correct image a standard image with a question-mark is shown.

A work-around could be to write the image to a temporary file and using this to fill the image with itdb_track_set_thumbnails from this file.
<pre>
diff --git a/src/device/gpoddevice.cpp b/src/device/gpoddevice.cpp
index 1bc37f75..10697a2d 100644
--- a/src/device/gpoddevice.cpp
+++ b/src/device/gpoddevice.cpp
@@ -181,7 +181,13 @@ bool GPodDevice::CopyToStorage(const CopyJob &job) {
     bool result = false;
     if (!job.metadata_.image().isNull()) {
 #if (QT_VERSION >= QT_VERSION_CHECK(5, 10, 0))
-      result = itdb_track_set_thumbnails_from_data(track, job.metadata_.image().constBits(), job.metadata_.image().sizeInBytes());
+      // TODO this is just a work-around - constBits/sizeInBytes does not work!
+      const QImage& _i2=job.metadata_.image();
+      const char* n="/tmp/strawberry.png";
+      _i2.save(n);
+      result = itdb_track_set_thumbnails(track, n);
+
+      //result = itdb_track_set_thumbnails_from_data(track, job.metadata_.image().constBits(), job.metadata_.image().sizeInBytes());
       track->has_artwork = 1;
 #else
       result = itdb_track_set_thumbnails_from_data(track, job.metadata_.image().constBits(), job.metadata_.image().byteCount());
</pre>

**Comment by jonaski** [comment]
Can you try:
`result = itdb_track_set_thumbnails_from_data(track, job.metadata_.image().constBits(), static_cast<int>(job.metadata_.image().sizeInBytes()));`

**Comment by jenskuespert** [comment]
I tried:
`result = itdb_track_set_thumbnails_from_data(track, job.metadata_.image().constBits(), static_cast<int>(job.metadata_.image().sizeInBytes()));`
But this didn't changed the misbehaviour...

**Comment by jonaski** [comment]
What does constBits() and sizeInBytes() return?

**Comment by jenskuespert** [comment]
`constBits()`returns a reasonable looking pointer. `sizeInBytes()` returns 360000 for an image of the size 300x300, which seems reasonable, too.

**Comment by jenskuespert** [comment]
Thanks for working on this one.

Could it be, that the cover-images read from the iPod are damaged too? At least, I never a got artwork from the iPod.

Again I created a crude workaround, which I'd like to share...

% diff --git a/src/core/song.cpp b/src/core/song.cpp
index 42696c58..bd75d4b6 100644
--- a/src/core/song.cpp
+++ b/src/core/song.cpp
@@ -18,8 +18,8 @@
  * along with Strawberry.  If not, see <http://www.gnu.org/licenses/>.
  *
  */
-
-#include "config.h"
+ #include "config.h"
+#include <gdk-pixbuf/gdk-pixbuf.h>
 
 #include <algorithm>
 
@@ -68,6 +68,7 @@
 #include "covermanager/albumcoverloader.h"
 #include "tagreadermessages.pb.h"
 
+
 #ifndef USE_SYSTEM_TAGLIB
 using namespace Strawberry_TagLib;
 #endif
@@ -1089,6 +1090,29 @@ void Song::InitFromItdb(const Itdb_Track *track, const QString &prefix) {
   d->skipcount_ = track->skipcount;
   d->lastplayed_ = track->time_played;
 
+  GdkPixbuf* tp=static_cast<GdkPixbuf*>(itdb_track_get_thumbnail(track, -1, -1));
+  if(tp!=nullptr) {
+      GError* ge=nullptr;
+      const char* fnw="/tmp/sb2.png";
+      gboolean res=gdk_pixbuf_save(tp, fnw, "png", &ge, NULL);
+      if(res) {
+        guchar* pix=gdk_pixbuf_get_pixels(tp);
+        int len=gdk_pixbuf_get_byte_length(tp);
+
+        QImage ti;
+        if(ti.load(fnw)) {
+          static auto cnt=0;
+          auto fn=QString::asprintf("/tmp/f_%04d.png", cnt++);
+          auto suc=ti.save(fn);
+          d->image_ = ti;
+        } else {
+	  // TODO report the error?
+        }
+      } else {
+        // TODO what about the error message in ge->message?
+      }
+  }
+
 }
 
 void Song::ToItdb(Itdb_Track *track) const {

Maybe the QTemporaryFile could be of help here, too?

**Comment by jonaski** [comment]
Do a check for itdb_track_has_thumbnails(track) first.
There is also a better way avoiding saving the image to file at all, possible gdk_pixbuf_save_to_buffer() then convert that to a QImage and set it directly to d->image_

I did some more attempts to get my iPod 6th gen working with libgpod, but had no success, seems like it doesn't recognize the itdb after it has been modified by libgpod, so maybe it's because they use 2 different versions of the itdb format or somehting, and it only understands the old. Attempted with rockbox too, but rockbox gets stuck initializing the db
I can not get any covers from itdb working on my 5th gen, with or without rockbox. I could get a cover to show in rockbox from a song where it most likely was reading the cover directly embedded in the FLAC, or in from a JPG file I had copied in manually in the same folder.
I also tried to resize the image to as low as 120 x 120 to see if the resolution was the problem.

Did you try to use QImage::byteCount() instead of sizeInBytes() with Qt > 5.10? QImage::byteCount() is still available with Qt 5 so we could change the ifdef to only use sizeInBytes() with qt 6 instead of saving the image to file.

**Comment by jonaski** [comment]
Try this:
```
  if (itdb_track_has_thumbnails(track)) {
    GdkPixbuf *pixbuf = static_cast<GdkPixbuf*>(itdb_track_get_thumbnail(track, -1, -1));
    if (pixbuf) {
      gchar *buffer = nullptr;
      gsize buffer_size = 0;
      GError *error = nullptr;
      gdk_pixbuf_save_to_buffer(pixbuf, &buffer, &buffer_size, "JPEG", &error, nullptr);
      if (buffer) {
        const QByteArray data = QByteArray::fromRawData(buffer, buffer_size);
        d->image_.loadFromData(data);
        g_free(buffer);
      }
    }
  }
```

**Comment by jonaski** [comment]
In your code you create a leak because you forgot to unref the pixbuf.

**Comment by jenskuespert** [comment]
Thanks for the suggestions and the improvement - I'll look into it.

**Comment by jonaski** [comment]
I was wrong yesterday, it won't work using Song::image, that's only used sort of like a temporary variable for embedded cover loaded by the cover loader and the organizer. The collection won't load the cover from there since it loads the songs directly from the backend (SQL).
I did a new update now where I store the image in a cover cache directory and set it to art_manual, it wil thenl be picked up by the cover loader triggered by the collection model: https://github.com/strawberrymusicplayer/strawberry/commit/81709873bda6348464914a2dfa81fcbfc127c8c8

**Comment by jonaski** [comment]
Can you get itdb_device_get_ipod_info to work in DeviceLister::GuessIconForPath?
For me it returns ITDB_IPOD_MODEL_INVALID for both iPods.

**Comment by jenskuespert** [comment]
> Can you get itdb_device_get_ipod_info to work in
> DeviceLister::GuessIconForPath? For me it returns ITDB_IPOD_MODEL_INVALID
> for both iPods.

For my iPod nano it returns a valid response regarding the model and color.
