### ISSUE TITLE
Renaming Track Filenames on the HDD with Strawberry open will cause that track to disappear

### ISSUE THREAD

**Issue by Tibokan** [strawberrymusicplayer/strawberry#539]
**Describe the bug**
Doing filename operations to track filenames in your Music Collection with Strawberry open will cause that track to disappear until a Strawberry restart.

**To Reproduce**
Rename the filename of a track in your Music Collection and watch it disappear. It will not show up anywhere else in Strawberry, and you will need to restart Strawberry to have it show up again.

Note this seems to be specific to these Music Collection display settings only (using one of the default Music Collection display settings available results in this bug not occurring at all):
![Screen Shot 2020-09-08 at 1 16 21 pm](https://user-images.githubusercontent.com/69946799/92429596-c7c31380-f1d5-11ea-8a92-975ec5d2316e.png)

**Expected behaviour**
The track refreshes its filename in the Music Collection and it is then accessible to use without requiring a Strawberry restart.

**System Information:**
 - Operating system: MacOS 10.13.6
 - Strawberry Version: 0.7.2.90

**Comment by Tibokan** [comment]
This also seems to happen with editing track tags using Strawberry - the track will disappear and not be anywhere in Strawberry until you change the Music Collection display view or restart Strawberry.

**Comment by jonaski** [comment]
I'm working on a huge improvement now to the collection model that will completely fix all of this. The problem now is that the keys used for the container nodes are not unique in all situations. I'm working on a fix that will build the keys from each parent node up to the current node to assure that the keys for the container nodes always will be unique (it's based on the parent grouping).
I realize the collection model is completely flawed when it comes to single groupings like disc and year that are not unique to one album. But the same problems can also occur in situations when you have 2 artists with the same album title. It's really weird that no-one has fixed this before, because it's so obviously broken. The situations where it works is actually when it lazy loads the rest of the nodes through to the song.
And the model mostly works on reset, grouping changes, search because those are done directly through distinct SQL queries (lazy loading) so it's manages to pass without checking the container nodes, but there are problems there too, because we set the keys to 0, when the SQL data is actually -1, and it uses the key to lazy load the rest of the song nodes. For songs that are moved to/from "Various artists", or songs are changed so they are removed/re-added to the model (discovered from disk, etc) that's when it's most problematic.
Moving a single disc from a multi-disc album from a non-compilation to the various artists (or the opposite) frees the container node for the album when it's first deleted, because the key for level 2 (album) is not unique even when they have different parent nodes ("Various Artists" vs "Artist") that's why that is a particular problematic case. My changes will address all of this.

**Comment by jonaski** [comment]
Try with https://github.com/strawberrymusicplayer/strawberry/commit/10303cb9c0b91dc057019f0242398a8a4bb8eb37 when the builds are available.
The changes are huge, but it looks to be working. I also made an unit test that tests all possible different groupings with various songs, but manually testing is needed too after this. It would be nice if you could test it with different collection groupings. Moving songs from/to "Various Artists", rename directories on disk, etc should trigger any potential problems.

**Comment by Tibokan** [comment]
Wow, what an overhaul! Fantastic work again @jonaski 
I've done a fair bit of testing today, primarily added in fresh music and doing a whole bunch of compilation album track re-tagging within Strawberry, with and without compilation tags, and on the whole, it is working exceptionally well, including across different collection views that I specifically alternated through whilst doing this retagging.
The only thing I've picked up on in my testing, is that renaming the non-compilation tagged album name of a V, Various Artists album moved into 'Various artists' first via right click, will cause it to drop it back down to V, Various Artists, that's it.

**Comment by jonaski** [comment]
Renaming a song will lose the "Show in various artists" / "Don't show in various artists" (compilation on/off) flags for those songs, so that's probably what happened. But it will remember it when just editing tags, in Strawberry or from an external editor.
