### ISSUE TITLE
System tray icon hover dialog showing raw HTML code (Linux Mint 20.04/Ubuntu Focal)

### ISSUE THREAD

**Issue by rootwork** [strawberrymusicplayer/strawberry#555]
**Describe the bug**
When I hover over the system tray icon, the dialog box that pops up shows raw HTML code rather than the rendered widget. 

This isn't a huge deal for me because I use the default Mint audio/media widget to control tracks (the musical note in the screenshot below), but I thought I'd report it since it seemed like a bug.

**To Reproduce**
Hover cursor over the Strawberry system tray icon.

**Expected behavior**
Rendered Strawberry widget.

**Screenshots:**
![Screenshot of widget showing raw HTML](https://user-images.githubusercontent.com/79733/95517368-b5bfc680-0975-11eb-8614-638b375fc802.png)

**System Information:**
 - Operating system: Linux Mint 20.04 LTS, which is built on Ubuntu 20.04 Focal Fossa LTS, using Cinnamon desktop.
 - Strawberry Version: 0.7.2

**Additional context**
I also tried changing Theme settings to make sure it wasn't a bug in the theme, but it was present on all of them, including the built-in ones.

**Comment by jonaski** [comment]
I'm aware of this, it should already be fixed in https://github.com/strawberrymusicplayer/strawberry/commit/c30ad2819d3411686b853dd2ed316e8c0fdcdbfb which will be in the next release I plan to do in a few days.
Some desktop environments stopped allowing HTML in the system tray tooltip some time ago. But it still works on others, for example XFCE which I use it still works fine, which is why I still keep it, but exclude other desktop environments like KDE and Cinnamon. But maybe we should just remove it entirely, or make it an option in the settings.
Thanks for sponsoring!

**Comment by rootwork** [comment]
Got it, that makes sense. I'll take a look in the next release.

Thanks for your fast response!

**Comment by rootwork** [comment]
I can confirm that this is fixed in 0.8.1. Thanks!
