### ISSUE TITLE
Bringing Strawberry home: KDE incubator consideration

### ISSUE THREAD

**Issue by nielsvm** [strawberrymusicplayer/strawberry#569]
I've used Strawberry music player over the last couple of months and I'm virtually in love, its past incarnations date back to Amarok 1.4 and many long-term Linux audiophiles wouldn't settle for less.

However, maintaining projects is a lot of work and goes far beyond just software developments, its maintenance of CI, websites, bug triaging, building packages are all labor intensive tasks that are often overseen. I foresee that Strawberry has a huge potential as a project and product, to stand next to KDE's flagship media player [Elisa](https://apps.kde.org/en/elisa) as the more advanced option for us audiophiles - KDE is already home to various "competing" projects and that diversity is well established and embraced. Over the past 15 years, KDE has involved from "a desktop project" to a full free software ecosystem promoting and supporting Qt applications.

Technically speaking, Strawberry's predecessors lost their KDE dependencies for various reasons and for anyone worried that I'm proposing to make it a "KDE only" project technically or culturally, I can assure that the absolute opposite is true. There's no necessity to adopt KF5 libraries or to lessen the multi-platform and multi-desktop focus, to the contrary, by becoming a KDE project, many of these things could actually prosper and further improve as other projects like Krita have thoroughly demonstrated.

The main "*problem to be solved*" here is to guard the project's longer-term future, because I'm worried that this awesome player may fall victim of the same faith its predecessors did: lost of interest or lower exposure to users and thus volunteers contributing. By leveraging some or more of KDE's non-code-library powers such as its marketing channels, CI/GIT infrastructure, its windows/mac builds CI, Windows Store and Apple store publication, its website infrastructure, the Strawberry project could prosper even further going forward.

The benefits of becoming a KDE project, are bulleted here:
https://manifesto.kde.org/benefits.html

The process of enrollment is well described here:
https://community.kde.org/Incubator

The main requirement of Incubator enrollment would probably be to switch away from non-free Github as most other requirements already seem demonstrably met:
https://manifesto.kde.org/

With regards to project governance as a KDE project, the status quo could continue as-is, for further context this blog post is a good read: https://pointieststick.com/2020/10/21/inside-kde-leadership-and-long-term-planning/

If there's interest in looking into this from the current project maintainers and contributors, I can make myself available to help out further on this.

**Comment by jonaski** [comment]
Thanks for the positive feedback.
I'm not sure I want to move the project from GitHub. I got everything set up around GitHub, we also have the GitHub sponsors thing here. I think also GitHub is the best place where it's most likely to get others involved.
Even if I would want to move the project from GitHub, I don't think it will meet the requirements in regard to "Healthy team", I'm the only one actively working on this project, I do most of the work. Only occasionally there is a commit from someone else.
There is no guarantee that other contributors get involved even if we move the project to KDE. Another thing is that there already is 3 other music players in KDE: Amarok, Elisa and JuK. It would make more sense to consider it if someone already involved with KDE gets involved with development in Strawberry.
Strawberry is very popular, and there is a need for more contributors. I think it would be better to announce the need for contributors, make an invitation to participate, perhaps even on a KDE list if that's allowed.
The lack of contributors isn't unique for this project, and certainly isn't because of lack of users. I think it has to do with web/mobile development being more popular, and the fact that streaming services have become much more popular than using a music player. But there is also the issue that there are far too many music players on Linux, you'll see in other music player projects that there is mostly one developer working on them.
