### ISSUE TITLE
Copy to MTP devices fails or hangs on Linux

### ISSUE THREAD

**Issue by breversa** [strawberrymusicplayer/strawberry#588]
**Describe the bug**
I'm unable to reliably copy files to my smartphone connected as an MTP device, using two different methods :
1. Opening the device in the Devices tab fails
2. Drag & dropping files from the playlist to an opened file manager window works but often hangs if an unsupported character in the filenames is encountered.

**To Reproduce**
First case :
1. Plug my smartphone (LG G4 H815) to my computer, and enable MTP transfer. I can browse my phone's content with the file explorer.
2. In Strawberry > Devices tab, double-click the phone to open it
3. Error message : `Erreur lors de la connexion au périphérique MTP mtp://lge_lg-h815_lgh815d243cd89/?busnum=003&devnum=026` (= "Error while connecting the MTP device")

Second case :
1. Plug my smartphone (LG G4 H815) to my computer, and enable MTP transfer. I can browse my phone's content with the file explorer.
2. Select some tracks from the playlist, then drag & drop them into the MTP directory in the file explorer
3. Copy starts fine then hangs indefinitely if any problematic character is encountered (i.e. `:|/\`). Probably linked to https://github.com/strawberrymusicplayer/strawberry/issues/404

**Expected behavior**
First case :
The phone opens in the Devices tab and I can export files to it, hopefully with special characters handling in case the MTP devices doesn't handle them properly.

Second case :
The files are copied to the MTP directory, with a warning or option to modify/ignore the potential problematic characters.

**Screenshots:**

**System Information:**
 - Operating system: Linux Mint 20 Ulyana
 - Strawberry Version: Version 0.8.3

**Additional context**
File manager : Nemo 4.6.5
libmtp9 : 1.1.17-3

If I copy my files using ``adb push``, the problematic files are skipped but the whole process doesn't hang indefinitely.

**Comment by jonaski** [comment]
To copy songs to a MTP compatible phone, the phone must not be mounted, mounting the device will block MTP communication that Strawberry needs to do.
Basically the steps are:
1. Connect your phone.
2. Select "Transfer files" on the phone when a message appears.
3. Doubleclick on the phone in the "devices" in Strawberry to make sure it connects.
4. Use the "Copy to a device" in either collection or playlists to copy songs.

Be patient because MTP is very slow, it is also very sensitive, any accessing of the phone from another application will block it.

Dragging songs from the playlist to MTP location in a file browser will never work, Strawberry does not use the special MTP handling required there, and it is not possible for Strawberry to detect that the destination is a MTP device.

Some of the limitations of MTP on Linux are described here:
https://sourceforge.net/p/libmtp/code/ci/master/tree/README

When test coping a song with special characters, both ":", "\", "/" and "|" in the filename using the "Copy to device", it works here.

**Comment by breversa** [comment]
Ah, that's it. My file manager auto-mounts my phone when I select "Transfer files". If I disable that auto-mount, I'm able to mount the phone via Strawberry.

However :
1. Disabling auto-mount hinders the use of all my USB storage devices, for the benefit of only my phone.
2. Strawberry seem unable to access in SD card inserted into my phone ; I can only copy to the internal storage, which is sadly already limited.

Do you see any way around this ?

Also, what about copying from Strawberry to Android devices using adb, as I've noticed is MUCH faster (although that requires setup on the phone) ?

**Comment by jonaski** [comment]
adb is a command utility, not a library. My guess is that it's not using MTP at all, but I'm not familiar with it.
I agree with you that it would be nice to select the SD for saving instead, but I don't see any method for that in MTP, this is what we use:
http://blackjack.izmiran.ru/doc/libmtp-0.0.18/html/group__tracks.html
Maybe changing the storage settings on the phone can change it, I remember that there are some storage settings where you can select internal memory or SD card for certain things.

Saving files is done by the file manager, and not Strawberry when you drag from the playlist, so it's not possible for Strawberry to rename those files when copying in that case.
