### ISSUE TITLE
When albums are in the "various artists" grouping, song names are often ellided in the collection view

### ISSUE THREAD

**Issue by meyamay** [strawberrymusicplayer/strawberry#591]
The below screenshots feature the same album, but one is under the "various artists" grouping, and the other is still has an albumartist tag of "various artists", but "Don't show in various artists" has been selected in the collection view.

When not in various artists grouping:
![not var art](https://user-images.githubusercontent.com/67524637/99443042-1a543680-28cf-11eb-9236-d042076e8562.png)

When in various artists grouping:
![var art](https://user-images.githubusercontent.com/67524637/99443057-1f18ea80-28cf-11eb-8882-4a749451fe95.png)

While showing which artist worked on which track is helpful, having to resize the collection view to see a song's name seems like it outweighs the benefit of seeing this info. Track artist info is shown in the playlist info after being added, too, where there is usually much more visual room.

**Comment by jonaski** [comment]
This isn't a bug, but is rather user preference. You can use album artist of for example "Paul McCartney" or "Soundtrack" instead of using various artists.
An option could be added to the setting to just song title, but that has to come as a contribution, I don't have time to adjust different things to suit everyones preference.
