### ISSUE TITLE
Flatpak package

### ISSUE THREAD

**Issue by soredake** [strawberrymusicplayer/strawberry#600]
Would be nice to have this player available on flatpak.

**Comment by jonaski** [comment]
We don't intend or want to provide flatpak

**Comment by Calinou** [comment]
> We don't intend or want to provide flatpak

Out of curiosity, is there a rationale for that? Note that you don't *have* to personally support and fix issues arising in a Flatpak if one is created. We just need any upstream contributor to approve of this.

See also [this thread](https://discourse.flathub.org/t/strawberry-flatpak/925) on the Flatpak Discoures.

**Comment by jonaski** [comment]
I rather want users to use strawberry through native Linux packages instead of flatpak or snapcraft. It is faster, more reliable and does have all the problems and restrictions. We got AppImage for those that want to test it without installing anything.
I added strawberry to snapcraft almost a year ago because someone requested it, it was a headache to deal with and caused a ton of bad reviews in the software centers, almost all reviews were because of slowness and restrictions in snapcraft, and strawberry got almost entirely positive reviews everywhere else. Strawberry is still in the snapcraft system since deleting it will cause users to be stuck on a old version, but it is no longer published so no new users get it. I also added a warning dialog on startup that recommends users to switch to a native package.
I don't know much about flatpak, but I know that it also runs in a sandbox environment similar to snapcraft.
Basically some of the issues with the snap were:
- Startup was really slow, normally the program should start in 3 seconds, but it took over 10 seconds and more to start the program the first time using snap.
- Users mounted their music hdds directly to a mountpoint under root (/), so when they tried to find their HDD with their music they were seeing the snap filesystem instead of the real root filesystem where the HDD was mounted.
-  ALSA was a headache to get to work, I basically had to manually build and install alsa-lib with alot of extra configuration inside the snap. Our target audience are users with DAC's that want to play their music to their HiFi, and PulseAudio is definitely not what you want for this. You alsa had to obtain special permission to even use ALSA, which was ridiculous in the first place.
- Most users did not know what they were running strawberry as a snap, they basically just installed it through the software center, so when users were reporting issues it was really hard to help them.
 - Using snap you were stuck with old libraries on a Ubuntu system that is possible the worst Linux system to use as a base.
 - No device support worked because they did not permit use of device access using udisks2 and GIO. You had to manually connect plugs/slots for this to work, which most users did not know how to do in the first place.
- When I tried to get some feedback on the snapcraft forum, or reported something broken, no-one responded.

You say that I don't have to deal with issues related to FlatPak, but how does a user know that they are running strawberry as a flatpak? If something is slow or not working correctly I just don't see them reporting that to FlatPak. My experience is that a lot of our linux users reporting issues are not very technical skilled, they often just install something in the software center without knowing if it's a native package, flatpak or snap.

**Comment by soredake** [comment]
>Startup was really slow

Snap comes in a compressed form, and unpacked at every launch, flatpak comes in unpacked form.

>Using snap you were stuck with old libraries

Flatpak have newer libs, see https://gitlab.com/freedesktop-sdk/freedesktop-sdk

>No device support worked because they did not permit use of device access using udisks2 and GIO. You had to manually connect plugs/slots for this to work, which most users did not know how to do in the first place.

https://github.com/flathub/org.kde.dolphin/blob/3c8e1f4b2d0bebe9d2f4fa252924e48f01f5a26f/org.kde.dolphin.json#L18 and https://github.com/flathub/org.gnome.World.PikaBackup/blob/6a53072292288c8854e168ad563893c75a928924/org.gnome.World.PikaBackup.yml#L26

**Comment by zhoreeq** [comment]
I'm on Debian stable and I wanted to try strawberry.  Too sad nobody has made a flatpak yet. 

Clementine [package](https://github.com/flathub/org.clementine_player.Clementine) exists for a long time already, so a strawberry package seems like a low hanging fruit.
