### ISSUE TITLE
[Context panel] Highlight currently playing song and album in the "Albums" widget

### ISSUE THREAD

**Issue by Cqoicebordel** [strawberrymusicplayer/strawberry#611]
Using 0.8.4 from PPA on Linux x64

In the context panel, in the list of albums, the album of the current song playing should be highlighted (→bolded) and expanded, and the current playing song should be highlighted as well.

**Comment by jonaski** [comment]
The albums in the context is poorly implemented, it was something I originally did in 2012 or 2013 when I was a beginner with Qt, I think it's one of the few things that I haven't improved much since then, so it could use some work.
Adding highlight and expanding it should be pretty easy if you want to try it.

**Comment by Cqoicebordel** [comment]
I've looked at it a bit, but it seems out of my depth :/

**Comment by jonaski** [comment]
OK. I don't have time to prioritize this as it's not a critical issue or bug. I will probably look into redoing some of context albums at a later time.
