### ISSUE TITLE
[pulse->pipewire] Crossfading tracks can cause the next track to not play

### ISSUE THREAD

**Issue by AryToNeX** [strawberrymusicplayer/strawberry#632]
**Describe the bug**
Crossfading between tracks can cause the (next) track to not start playing

**To Reproduce**
1. Ensure that you're outputting to a PulseAudio server and that crossfading between tracks is enabled
2. Play one track
3. Go to the next track

**Expected behavior**
The next track should play just fine.

**System Information:**
 - Operating system: Artix Linux rolling x86_64
 - Strawberry Version: 0.8.5

**Additional context**
Recently switched from PulseAudio to PipeWire. Running Strawberry in a console did not give me enough clues to know the root cause of the problem. The sound system runs fine otherwise (that is, including when Strawberry outputs to it as a JACK client).

**Comment by jonaski** [comment]
I don't think this is a bug in strawberry, the setup needs to be compatible with playing multiple streams simultaneously for the cross-fading to work. It is more likely that there is a configuration issue with pipewire, or that gstreamer does not function well enough yet with pipewire for the cross-fading features to function properly.
Are you using pipewire through alsa pcm? Through a gstreamer plugin, or through alsa, pulseaudio or jack?

**Comment by AryToNeX** [comment]
I am using PipeWire as the audio server; PipeWire-Pulse as a "pulse" server drop in. I already checked and apps can have multiple Pulse streams assigned to them.

**Comment by jonaski** [comment]
@v-fox are you familiar with this problem?

**Comment by v-fox** [comment]
@jonaski Not exactly. But I has been using either JACK or OpenAL->JACK output and not PW's PA emulation. I haven't yet migrated to PW on my main PC with all the music. Been planning to do so recently due to a bunch of recent important fixes but haven't tested strawberry yet. Really recommend to always use git's most recent revision for now.

Also, there is PW's native GStreamer sink/output module, it's quite underbaked yet, glitchy and should not be used. So, first step should be to make sure to manually select OpenAL output (and configure it [like this](https://github.com/strawberrymusicplayer/strawberry/issues/262#issuecomment-756205854)), PA or JACK.

@AryToNeX What exact version and revision of PW is this ? You might want to see `journalctl` output of PW during errors after changing `log.level` (to 4 or higher) in /etc/pipewire/pipewire.conf or otherwise declaring `PIPEWIRE_DEBUG="4"` envvar for `pipewire-media-session`.

**Comment by AryToNeX** [comment]
@v-fox I have PipeWire 0.3.19.

I will try to get the errors, but I am quite sure that `journalctl` does not exist in my distro.

I hope that errors are logged in the syslog; probably I will catch them here, if any.

**Comment by v-fox** [comment]
Might be related to https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/653

**Comment by jonaski** [comment]
There is a new release of pipewire (0.3.21) https://gitlab.freedesktop.org/pipewire/pipewire/-/blob/master/NEWS
I suggest to try that, if that doesn't work, then it's probably better to report this to pipewire, as long as strawberry works through pulseaudio and pipewire acts like a audio server emulation, then it's hard too see how this bug is in strawberry in any case.

**Comment by v-fox** [comment]
Seems to work fine with recent PW snapshot 0.3.21+74~git20210210.0ce6de8f
