### ISSUE TITLE
Feature request: Add Flatpak package and other repositories

### ISSUE THREAD

**Issue by dtantono** [strawberrymusicplayer/strawberry#635]
it will be great to have this app in Flatpak (Linux), Chocolatey (Windows), snapcraft (Linux) and install directly from apt repositories itself.

**Comment by jonaski** [comment]
I'm won't be maintaining more packages than we already have.

**Comment by jonaski** [comment]
This has been answered previously on GitHub if you search the issues, and is also available if you Google.

There is a ongoing progress for over 2 years for getting Strawberry into Debian:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=913079

There is a PPA repository available for Ubuntu. As well as deb packages for all current Debian and Ubuntu releases.

There is a process getting strawberry into chocolatey here:
https://chocolatey.org/packages/strawberrymusicplayer

Strawberry was previously published as a snap but I decided based on negative experience, user feedback and reviews that I no longer want strawberry available as a snap. So I no longer plan on maintaining a snap of strawberry.
The software Center in Ubuntu were full of negative reviews of strawberry, most of the negative reviews were because of technical issues with the snap, and not bugs in strawberry.
Users were also reporting too many issues specific to the snap on GitHub issues for strawberry which takes away valuable time for me that I need to dedicate to development.
I don't think this would change much if someone else were maintaining the snap, as most users just report the issues directly to strawberry anyway, many users just install it from the software center and hardly ever know if it's a snap or not.

I suspect with Flatpak, we will struggle with the same of the same issues as the snap.

**Comment by dtantono** [comment]
the main technical difference between snap and flatpak is Flatpaks can both use libraries included in the package and shared libraries from another Flatpak app and this factor makes flatpak is less bulky than snap package. So, I think you can review it and have you ever considered Microsoft store for Windows?
