### ISSUE TITLE
Strawberry 0.9.1 interface is different 

### ISSUE THREAD

**Issue by gianlucapettinello** [strawberrymusicplayer/strawberry#661]
Upgraded from 0.8.5 to 0.9.1 on arch.
The interface is different and I think it is linked to qt6:
Fusion theme instead o Breeze,
no breeze icons and the rows of the playlist are someway crammed.
Compiling with QT6 disabled fixes the issue

**Comment by jonaski** [comment]
When using strawberry with Qt 6 the plugins need to be Qt 6 based too.
Breeze is provided by KDE, so you need to look into if there is a release of those plugins for Qt 6.
Arch has switched to building with Qt 6 which makes sense since there are no longer open source releases for Qt 5, which means no important bugfixes and security fixes anymore with Qt 5.

**Comment by gianlucapettinello** [comment]
Ok thanks I'll check.
