### ISSUE TITLE
[Feature Requests] Collection view: bigger covers, grid view, advanced grouping by

### ISSUE THREAD

**Issue by therob84** [strawberrymusicplayer/strawberry#662]
**Feature Request:**
Hi, glad to found Strawberry as a good Linux-Player (coming from MusicBee@Windows via Clementine). I like Strawberry until now but do missing some features I am used to - maybe I am just to stupid to find the correct settings. If not I would like to suggest the following 3 feature requests (let me know if I just did not find it):

1. **Bigger cover size** in Collection View (adjustable size?) - now they are that tiny (at least on my HD-Notebook monitor as you can see on screenshot).
2. **Grid view** in Collection View like in Cover Manager (with bigger covers, see screenshot right hand side). It think about something similar to e.g. MusicBee ([Link](https://getmusicbee.com/img/hero_img/mb-hero-interface-min.png)) (see screenshot 2))
3. **advanced "grouping by" options** in Collection View. The closest grouping to my imagination I could achive is depicted in screenshot left hand side: 1.) Year-Album 2.) Interpret.
 **BUT**:
  **3a**) Tha **Interpret name is not visible** at a glance - I have first to click onto the Album what is very annoying. Or a 2-line-view would help (see screenshot 1))?
  **3b**) **before the album name always the year is stated** - although it is already included in the headlines (what should be enough)(see screenshot 1)).
  **3c**) Most Important to me: how I can achieve a **reversed order** (**most recent year-album on top**)? Now iI have to scroll all the way down to find the most recent music (what I usually wants). (not on screenshot)
So all in all: I would like a bigger grid view with most recent albums on top, without grouping by artists, just under a year-headline. You now what I mean?

Maybe a two line layout per album in this view would also be very valueable, togehter with bigger covers. Takes of course more space, but would make it looks nicer and easier to scroll through...

These are my main questions. But the following things also puzzles me:

- What about options for covers also in the playlists (right panel)? (grouped by album)
- Can I add a internet stream URL permanently for a quick access of radio stations anywhere? How? I now using a save playlist for this"
- How I can add a album to the currently playing playlist but shuffled within this album (or within each album if multiple selected)? I tried it with "Playlist"-->"Shuffle"-->"Shuffle tracks in this album" but can't figure out how the above written could be achieved.
- Can I just shuffel selected tracks within a playlist (not all)?
- What is the difference between "Que Track" and "Append to current playlist" - both are sending tracks to the playlist (right panel), right?

Screenshot of current view (left hand side) and mock-up of my ideas (right hand side) see below.

What do you think? Any chance to implement these features?

**In relation to**
forum entry without answers here: https://forum.strawberrymusicplayer.org/topic/183/collection-view-bigger-covers-grid-view-advanced-grouping-by

**Screenshots:**
![grafik](https://user-images.githubusercontent.com/15350793/111068032-47080b80-84c7-11eb-95db-6e5475716552.png)

**System Information:**
 - Operating system: Linux Mint 20.1
 - Strawberry Version: 0.9.1

**Comment by jonaski** [comment]
This is a community project, so whatever change or new feature you want, it needs to come from you. There are no volunteers here to adjust it to your taste.
As for the questions they need to be answered in the forum. But I usually prioritize answering the ones that are related to bug or technical issues.

**Comment by therob84** [comment]
OK, as I can't code myself I thought to bring the community project a bit closer to perfect by only make mentally input.
But it seems that this is not wanted - that's OK. In the Forum obviously nobody wants to participate since 2 months to this topic - seems I am the only person want to get this improved. Has to be OK too.

I had the hope that at least one of this FeatureRequest is maybe a small piece of work which maybe somebody or you could implement without that much work if it is seen as worth a try. Thats not the case - thats OK.

Thanks for reply (and close ;-) ) already after 2h ;-)

**Comment by jonaski** [comment]
You already made your input on the forum.
I put up the feature suggestions category so that users could suggest things, it doesn't mean you'll get an answer, but it means if someone is willing to contribute they can look through it to find something they'd like to do. None is obligated to do these things, or even answer any of it.
GitHub issues isn't a good place to file these, since it doesn't separate technical issues and bugs from "feature requests". It also takes valuable time from developers who can participate in development. Github issues is also difficult to locate answers, so that to many times we have to answer the same questions over again. That's why I created the forum.
There are also too many users wanting something, some even demanding things to be done. Most of it won't be done. Even a large company with many developers would not have resources for that sort of thing.
The grid view with covers thing you mention isn't a small thing to do, since the collection uses a tree view, it has to be completely redone. But it really doesn't matter if it's a small thing or not, someone has to be willing to do it.
I already spend over half of my spare time on open source projects, mostly this. I spend many hours of that time just answering all the technical issues I receive here, in private e-mails and on the forum. Finding something to do, or improve isn't an issue for me.
Since I put this project on GitHub 3 years ago or so ​there have been very little given back in form of contributions. I see this isn't unique for this project, but many open source projects on GitHub and other places.
I decided to move this "feature request" thing away from here so I can focus on development, because I do not have time to answer or deal with all of it. There were too many requesting things. Many users including you do not respect it, even though it's written both in the README and in the issue template. There are even some demanding things that would require almost an entire rewrite of the software.
