### ISSUE TITLE
Won't scrobble album artist to last.fm.

### ISSUE THREAD

**Issue by nrgmilk** [strawberrymusicplayer/strawberry#664]
**Describe the bug**
Won't scrobble album artist.

**To Reproduce and Expected behavior**
Set different name track artist and album artist.

**Expected behavior**
Generally, compilation album's album artist is "Various Artists" or other same name.
But, strawberry scrobbles track artist.

**Screenshots:**
None

**System Information:**
 - Operating system: FreeBSD
 - Strawberry Version: 0.91

**Additional context**
https://www.last.fm/api/show/track.scrobble
albumArtist[i] (Optional) : The album artist - if this differs from the track artist.

Also, Clementine works.

**Comment by jonaski** [comment]
It works here. I just tested now.

Not sure what you mean by "Generally, compilation album's album artist is "Various Artists" or other same name.".
In case you expect it to scrobble a album artist tag with "Various Artists", it won't.
Album artist should never tagged to "Various Artists", that's incorrect usage of album artist, if the album does not have an album artist, it should only be tagged with artist and it's automatically put in "Various Artists" when you group by Album Artist.
If someone happens to tag album artist with Various Artists", it won't use that since it will send bogus data to last.fm, if it did, only album and track would be correct in the data that is sent to last.fm.

In this example the track artist is John Mellencamp and album artist is Bob Dylan:

Without "Prefer album artist when sending scrobbles" checked:

```
albumArtist[0]=Bob Dylan&
album[0]=The 30th Anniversary Concert Celebration&
artist[0]=John Mellencamp&
duration[0]=414&
lang=en&
method=track.scrobble&
timestamp[0]=1616013525&
trackNumber[0]=1&
track[0]=Like A Rolling Stone&
format=json
```

With "Prefer album artist when sending scrobbles" checked:

```
album[0]=The 30th Anniversary Concert Celebration&
artist[0]=Bob Dylan&
duration[0]=414&
lang=en&
method=track.scrobble&
timestamp[0]=1616013978&
trackNumber[0]=1&
track[0]=Like A Rolling Stone&
format=json

```

**Comment by nrgmilk** [comment]
> It works here. I just tested now.
> 
> Not sure what you mean by "Generally, compilation album's album artist is "Various Artists" or other same name.".
> In case you expect it to scrobble a album artist tag with "Various Artists", it won't.
> Album artist should never tagged to "Various Artists", that's incorrect usage of album artist, if the album does not have an album artist, it should only be tagged with artist and it's automatically put in "Various Artists" when you group by Album Artist.
> If someone happens to tag album artist with Various Artists", it won't use that since it will send bogus data to last.fm, if it did, only album and track would be correct in the data that is sent to last.fm.
> 
> In this example the track artist is John Mellencamp and album artist is Bob Dylan:
> 
> Without "Prefer album artist when sending scrobbles" checked:

I heard it for the first time.
However, even if I removed the Album Artist tag or changed the settings, Strawberry did not work as I expected.

Thank you.
