### ISSUE TITLE
Fast seeking resets playback position

### ISSUE THREAD

**Issue by staticssleever668** [strawberrymusicplayer/strawberry#679]
**Describe the bug**
When one seeks too fast through the song (with mouse wheel or arrow keys, but not with mouse dragging the slider), song position resets to the very beginning.

**To Reproduce**
With a long song playing in the background focus the seeker and scroll the mouse wheel forwards or press 'up' and 'right' arrow keys rapidly.
It's also happens when you go forth and back, both with mouse wheel and with keys.

**Expected behavior**
Seek through the song properly.

**System Information:**
 - Operating system: Arch Linux
 - Strawberry Version: 0.9.2-21-g8753782a

**Additional context**
This may sound ridiculous, like, who would even want to seek this fast, but sometimes in long songs when I want to get to specific position, I over-seek and go back. Then song position resets.
Also, when you seek this fast, song position indicator sometimes shows '0:00' even when song position didn't reset.

**Comment by jonaski** [comment]
I realize it's not perfect, but I'm not sure there is an easy fix.
The problem is that you are seeking faster than the slider is updated.
Because the slider is updated using a timer, and isn't immediately set to the seek position.
Maybe the slider could be updated to the seeked position instead of the actual value from the engine.

**Comment by jonaski** [comment]
I don't think I can improve this much I'm afraid.
