### ISSUE TITLE
Multimedia key detection error

### ISSUE THREAD

**Issue by Heny67** [strawberrymusicplayer/strawberry#719]
For technical issues, questions and feature suggestions/requests please use the forum on https://forum.strawberrymusicplayer.org/

Check the Changelog to see if the issue is already fixed:
https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog

If it's fixed, try the latest development build from: https://builds.strawberrymusicplayer.org/

**Describe the bug**
Hi
I'm using strawberry on Ubuntu mate 20.04, but multimedia keyboards don't work. Strawberry does not detect them even in the settings. The keyboard is a Coolermaster deveastador. In linux key settings and clementine it detects multimedia keys but not in strawberry.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots:**

**System Information:**
 - Operating system: Ubuntu mate 20.04
 - Strawberry Version:0.9.3

**Additional context**

**Comment by jonaski** [comment]
If what you mean is that the "Change shortcut" in Settings / Global Shortcuts does not work for the media keys either.
Then another program is capturing the media keys and preventing strawberry from capturing them.
This can happen if a program is using XGrabKey() and does not properly release them.
Because the "Change shortcut" does not filter any specific keys, it accepts all that it receives.
I don't think this is a bug at all.
Try a reboot, and start no other programs than strawberry and check if it works.
Also make sure that the "Use Gnome (GSD) shortcuts when available" is checked in the settings.
But the "Change shortcut" should work independent of what backend is used.

**Comment by Heny67** [comment]
Hi!
Yes, I thought so, but the multimedia keys don't work during playback either. Accept anything other than the multimedia buttons in the settings. When you start the strawberry by standing on the player list and pressing the play button, all that happens is that the letters of the name of the track you want to play will be brighter, but playback will not start. The x11 keys are turned on. 


![kép](https://user-images.githubusercontent.com/80578702/120060455-3c85f880-c058-11eb-8079-6c98117d3d66.png)

**Comment by jonaski** [comment]
Maybe the X11 based global shortcuts could be causing issues on Mate.
I realize now that Mate is using a different interface name, so the standard Gnome SettingsDaemon MediaKeys interface won't register on Mate like it does not Gnome and Cinnamon.
I added native shortcuts for Mate, if you try the newest build from https://builds.strawberrymusicplayer.org/, there should be a additional option to enable mate shortcuts.
Disable X11 and enable Mate in the settings, save the settings, and do a reboot of the machine just in case.

**Comment by Heny67** [comment]
Hi!
That's how it works. Thanks! 
![kép](https://user-images.githubusercontent.com/80578702/120224776-5a17b580-c244-11eb-83bf-daa18171defe.png)
