### ISSUE TITLE
Search function is awkward

### ISSUE THREAD

**Issue by monstro1** [strawberrymusicplayer/strawberry#746]
The search feature doesn't really work the way I think it should. It can't really handle special characters at all (like ' or "). Looking up a song with the word "Don't" in the title brings up no results.

Furthermore, appending the search with a tag like title: or artist: seems to have no effect. If I search for artist:"The Police" it should bring up songs by The Police. Instead, it brings up nothing. If I search artist:The Police (no quotes) then it brings up all songs by The Police, but also a few songs with the word Police in the title and a few songs from an album called "Dream Police."

**Comment by jonaski** [comment]
1. I know about this, that's why there is already work in progress for replacing the entire search with a new one, it already fixes some of the issues you mention, and will probably fix all the issues you mention when I merge it. See: https://github.com/strawberrymusicplayer/strawberry/pull/729
2. The search can behave different based on sqlite and Qt version, there is an issue template here where you are supposed to fill in OS and Strawberry version as a minimum before posting a bug-report.
