### ISSUE TITLE
Subsonic library scan hangs at 99%

### ISSUE THREAD

**Issue by jonascant** [strawberrymusicplayer/strawberry#754]
I am using a nextcloud subsonic server with around 1400 albums. On Clementine, refreshing the library takes a good whie, but works. On Strawberry however it always stops responding at 99% and nothing is added to the library.
I tried different strawberry versions under Linux and Windows 10 with the same result.
Currently i am running Version 0.9.3-358-gfe018ff8.

Are there any logs for the library scan?

**Comment by jonaski** [comment]
Are you using Qt 5 or 6?

**Comment by jonascant** [comment]
Qt 5

**Comment by jonaski** [comment]
So it's probably not the same issue as in https://github.com/strawberrymusicplayer/strawberry/issues/718 then.
I looked into this quite a bit because of that issue, it's very hard to figure out since it works on all the servers I have tested.
If possible, create a temporary account I can use and send it on my e-mail and I can look into it.

**Comment by jonaski** [comment]
It's actually the same bug. Looks to be a HTTP2 issue with Qt, QNetworkReply never finishes.
You can disable HTTP2 in the settings and it should work.
But I've made a workaround to make the network replies timeout after 30 seconds so at least it finishes even if it does not receive all songs, looks to be only 2 http requests that are dropped each time.
I also found a bug where it wasn't loading the authentication method setting correctly.
