### ISSUE TITLE
TagLib warning

### ISSUE THREAD

**Issue by EmmanuelMess** [strawberrymusicplayer/strawberry#757]
I am getting a warning compiling the project:

```
CMake Warning at CMakeLists.txt:537 (message):
  There is a critical bug in TagLib (1.11.1) that can result in corrupt Ogg
  files, see: https://github.com/taglib/taglib/issues/864, please consider
  updating TagLib to the newest version.
```

**Comment by jonaski** [comment]
This is intentional because taglib 1.11.1 is a over 5 years old release with issues, but adding require for 1.12 would mean dropping support for debian and all the debian based distros including ubuntu. Debian is still at taglib 1.11.1, even though version 1.12 has been out for over 1/2 year and is even binary compatible with 1.11.1: https://salsa.debian.org/multimedia-team/taglib

**Comment by EmmanuelMess** [comment]
Could a submodule be added and compiled from there for the project?
