### ISSUE TITLE
Minor UI issue: wrench icon and dropdown arrow overlapping

### ISSUE THREAD

**Issue by foss-** [strawberrymusicplayer/strawberry#796]
**Describe the bug**
Minor UI issue: wrench icon and dropdown arrow overlapping
<img width="516" alt="icon and dropdown arrow" src="https://user-images.githubusercontent.com/5708172/137558832-1bcda6f3-f6d8-4be6-89c9-dcf425122013.png">

**Expected behavior**
Not sure what is expected but the current UI looks wrong.

**System Information:**
 - Operating system: macOS 11.6
 - Strawberry Version: 1.0

**Comment by buckmelanoma** [comment]
I have the same issue on my system (Linux).  It appears to be an issue with scaling because changing the configure icon size to a large enough value gives enough room for each component.

That said, I tried to fix this locally and changing this button mode from QToolButton ::InstantPopup to QToolButton::MenuButtonPopup places the arrow to the right of the button without overlap.  See screenshot.  I'll add a PR as a potential fix.

![Screenshot_20211015_154602](https://user-images.githubusercontent.com/43704682/137562080-fe18925d-f952-4e0d-8043-09fe88c8c771.png)

**Comment by jonaski** [comment]
Hopefully fixed with #797

**Comment by foss-** [comment]
This has returned in main build:
<img width="494" alt="Screenshot 2021-12-01 at 21 59 00" src="https://user-images.githubusercontent.com/5708172/144314984-b5e447b5-ef1f-4601-bd67-86ff725f417b.png">
