### ISSUE TITLE
last.fm offline

### ISSUE THREAD

**Issue by garageman2335** [strawberrymusicplayer/strawberry#871]
**Describe the bug**
When using strawberry offline an error window appears (that steals focus and makes it basically impossible to use computer whilst strawberry is being used offline). The error says can't connect to last.fm, an automatic toggling to offline (cache scrobbles) mode would be useful when there is no connection.

**To Reproduce**
Enable last.fm scrobbling, disconnect internet connection and play music

**System Information:**
 - Operating system:
 - Strawberry Version:

**Comment by jonaski** [comment]
I don't think silently turning it to offline mode is a good idea since it won't inform the user that something is wrong.
You can manually turn off the scrobbler or put it in offline mode yourself when the first error occurs. We need to inform the user and right now there isn't a better way than the error dialog.

**Comment by garageman2335** [comment]
I think a better way to inform the user would be to send a notification (either via the pretty OSD or native notification depending on users settings) instead of having an error window, because it is a low severity error.
