### ISSUE TITLE
Playlists can be corrupted under certain circumstances if collection files are temporarily removed

### ISSUE THREAD

**Issue by Shados** [strawberrymusicplayer/strawberry#907]
**Describe the bug**
Under specific circumstances, playlists can be corrupted, ending up with their songs either in a completely different order, or with a completely different set of songs.

**To Reproduce**
1. Create some playlists.
2. Close Strawberry.
3. Move your collection directory somewhere else.
4. Start Strawberry.
5. Note that the playlists are present but don't list any tracks inside them.
5. Close Strawberry.
6. Move your collection directory back to its original path.
7. Start Strawberry.
8. Note that your playlists now list tracks in them, but either in a completely different order than they originally had, or with a completely different set of tracks.

**Expected behavior**
- In step 5, I would expect the tracks to still be listed, even if only by their absolute file path (with some sort of indicator that the files are missing/not present), albeit obviously they would not be playable.
- In step 8, I would expect the playlists to have the same order and contents as they did at the end of step 1.

**Screenshots:**
N/A

**System Information:**
 - Operating system: NixOS
 - Strawberry Version: 1.0.1, nothing in the changelog for newer versions appears applicable, though

**Additional context**
I ran into this issue in the wild because I have my music collection on a network filesystem, and it was briefly failing to load properly. As you might imagine, I was not terribly impressed at having all my playlists effectively nuked.

I haven't looked at the code, but based on the behaviour I strongly suspect that this issue is related to the fingerprinting logic introduced in #721, as this behaviour would seem pretty inexplicable if the playlists were working purely based on filesystem paths.

**Comment by jonaski** [comment]
This is expected behavior if both "mark disappeared songs unavailable" and "Song fingerprinting and tracking" options are off in the collection settings.
Songs are linked to the collection by database row ID, when these options are off, the songs are deleted from the database once they disappear from disk, the playlists will then point to non-existing row ID's, once the directories are scanned again all songs get assigned a new row ID but the playlists still point to the old row ID's.
