### ISSUE TITLE
Non-latin characters are changed to question mark while saving to PLS playlist.

### ISSUE THREAD

**Issue by kan-ibal** [strawberrymusicplayer/strawberry#931]
**Describe the bug**
Non-latin characters are changed to question mark while saving to PLS playlist. Saving to M3U is done correctly.

**To Reproduce**
1. Song with non-latin character in playlist. 
2. Menu->Playlist->Save playlist->'playlistname'.pls

**Expected behavior**
UTF-8 codepage for characters in saved PLS playlist.

**Screenshots:**
-

**System Information:**
 - Operating system: Gentoo
 - Strawberry Version: 1.0.3

**Additional context**
-

**Comment by jonaski** [comment]
For me all playlists are saved as UTF-8 both with Q 5.15-something and Qt 6 dev. I think it's a QTextStream bug that has been fixed.

**Comment by kan-ibal** [comment]
I have compiled already from git and it behaves the same. I have spotted one more issue, albums with directories and filenames that contain non-latin names does not even show up in collection and files lists.
Example of playlist:
[original playlist](https://github.com/kan-ibal/testfiles/blob/main/test_org.pls)
[saved to m3u](https://github.com/kan-ibal/testfiles/blob/main/test1.m3u)
[saved to pls](https://github.com/kan-ibal/testfiles/blob/main/test2.pls)

**Comment by jonaski** [comment]
Compiled Qt from git? Something else is wrong with your system, perhaps locale settings.

**Comment by jonaski** [comment]
I tested importing and exporting your playlist with Strawberry, it works fine both with Qt 5 and Qt 6 on my machine. This has never been an issue for anyone else either.
KID3 has a setting for overriding the encoding for QTextStream, that's probably why it works.
Strawberry doesn't have such as a setting and always uses the encoding from the system locale settings.
See: https://doc.qt.io/qt-5/qtextcodec.html#codecForLocale and https://doc.qt.io/qt-5/qtextstream.html#setCodec
M3U works because it doesn't use QTextStream
I can't answer why files with non-latin names don't show up, this is the first time I've ever heard that has been a problem with Strawberry. If that was a common problem with Strawberry a lot more users would have reported it by now, so it's most likely a system related issue too.

**Comment by kan-ibal** [comment]
I have been investigating that issue and I find out that I have to start Strawberry with explicit export LANG=en_US.UTF-8 variable. So it looks like that it is specific to system issue indeed.

**Comment by jonaski** [comment]
Try getting support from Gentoo. It might be worth checking if Qt was compiled with ICU, I haven't tested compiling Qt without ICU on Linux (only Windows), so I'm not sure if the locale behave different without ICU.
