### ISSUE TITLE
Versions 1.0.3 and 1.0.4 are crashing on Windows

### ISSUE THREAD

**Issue by awvalenti** [strawberrymusicplayer/strawberry#944]
**Describe the bug**
On Windows, crashes almost every time it tries to open a song, exiting without any message. When it doesn't at first, it does after trying to advance to next song (either by waiting or by pressing "Next track" button or fast-forward key on keyboard)

*NOTE*: If opened via command-line, it displays `Illegal instruction` and returns error code `132`.

Version 1.0.2 doesn't seem to have this issue.

**To Reproduce**
Install version 1.0.3 or 1.0.4 on Windows, either MSVC or MinGW
Open a song or, preferably, a folder or list of songs

**Expected behavior**
Should play correctly

**Screenshots:**
N/A

**System Information:**
 - Operating system: Windows 10 Pro 21H2, 19044.1645, Windows Feature Experience Pack 120.2212.4170.0
 - Strawberry Version: 1.0.3 and 1.0.4

**Additional context**
N/A

**Comment by jonaski** [comment]
I can't reproduce any crashes.
There isn't much code changes in Strawberry that could cause something like that between version 1.0.2 and 1.0.4. But a lot of libraries were upgraded, some gstreamer plugins added, it's most likely caused by a library.
What audio file format are you playing?
What CPU are you using?
Does the Windows application log show any information about the crash? (very rare if it doesn't) (Administrative Tools / Event Viewer / Application). It usually gives a good indicator of what library is causing the crash

**Comment by awvalenti** [comment]
It happens for any file type: mp3, flac, aac. It now occurred more frequently when opening a whole folder, especially with more than one song.

My CPU is Intel i7-3770K.

I found a log about the crash, it happened on library `fftw3.dll`. Proably the only useful information besides that is the following. Please tell me if you need more.

```
Problem signature:
P1: strawberry.exe
P2: 1.0.4.0
P3: 6252d4ce
P4: fftw3.dll
P5: 0.0.0.0
P6: 6252002e
P7: c000001d
P8: 000000000003887e
P9: 
P10: 
```

**Comment by jonaski** [comment]
The only thing using fftw is the moodbar, do you have the moodbar enabled? Try turning it off.

**Comment by awvalenti** [comment]
Yes, when I turn moodbar off, it doesn't crash anymore. By the way, after
testing that, it even started working more often even after turning it on
again.

Maybe it's some cache with out-of-date data? Can I clean moodbar data
somehow? It's not checked to store data on music folder.
<https://about.me/awvalenti?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=edit_panel&utm_content=thumb>
André Willik Valenti (ele/dele | he/him)
about.me/awvalenti
<https://about.me/awvalenti?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=edit_panel&utm_content=thumb>


Em ter., 3 de mai. de 2022 às 18:33, Jonas Kvinge ***@***.***>
escreveu:

**Comment by jonaski** [comment]
The moodbar cache is in `%localappdata%\Strawberry\Strawberry\cache\moodbar`, you can safely delete that folder and the it will regenerate the moodbars.

I see that the Intel i7-3770K CPU does not support AVX2. At least the fftw3 library for the MSVC release is compiled with AVX2. I think it's the same for the MinGW release.
But I thought that fftw would detect whether the CPU supports it at runtime, but I'm not sure.
At least Illegal instruction probably means it's trying to use one of the features the CPU does not support, and it looks like your CPU supports everything but AVX2.
So either it's a bug in fftw3, or I might need to disable compiling with AVX2.
When running Strawberry MSVC in debug I can see the following output when generating moodbars, so that looks to me like it's supposed to detect the CPU features at runtime.

```
CPU info (x86-64):
  CMOV ....... Y
  MMX ........ Y
  SSE ........ Y
  SSE2 ....... Y
  SSE3 ....... Y
  SSSE3 ...... Y
  SSE41 ...... Y
  SSE42 ...... Y
  AVX ........ Y
  FMA ........ Y
  AVX2 ....... Y
  AVX OS sup . Y
```

**Comment by jonaski** [comment]
Finally got my hands on an older computer with Windows 10 and I can confirm the issue:

```
Faulting application name: strawberry.exe, version: 1.0.4.0, time stamp: 0x6252d4ce
Faulting module name: fftw3.dll, version: 0.0.0.0, time stamp: 0x6252002e
Exception code: 0xc000001d
Fault offset: 0x000000000003887e
Faulting process id: 0xefc
Faulting application start time: 0x01d86b459e4eee54
Faulting application path: C:\Program Files\Strawberry Music Player\strawberry.exe
Faulting module path: C:\Program Files\Strawberry Music Player\fftw3.dll
Report Id: a0058b61-6f65-4724-ab71-4c164d0176b4
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by jonaski** [comment]
Compiling fftw without AVX2 fixes the problem.
