### ISSUE TITLE
Saving a playlist with relative paths uses non-portable relative paths.

### ISSUE THREAD

**Issue by Ferroin** [strawberrymusicplayer/strawberry#955]
**Describe the bug**

When saving a playlist using relative paths, the saved paths consist of a series of `../` components long enough to get to the volume root, followed by an absolute path. This results in saved playlists being non-portable because they functionally just contain excessively long non-canonical absolute paths.

**To Reproduce**

Save a playlist using relative paths.

**Expected behavior**

Relative paths in saved playlists should be the shortest possible relative paths that point to the songs correctly relative to the playlist file itself.

For example, if the playlist is saved in directory `/foo` as `bar.m3u`, and all the songs it contains are also in directory `/foo`, then a relative path to each song should start with `./`, followed by the path under `/foo` to that song, instead of starting with `../foo/`.

**Screenshots:**

n/a

**System Information:**
 - Operating system: Linux (Gentoo ~amd64)
 - Strawberry Version: 1.0.4

**Additional context**

Aside from the resulting playlists being non-portable, this behavior is inconsistent with other media player software. Saving an otherwise identical playlist in VLC, for example, sanely uses the shortest possible relative path to each song.

**Comment by jonaski** [comment]
Saving with relative paths works as expected here, except it doesn't prefix the filenames with `./` when the playlist is saved in the same directory as the songs.

**Comment by Ferroin** [comment]
> Saving with relative paths works as expected here, except it doesn't prefix the filenames with `./` when the playlist is saved in the same directory as the songs.

Expected by who though?

The norm in most software when you talk about relative paths involves eliminating the longest shared prefix from the absolute paths involved. So for example, if you’re creating a relative path from `/a/b/c/d` to `/a/b/e/f`, the norm in most software would be `../../e/f`, but what I’ve been seeing in Strawberry, no matter _where_ I save the playlist, always ends up being the equivalent of generating `../../../../a/b/c/d` in that situation.

Expected behavior from my perspective would be:

- A playlist in `/foo`, containing the song `/foo/bar.mp3`, would store the path as either `./bar.mp3` _or_ `bar.mp3` (with no slashes in the path).
- A playlist in `/foo`, containing the song `/foo/bar/baz.mp3`, would store the path as `./bar/baz.mp3` _or_ `bar/baz.mp3` (with an implied `./`).
- A playlist in `/foo/quoz`, containing the song `/foo/bar/baz.mp3`, would store the path as `../bar/baz.mp3`

VLC (used as an example here because I know for certain it behaves this way) behaves exactly as described above for at least the first and second cases (those are what I personally care about anyway).

However, when saving a playlist using Strawberry, in the first case I see `../foo/bar.mp3`, and in the second and third cases I see `../../foo/bar/baz.mp3`.

---

To expand a bit on my use case here:

I have my music collection organized on-disk in a directory per album all in one master directory, with the playlists stored in that master directory alongside the album directories, which I synchronize from my computer to my phone _and_ share between Linux and Windows. My expectation here is that a playlist I write out on Linux is usable on both Windows and my phone with no modification, and one written on Windows is usable on both Linux and my phone with no modification.

Currently, however, Strawberry simply cannot do this. No matter which OS I save the playlist from, I need to do some post-processing to make it usable elsewhere (I can easily do this, but it’s a serious pain in the arse, especially since Strawberry _loads_ the postprocessed playlist correctly on both platforms).

**Comment by poikilos** [comment]
@Ferroin Another use case for what you describe is mobile, and I agree that is the expectation. For that, prepending "./" being optional is ideal, since some mobile players require it and some are like your use case and require "./" to *not* be there (such as Pi Music Player which I use). For now I have to use my own script `pip install https://github.com/poikilos/DigitalMusicMC/archive/refs/heads/main.zip` (provides the transfer-playlist command).

**Comment by jonaski** [comment]
@Ferroin 

> 
> Expected by who though?
> 

How relative paths is expected to work. Exactly like you described "Expected behavior" (but without ./).
For me it works both on Linux and Windows, I tested both xspf and m3u.

What playlist format did you try?
What filesystem do you use?
What version of Qt?

Your a developer, I suggest that  you debug this yourself since your the only one having this problem.

The code is here: https://github.com/strawberrymusicplayer/strawberry/blob/master/src/playlistparsers/parserbase.cpp#L111

We use `QDir::relativeFilePath()`

https://doc.qt.io/qt-6/qdir.html#relativeFilePath

**Comment by Ferroin** [comment]
> What playlist format did you try?

M3U and XSPF as well, have not tested with other formats.

> What filesystem do you use?

NTFS (using NTFS-3G on Linux).

> What version of Qt?

Qt 5.15.3

> Your a developer, I suggest that you debug this yourself since your the only one having this problem.

I had not (yet) had the time to dig into this any further, but plan to try and do so today, though I don’t know that I’ll be able to dig any further than figuring out whether this is a bug in Qt or in Strawberry itself (low-level debugging of C/C++ code is unfortunately not something I’m any good with).

**Comment by Ferroin** [comment]
OK, digging further, it looks like this was a result of me missing something in the path listing in the playlist save dialog. Sorry about any wasted time from this (and rather embarrassed that it took me digging through the code and poking around with QDir in Python to realize this).

**Comment by gled-rs** [comment]
> 

I think I had the same issue, and it was because of a symbolic link ( for future reference if someone looks for that issue again ).

IE /home/files/music is a symbolic link to /mnt/externalhd/music.

Library was configured to use /home/user/files/music. When saving m3u files in either /home/files/music or /mnt/externalhd/music, the playlist is saved with ../../../$fullpathtothefile instead of $relativepath.

When the library is configured to use the real path ( /mnt/externalhd/music ), no problems at all saving relative paths.
