### ISSUE TITLE
When a song is missing, playback stops and shows an error.

### ISSUE THREAD

**Issue by Poikilos** [strawberrymusicplayer/strawberry#958]
**Describe the bug**
When a song is missing, playback stops and shows an error that doesn't indicate what is really wrong: ""

**To Reproduce**
- Add a two songs to a playlist.
- Rename, move, or delete the second file using a file manager.
- Double-click the first song, and skip to somewhere near the end.
- When the transition to the next song occurs, instead the error occurs.

**Expected behavior**
The song should simply be skipped.
- The fact that the song's name is gray already indicates to the user that the file is missing or renamed, so no further action other than skipping it is necessary. The user has enough information.
- If the user is playing a playlist, their intent is already clear: To have uninterrupted background music.

**Screenshots:**
![image](https://user-images.githubusercontent.com/7557867/168674694-2597a0a2-02b7-4fae-a49f-26d540c7ecf8.png)
- Ignore the "superuser" part. That is merely due to installing the Flatpak as root. The program doesn't run as root.

**System Information:**
 - Operating system: Devuan 4 Chimera (based on Debian 11 Bullseye) 
 - Strawberry Version: 1.0.4 (Flatpak)

**Additional context**
- Options:
  - Cross-fade when changing tracks automatically: No

**Comment by jonaski** [comment]
I have never seen this error shown in strawberry before.
For me, when a file doesn't exist, "Resource not found" is shown.
So I suspect the error has something to do with the flatpak gstreamer installation.
I already added more info to the error dialog on GStreamer errors after 1.0.4: https://github.com/strawberrymusicplayer/strawberry/commit/c246b8f1641c48d5fc1f267a21100d7c4970efc6
Strawberry continues playback depending on the Playlist setting "continue to the next item in the playlist if a song is unavailable" if it's a non-fatal error, it correctly continues to the next track. It always shows the error, I'm not going to change that, and I've answered this before. Just because I shared a project on GitHub doesn't mean I have time to adjust Strawberry to fit every user's preference. I personally don't think it's a good idea to just ignore errors.

**Comment by poikilos** [comment]
I get "Resource not found" but not consistently. I thought flatpak would be new enough since my issue wasn't here but I'll switch to a development build as the issue instructions say.

**Comment by insunaa** [comment]
Is it possible to turn off the error popups? I have absolutely no problem with error messages showing as integrated in the UI, but Strawberry error messages frequently interrupt my work in other programs, because they just pop up in the middle of the screen. When there is a larger network issue and I'm streaming my audio files it's also possible that error messages just continuously pop up and can only be stopped by killing strawberry with htop

**Comment by poikilos** [comment]
Here it is with the development build which shows the deeper error:
> GStreamer error: state change failed and some element failed to post a proper error message with the reason for the failure.
> 
> ../libs/gst/base/gstbasesrc.c(3556): gst_base_src_start (): /GstPlayBin:pipeline-5-pipeline/GstURIDecodeBin:uridecodebin6/GstFileSrc:source: Failed to start

**Comment by jonaski** [comment]
Perhaps a GStreamer bug.

**Comment by poikilos** [comment]
@jonaski I narrowed it down to when it goes to the song on its own but not when I start playing at the song. Maybe the fade feature isn't checking whether the song exists before asking gstreamer to blend two together. Can you take a look at that?

**Comment by jonaski** [comment]
Fading is handled by entirely by strawberry itself, not gstreamer. Fading is basically just starting a new pipeline instance with the next url while the old is still playing, turning volume down on the old and up for the next.
So cross-fading is basically does the same as changing song manually, except keeping the old song playing.
This is probably what happens in your case:
1. You start playing the first song.
2. The first song is reaching the end and Starwberry tells gstreamer to pre-load the second song.
3. The URL for the second song is unavailable and gstreamer throws an error, it is ignored by strawberry because the current song needs to finish so it does not throw an error to stop playback.
4. After the first song ends, Strawberry sets the state to play, but gstreamer already us that the file was unavailable so we get a set-state error.

**Comment by lelutin** [comment]
Hi, I'm just chiming in to confirm that this is happening to me too. I'm using strawberry 1.0.7 from the debian package in debian unstable (1.0.7-1)

In my case though it's related to a permission issue -- I'm playing my music files with a different user on the computer but I forgot to set all files as readable to that other user.

I do have the cross-fader enabled as well.

The error that I get is very similar:

~~~
../libs/gst/base/gstbasesrc.c(3556): gst_base_src_start (): /GstPlayBin:pipeline-37-pipeline/GstURIDecodeBin:uridecodebin51/GstFileSrc:source: Failed to start
~~~

And when the error is shown, generally towards the end of a song, playback stops right there before ending the currently playing song.

As an aside that might not be directly relevant to the playback stopping issue: when the playback stops, if I hit "play" or "next" again strawberry always starts with the same song in the playlist (then the shuffle goes elsewhere new)

p.s.: I really love strawberry so far, I've migrated from clementine to it recently when the debian package was made available. thanks for maintaining this :)
