### ISSUE TITLE
Hijacked lyrics

### ISSUE THREAD

**Issue by dtl131** [strawberrymusicplayer/strawberry#996]
This is what I got when I played Bruce Springsteen's 'Oklahoma Home' and from 'ChartLyrics'.

I know what it's like to have failed baby
With the whole world lookin' on
I know what it's like to have soared
And come crashin' like a drunk on a bar room floor

Now you got no reason to trust me
My confidence is a little rusty
But if you don't feel like bein' alone
Baby I could walk you all the way home

Well now our old fears and failures
Baby they do linger
Like the shadow of that ring
That was on your finger
Those days they've come and gone
Baby I could walk you all the way home

Love leaves nothin' but shadows and vapor
We go on, as is our sad nature
Now it's some old Stones' song the band is trashin'
If you feel like dancin', baby I'm askin'

It's comin' on closing time
Bartender he's ringin' last call
These days I don't stand on pride
And I ain't afraid to take a fall
So if you're seein' what you like
Maybe your first choice, he's gone
Well that's all right
Baby I could walk you all the way home
Baby I could walk you all the way home

**Comment by dtl131** [comment]
WTF?

**Comment by jonaski** [comment]
http://api.chartlyrics.com/apiv1.asmx/SearchLyricDirect?artist=Bruce%20Springsteen&song=my%20oklahoma%20home
Lyrics from providers are sometimes wrong or garbage, not much we can do with that. Report it directly to ChartLyrics, or turn ChartLyrics off in the settings.

**Comment by dtl131** [comment]
The problem is that ChartLyrics may be good for some songs in a collection, so I don't want to turn it off completely. How difficult  would it be to allow the user to select lyric providers for individual songs? I am even willing to fund it if you think it's doable.
And yes, one solution is to try to manage the lyrics at their providers, but that requires creating a bunch of accounts and other issues (edit wars, bots, etc.)

Thank you for your good work and my apologies that the initial bug report was not the best...

**Comment by jonaski** [comment]
Probably the easiest is to use the tag editor and set lyrics manually for the song and it will be used instead of the providers.
Unless I quit my job I can't really take any requests at this time (it's written in the issue template and README)
Having probably spent over half of my spare time on Strawberry for over 5 years, I need to reduce the time I spend on it, so I can't take any more feature requests. I put Strawberry on GitHub so others could contribute, but there are almost no contributions over many years and GitHub is manly being used for support. I'm getting bombarded by requests even on private e-mail.
Even though I have sponsors, it's less than 100$ a month in income so it does not cover much of the time I spend, most of it gets spent on domains and hosting.
Getting any coding done anymore is hard. In the long run I will probably have to make some changes, maybe making support paid could be an option.

**Comment by dtl131** [comment]
Oh, I didn't even know I could set the lyrics manually. Now I feel stupid for making this an issue.
Sorry for the noise, and yes, do what you need to do, to pay the bills and relax in spare time. Good wishes..
