### ISSUE TITLE
Justification of Column Text Setting in Playlist Window Ignored

### ISSUE THREAD

**Issue by clementine-user** [strawberrymusicplayer/strawberry#999]
Justification of the text in the playlist columns setting is ignored. Selecting any setting, Left/Center/Right, leaves text at Left justified. This happens on all builds of Strawberry from strawberry-1.0.5.8.g4487d292-x86_64 through strawberry-1.0.6.1.g99840c9e-x86_64. Builds strawberry-1.0.5.7.g76711b9a-x86_64 and lower are not affected.

strawberry-1.0.5.7.g76711b9a-x86_64 and lower:

![1 0 5 7](https://user-images.githubusercontent.com/6315176/179632497-ba1700d1-7baa-40d1-8051-ac42535d6a7e.png)

strawberry-1.0.5.8.g4487d292-x86_64 and higher (strawberry-1.0.6.1.g99840c9e-x86_64 screenshot):

![1 0 6 1](https://user-images.githubusercontent.com/6315176/179632593-48de8838-3abd-4a04-b04b-60d717f5c496.png)

The issue is present on macOS v10.15.7 and macOS v11.6.7—multiple devices.

Not tested on macOS 12.5—probably same will test if needed.

Deleting prefs and other Strawberry related files does not change behavior.

Starting Strawberry from Terminal.app produces no error output in console.

Behavior is not present on Windows msvc builds—not tested on mingw builds.

**Comment by jonaski** [comment]
The bug is in Qt, all platformas affected, actually I had already fixed it, but the patch failed to integrate into 6.3 so 6.3.1 didn't get the fix, if I had noticed that before the new release I would of course have applied the patch. Let's hope it makes it into Qt 6.3.2.
The fix is here: https://codereview.qt-project.org/c/qt/qtbase/+/412429
